//! The Rust-entry parity gate (phase-432 W2.4, RFC-0091 §7).
//!
//! A Rust entry has two producers and will keep having two: this proc-macro
//! renders it with `quote!` at compile time, and `nros codegen entry`'s
//! `emit_rust` renders it from a `.jinja` template. Rendering the macro
//! through the pack instead was considered and REJECTED — it compiles
//! `minijinja` into every user's entry build, which is the dependency weight
//! that produced this duplication once already (issue 0083).
//!
//! So the duplication is a design decision, and this is the measurement that
//! makes it a safe one. `emit_rust.rs`'s doc comment has said since it was
//! written that it exists "for byte-level diffs against the proc-macro
//! output". No such diff existed. RFC-0091 §1 measured the bill: four
//! per-node features — params, identity, remaps, QoS overrides — reached the
//! proc-macro over four phases and left the emitter behind, so a CLI-baked
//! entry ran every node with default parameters, no remaps, its own hardcoded
//! name and no QoS overrides, from the same plan (archived issue 0302).
//!
//! ## What is compared, and why that and not more
//!
//! The **per-node runtime bake**: the block of `runtime.params` /
//! `runtime.remaps` / `runtime.qos_overrides` / `runtime.node_identity`
//! assignments and the `register` call each precedes. That is exactly the
//! text both producers emit from the same facts. The surrounding entry
//! differs by design — the macro emits tiers, lifecycle, param services and
//! executor sizing that the CLI renderer never had, which is why the
//! `--lang rust` VERB is retired rather than the renderer.
//!
//! Comparison is **token-level**, not byte-level: `quote!` has no formatting
//! and a template does, so the two agree on tokens and cannot agree on
//! whitespace. Tokens are the right granularity anyway — they are what the
//! compiler sees, and `1` versus `1u8` is a token difference the eye slides
//! over. That one is not hypothetical: building this gate found the CLI
//! rendering a QoS code as `1` where `quote!` interpolating a `u8` emits
//! `Literal::u8_suffixed`, i.e. `1u8`. The two renderings had never been the
//! same text, and nothing said so.
//!
//! ## Where the inputs live
//!
//! The corpus is `packages/cli/nros-entry-lower/testdata/parity/*.json` — in
//! the crate BOTH producers depend on, not in either producer's own tree, so
//! neither side can quietly cover a different set. The CLI's rendering is
//! `packages/cli/nros-cli-core/testdata/entry/parity_<case>.rs.golden`,
//! regenerated by its own harness with `NROS_UPDATE_GOLDEN=1`.
//!
//! A missing corpus, a missing golden or an unparseable golden is a FAILURE
//! here, never a skip: this gate's whole value is that it cannot quietly
//! measure nothing.

use std::{
    path::{Path, PathBuf},
    str::FromStr,
};

use nros_entry_lower::LoweredEntry;

/// Repo-relative anchor: this file's crate, up to the workspace root.
fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .canonicalize()
        .expect("resolve the repo root from nros-macros")
}

fn corpus_dir() -> PathBuf {
    repo_root().join("packages/cli/nros-entry-lower/testdata/parity")
}

fn cli_golden(case: &str) -> PathBuf {
    repo_root().join(format!(
        "packages/cli/nros-cli-core/testdata/entry/parity_{case}.rs.golden"
    ))
}

/// Every corpus case, by name, sorted — enumerated from the directory, the
/// same way the CLI side enumerates it.
fn cases() -> Vec<(String, LoweredEntry)> {
    let dir = corpus_dir();
    let mut paths: Vec<PathBuf> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| {
            panic!(
                "read the shared parity corpus at {}: {e}\n\
                 This gate compares this crate's rendering against \
                 `nros codegen entry`'s; with no corpus it would compare \
                 nothing and pass.",
                dir.display()
            )
        })
        .map(|e| e.expect("read corpus entry").path())
        .filter(|p| p.extension().is_some_and(|x| x == "json"))
        .collect();
    paths.sort();

    assert!(
        paths.len() >= 2,
        "the parity corpus at {} holds {} case(s); at least the bare and rich \
         cases must be present",
        dir.display(),
        paths.len()
    );

    paths
        .into_iter()
        .map(|p| {
            let name = p
                .file_stem()
                .expect("corpus file has a stem")
                .to_string_lossy()
                .into_owned();
            let text =
                std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("read {}: {e}", p.display()));
            let entry: LoweredEntry = serde_json::from_str(&text)
                .unwrap_or_else(|e| panic!("parse {} as a LoweredEntry: {e}", p.display()));
            (name, entry)
        })
        .collect()
}

/// The per-node block, lifted out of the CLI's whole-TU rendering.
///
/// Anchored on text the template emits either side of the loop: the first
/// `runtime.` assignment, and the closure's `Ok(())`. Both anchors are
/// asserted — if the template moves, this FAILS naming the anchor rather than
/// silently comparing an empty string against an empty string.
fn cli_register_block(case: &str, rendered: &str) -> String {
    let path = cli_golden(case);
    let lines: Vec<&str> = rendered.lines().collect();

    let start = lines
        .iter()
        .position(|l| l.trim_start().starts_with("runtime."))
        .unwrap_or_else(|| {
            panic!(
                "no `runtime.` assignment in {} — the CLI renderer's per-node \
                 block moved, so this gate has nothing to compare",
                path.display()
            )
        });
    let end = lines
        .iter()
        .skip(start)
        .position(|l| l.trim() == "::core::result::Result::Ok(())")
        .map(|i| i + start)
        .unwrap_or_else(|| {
            panic!(
                "no closing `::core::result::Result::Ok(())` after the per-node \
                 block in {} — the anchor moved",
                path.display()
            )
        });

    lines[start..end].join("\n")
}

/// The token SEQUENCE, flattened — whitespace, formatting and spacing gone.
///
/// Not `TokenStream::to_string()`: that re-inserts a spelling of its own, and
/// it is not stable across producers. `quote!` emits `?` and `;` as two ALONE
/// puncts and prints `? ;`, while the same two characters parsed from a
/// template's `register(runtime)?;` carry `Spacing::Joint` and print `?;`.
/// Identical to the compiler, different as strings — so a string compare would
/// report drift on every case forever and this gate would be discarded as
/// noisy within a week. `Spacing` is a formatting hint; it is deliberately not
/// part of the comparison, and neither are spans.
fn tokens(src: &str, what: &str) -> Vec<String> {
    let ts = proc_macro2::TokenStream::from_str(src)
        .unwrap_or_else(|e| panic!("{what} is not parseable Rust: {e}\n---\n{src}\n---"));
    let mut out = Vec::new();
    flatten(ts, &mut out);
    out
}

fn flatten(ts: proc_macro2::TokenStream, out: &mut Vec<String>) {
    use proc_macro2::TokenTree;
    for tt in ts {
        match tt {
            TokenTree::Group(g) => {
                out.push(format!("open {:?}", g.delimiter()));
                flatten(g.stream(), out);
                out.push(format!("close {:?}", g.delimiter()));
            }
            TokenTree::Ident(i) => out.push(format!("ident {i}")),
            TokenTree::Punct(p) => out.push(format!("punct {}", p.as_char())),
            TokenTree::Literal(l) => out.push(format!("lit {l}")),
        }
    }
}

/// A readable rendering of a flattened stream, for a failure message.
fn show(tokens: &[String]) -> String {
    tokens
        .iter()
        .map(|t| t.split_once(' ').map_or(t.as_str(), |(_, v)| v))
        .collect::<Vec<_>>()
        .join(" ")
}

/// The first index at which two token sequences differ, if any.
fn first_divergence(want: &[String], got: &[String]) -> Option<usize> {
    (0..want.len().max(got.len())).find(|&i| want.get(i) != got.get(i))
}

/// The gate: both producers render the same corpus to the same tokens.
#[test]
fn the_two_rust_entry_producers_render_the_corpus_identically() {
    let mut drift: Vec<String> = Vec::new();
    let mut compared = 0usize;

    for (case, entry) in cases() {
        let golden_path = cli_golden(&case);
        let cli_rendered = std::fs::read_to_string(&golden_path).unwrap_or_else(|e| {
            panic!(
                "read {}: {e}\n\
                 A corpus case with no CLI rendering is not coverage. Run:\n  \
                 NROS_UPDATE_GOLDEN=1 cargo test -p nros-cli-core --lib \
                 codegen::entry::parity",
                golden_path.display()
            )
        });

        let want = tokens(
            &cli_register_block(&case, &cli_rendered),
            &format!("the CLI's per-node block for `{case}`"),
        );
        let got = crate::main_macro::render_register_calls(&entry.nodes)
            .iter()
            .map(|ts| ts.to_string())
            .collect::<Vec<_>>()
            .join(" ");
        let got = tokens(&got, &format!("this macro's per-node block for `{case}`"));

        compared += 1;
        if let Some(at) = first_divergence(&want, &got) {
            // Name the FIRST divergent token as well as the two streams: the
            // blocks are long, and "which token" is the whole question.
            drift.push(format!(
                "  {case}: first difference at token {at}\n    \
                 CLI ({}) has: {:?}\n    macro has:      {:?}\n    \
                 CLI   : {}\n    macro : {}",
                golden_path.display(),
                want.get(at)
                    .map(String::as_str)
                    .unwrap_or("<end of stream>"),
                got.get(at).map(String::as_str).unwrap_or("<end of stream>"),
                show(&want),
                show(&got),
            ));
        }
    }

    assert!(
        drift.is_empty(),
        "the proc-macro and `nros codegen entry` render the same entry facts \
         DIFFERENTLY:\n{}\n\nOne of the two producers changed without the \
         other. Fix the one that is wrong; regenerate the CLI goldens only \
         when the CLI is the one that should move.",
        drift.join("\n")
    );
    assert!(
        compared >= 2,
        "only {compared} case(s) compared — a gate that measures nothing passes"
    );
}

/// The RESET is the defect this gate is most likely to meet, so it must be in
/// the compared text rather than merely in the corpus.
///
/// A producer that emits an assignment only when it has a value works for
/// every node that HAS values and leaks the previous node's state into every
/// node that does not. Asserted against the MACRO's own output, so it holds
/// even if the CLI side were to lose the property first.
#[test]
fn a_bare_node_still_gets_all_four_resets() {
    let node = nros_entry_lower::LoweredNode::bare("talker_pkg");
    let rendered = crate::main_macro::render_register_calls(std::slice::from_ref(&node))
        .iter()
        .map(|ts| ts.to_string())
        .collect::<Vec<_>>()
        .join(" ");
    let got = tokens(&rendered, "the bare node's block");

    // Spelled as SOURCE, not as a token dump: this is the exact text a bare
    // node must produce, so a reader can check the assertion by reading it.
    let want = tokens(
        r#"
        runtime.params = &[];
        runtime.remaps = &[];
        runtime.qos_overrides = &[];
        runtime.node_identity = ::core::option::Option::None;
        ::talker_pkg::register(runtime)?;
        "#,
        "the expected bare-node block",
    );

    assert_eq!(
        show(&got),
        show(&want),
        "a node with no launch facts must still write all four resets - \
         otherwise the previous node's state survives into it"
    );
}

/// Both producers must reach the SAME identifier rule. They each carried a
/// character-for-character copy of it until W2.4.
#[test]
fn a_package_name_that_is_not_an_identifier_is_sanitised_the_same_way() {
    let node = nros_entry_lower::LoweredNode::bare("talker-pkg");
    let rendered = crate::main_macro::render_register_calls(std::slice::from_ref(&node))
        .iter()
        .map(|ts| ts.to_string())
        .collect::<Vec<_>>()
        .join(" ");
    assert!(
        rendered.contains("talker_pkg"),
        "`talker-pkg` must reach `::talker_pkg::register`:\n{rendered}"
    );
    assert!(
        !rendered.contains("talker-pkg"),
        "the raw name must not survive into the emitted path (it is not \
         a valid Rust ident):\n{rendered}"
    );
}
