//! FFI declarations for zenoh-pico-shim
//!
//! This module defines the C API that the shim implements.
//!
//! # Header Generation
//!
//! The header `include/zenoh_shim.h` is automatically generated by cbindgen
//! during the build process (see `build.rs`). The build script:
//!
//! 1. Uses cbindgen to generate declarations from this module's stub functions
//! 2. Post-processes to remove duplicate declarations from the extern block
//! 3. Collapses consecutive blank lines
//!
//! To manually regenerate (if needed):
//!
//! ```bash
//! cargo build -p zenoh-pico-shim
//! ```

use core::ffi::c_void;

// c_char is used in cbindgen stubs
#[cfg(cbindgen)]
use core::ffi::c_char;

// ============================================================================
// Configuration Constants
// ============================================================================

/// Maximum number of concurrent publishers
pub const ZENOH_SHIM_MAX_PUBLISHERS: usize = 8;

/// Maximum number of concurrent subscribers
pub const ZENOH_SHIM_MAX_SUBSCRIBERS: usize = 8;

// ============================================================================
// Error Codes
// ============================================================================

/// Success
pub const ZENOH_SHIM_OK: i32 = 0;
/// Generic error
pub const ZENOH_SHIM_ERR_GENERIC: i32 = -1;
/// Configuration error
pub const ZENOH_SHIM_ERR_CONFIG: i32 = -2;
/// Session error
pub const ZENOH_SHIM_ERR_SESSION: i32 = -3;
/// Task creation error
pub const ZENOH_SHIM_ERR_TASK: i32 = -4;
/// Invalid key expression
pub const ZENOH_SHIM_ERR_KEYEXPR: i32 = -5;
/// Resource limit reached
pub const ZENOH_SHIM_ERR_FULL: i32 = -6;
/// Invalid handle
pub const ZENOH_SHIM_ERR_INVALID: i32 = -7;
/// Publish error
pub const ZENOH_SHIM_ERR_PUBLISH: i32 = -8;

// ============================================================================
// Callback Type
// ============================================================================

/// Callback function type for receiving samples.
///
/// # Parameters
/// * `data` - Pointer to received data buffer
/// * `len` - Length of data in bytes
/// * `ctx` - User-provided context pointer
pub type ShimCallback = extern "C" fn(data: *const u8, len: usize, ctx: *mut c_void);

// ============================================================================
// FFI Function Declarations
//
// The extern "C" block is in lib.rs to keep it separate from cbindgen parsing.
// cbindgen generates headers from the stub functions below (cfg(cbindgen)).
// ============================================================================

// ============================================================================
// cbindgen Stub Functions
//
// These stubs exist only for cbindgen to generate the C header.
// They are never actually called - the C implementation is linked instead.
// ============================================================================

#[cfg(cbindgen)]
mod cbindgen_stubs {
    use super::*;

    /// Initialize zenoh configuration with client mode and connect locator.
    ///
    /// # Parameters
    /// * `locator` - Connection string (e.g., "tcp/192.168.1.1:7447"), null-terminated.
    ///   Can be NULL to use default.
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_init(_locator: *const c_char) -> i32 {
        0
    }

    /// Open zenoh session and start background tasks (if threaded backend).
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_open() -> i32 {
        0
    }

    /// Check if session is currently open.
    ///
    /// # Returns
    /// Non-zero if open, 0 if closed.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_is_open() -> i32 {
        0
    }

    /// Close the session and clean up all resources.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_close() {}

    /// Declare a publisher for the given key expression.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
    ///
    /// # Returns
    /// Publisher handle (>= 0) on success, negative error code on failure.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_declare_publisher(_keyexpr: *const c_char) -> i32 {
        0
    }

    /// Publish data using publisher handle.
    ///
    /// # Parameters
    /// * `handle` - Publisher handle from zenoh_shim_declare_publisher()
    /// * `data` - Pointer to data buffer
    /// * `len` - Length of data in bytes
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_publish(_handle: i32, _data: *const u8, _len: usize) -> i32 {
        0
    }

    /// Undeclare a publisher.
    ///
    /// # Parameters
    /// * `handle` - Publisher handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_undeclare_publisher(_handle: i32) -> i32 {
        0
    }

    /// Declare a subscriber for the given key expression.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
    /// * `callback` - Callback function to invoke when samples arrive
    /// * `ctx` - User context pointer passed to callback
    ///
    /// # Returns
    /// Subscriber handle (>= 0) on success, negative error code on failure.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_declare_subscriber(
        _keyexpr: *const c_char,
        _callback: ShimCallback,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Undeclare a subscriber.
    ///
    /// # Parameters
    /// * `handle` - Subscriber handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_undeclare_subscriber(_handle: i32) -> i32 {
        0
    }

    /// Poll for incoming data and process callbacks.
    ///
    /// For threaded backends (Zephyr, POSIX), this is a no-op as background
    /// tasks handle polling automatically.
    ///
    /// For polling backends (smoltcp), this must be called regularly to
    /// process network data and dispatch callbacks.
    ///
    /// # Parameters
    /// * `timeout_ms` - Maximum time to wait for data (0 = non-blocking)
    ///
    /// # Returns
    /// Number of events processed, or negative on error.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_poll(_timeout_ms: u32) -> i32 {
        0
    }

    /// Combined poll and keepalive operation.
    ///
    /// This is equivalent to calling zenoh_shim_poll() and performing any
    /// necessary keepalive operations. For threaded backends, this is just
    /// a brief poll. For polling backends, this handles both network I/O
    /// and zenoh protocol maintenance.
    ///
    /// # Parameters
    /// * `timeout_ms` - Maximum time to wait (0 = non-blocking)
    ///
    /// # Returns
    /// Number of events processed, or negative on error.
    #[no_mangle]
    pub extern "C" fn zenoh_shim_spin_once(_timeout_ms: u32) -> i32 {
        0
    }

    /// Check if the current backend uses polling.
    ///
    /// # Returns
    /// true if polling required (smoltcp), false if threaded (Zephyr, POSIX).
    #[no_mangle]
    pub extern "C" fn zenoh_shim_uses_polling() -> bool {
        false
    }
}
