//! FFI declarations for zpico-sys
//!
//! This module defines the C API that zpico implements and the
//! platform FFI functions that Rust provides.
//!
//! # Header Generation
//!
//! The header `c/include/zpico.h` is automatically generated by cbindgen
//! during the build process (see `build.rs`).

use core::ffi::c_void;

// c_char is used in cbindgen stubs
#[cfg(cbindgen)]
use core::ffi::c_char;

// ============================================================================
// Protocol Constants
// ============================================================================

/// Size of Zenoh ID in bytes
pub const ZPICO_ZID_SIZE: usize = 16;

/// Size of RMW GID in bytes (for ROS 2 humble compatibility)
pub const ZPICO_RMW_GID_SIZE: usize = 16;

// ============================================================================
// Error Codes
// ============================================================================

/// Success
pub const ZPICO_OK: i32 = 0;
/// Generic error
pub const ZPICO_ERR_GENERIC: i32 = -1;
/// Configuration error
pub const ZPICO_ERR_CONFIG: i32 = -2;
/// Session error
pub const ZPICO_ERR_SESSION: i32 = -3;
/// Task creation error
pub const ZPICO_ERR_TASK: i32 = -4;
/// Invalid key expression
pub const ZPICO_ERR_KEYEXPR: i32 = -5;
/// Resource limit reached
pub const ZPICO_ERR_FULL: i32 = -6;
/// Invalid handle
pub const ZPICO_ERR_INVALID: i32 = -7;
/// Publish error
pub const ZPICO_ERR_PUBLISH: i32 = -8;
/// Query timeout
pub const ZPICO_ERR_TIMEOUT: i32 = -9;
/// Caller's buffer cannot hold the value, which is REFUSED rather than
/// truncated (phase-381 W1) — a partial keyexpr names a different, plausible
/// entity, so `zpico_liveliness_entry` never returns one.
pub const ZPICO_ERR_BUFFER: i32 = -10;

// ============================================================================
// Callback Types
// ============================================================================

/// Callback function type for receiving samples (legacy, payload only).
///
/// # Parameters
/// * `data` - Pointer to received data buffer
/// * `len` - Length of data in bytes
/// * `ctx` - User-provided context pointer
pub type ZpicoCallback = extern "C" fn(data: *const u8, len: usize, ctx: *mut c_void);

/// Callback function type for receiving samples with attachment (RMW compatible).
///
/// # Parameters
/// * `data` - Pointer to received data buffer
/// * `len` - Length of data in bytes
/// * `attachment` - Pointer to attachment buffer (may be NULL)
/// * `attachment_len` - Length of attachment in bytes
/// * `ctx` - User-provided context pointer
pub type ZpicoCallbackWithAttachment = extern "C" fn(
    data: *const u8,
    len: usize,
    attachment: *const u8,
    attachment_len: usize,
    ctx: *mut c_void,
);

/// Notify callback for direct-write subscribers.
///
/// Called after the C shim has written the payload directly into the Rust
/// static buffer. Only provides the payload length and attachment data.
///
/// # Parameters
/// * `len` - Length of payload already written to the buffer
/// * `attachment` - Pointer to attachment buffer (may be NULL)
/// * `attachment_len` - Length of attachment in bytes
/// * `ctx` - User-provided context pointer
pub type ZpicoNotifyCallback =
    extern "C" fn(len: usize, attachment: *const u8, attachment_len: usize, ctx: *mut c_void);

/// Zero-copy callback: data pointer is borrowed from zenoh-pico's receive buffer.
/// Only valid during the callback invocation. Requires `unstable-zenoh-api` feature.
///
/// # Parameters
/// * `data` - Pointer to payload in zenoh-pico's internal buffer (borrowed, NOT owned)
/// * `len` - Length of payload in bytes
/// * `attachment` - Pointer to attachment buffer (may be NULL)
/// * `attachment_len` - Length of attachment in bytes
/// * `ctx` - User-provided context pointer
pub type ZpicoZeroCopyCallback = extern "C" fn(
    data: *const u8,
    len: usize,
    attachment: *const u8,
    attachment_len: usize,
    ctx: *mut c_void,
);

/// Callback function type for receiving queries (service requests).
///
/// # Parameters
/// * `keyexpr` - Key expression string (not null-terminated)
/// * `keyexpr_len` - Length of key expression
/// * `payload` - Pointer to request payload (may be NULL)
/// * `payload_len` - Length of payload in bytes
/// * `ctx` - User-provided context pointer
pub type ZpicoQueryCallback = extern "C" fn(
    keyexpr: *const core::ffi::c_char,
    keyexpr_len: usize,
    payload: *const u8,
    payload_len: usize,
    ctx: *mut c_void,
);

// ============================================================================
// cbindgen Stub Functions for Shim API
//
// These stubs exist only for cbindgen to generate the C header.
// They are never actually called - the C implementation is linked instead.
// ============================================================================

#[cfg(cbindgen)]
mod cbindgen_stubs {
    use super::*;

    /// Opaque per-session handle (issue 0348 / phase-328). A `zpico_session_t*`
    /// points into the C shim's compile-time session pool
    /// (`ZPICO_MAX_SESSIONS`, default 1). Every `zpico_*` entry point that
    /// operates on a session takes one as its leading argument. Rust never
    /// dereferences it — it is a bare pointer forwarded to the C shim.
    #[repr(C)]
    pub struct zpico_session_t {
        _private: [u8; 0],
    }

    /// Acquire a free slot from the C shim's session pool. Returns NULL when
    /// the pool (`ZPICO_MAX_SESSIONS`) is exhausted. Pair with
    /// `zpico_session_release` after `zpico_close`.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_session_acquire() -> *mut zpico_session_t {
        core::ptr::null_mut()
    }

    /// Return a slot to the pool. Call after `zpico_close`; the pointer is
    /// invalid afterwards.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_session_release(_session: *mut zpico_session_t) {}

    /// The session's pool index (0..ZPICO_MAX_SESSIONS), or -1 if invalid.
    /// Scopes the Rust shim's process-global tables per session (issue 0376).
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_session_index(_session: *mut zpico_session_t) -> i32 {
        -1
    }

    /// A key-value property for transport configuration.
    #[repr(C)]
    pub struct zpico_property_t {
        /// Property key (null-terminated C string)
        pub key: *const c_char,
        /// Property value (null-terminated C string)
        pub value: *const c_char,
    }

    /// Phase 124.D.3.c — SPSC ring descriptor for burst-tolerant
    /// direct-write subscribers. C shim is the sole producer
    /// (writes payloads, advances `tail`); Rust shim the sole
    /// consumer (reads payloads, advances `head`). Slot index is
    /// `counter % slot_count`. Backing storage owned by the Rust
    /// `SubscriberBuffer`.
    #[repr(C)]
    pub struct zpico_ring_desc_t {
        /// `slot_count * payload_stride` bytes of payload storage.
        pub payload_base: *mut u8,
        /// Bytes between payload slot starts.
        pub payload_stride: usize,
        /// `slot_count * att_stride` bytes of attachment storage.
        pub att_base: *mut u8,
        /// Bytes between attachment slot starts.
        pub att_stride: usize,
        /// Number of ring slots N.
        pub slot_count: usize,
        /// `slot_count` entries — per-slot payload length.
        pub payload_len: *mut usize,
        /// `slot_count` entries — per-slot attachment length.
        pub att_len: *mut usize,
        /// Consumer counter — written only by the Rust shim.
        pub head: *mut usize,
        /// Producer counter — written only by the C shim.
        pub tail: *mut usize,
    }

    /// Initialize zenoh configuration with client mode and connect locator.
    ///
    /// # Parameters
    /// * `locator` - Connection string (e.g., "tcp/192.168.1.1:7447"), null-terminated.
    ///   Can be NULL to use default.
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_init(_session: *mut zpico_session_t, _locator: *const c_char) -> i32 {
        0
    }

    /// Initialize zenoh configuration with mode, locator, and properties.
    ///
    /// # Parameters
    /// * `locator` - Connection string (e.g., "tcp/192.168.1.1:7447"), null-terminated.
    ///   Can be NULL for peer mode.
    /// * `mode` - Session mode string ("client" or "peer"), null-terminated.
    /// * `properties` - Array of key-value properties, or NULL.
    /// * `num_properties` - Number of properties in the array.
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_init_with_config(
        _session: *mut zpico_session_t,
        _locator: *const c_char,
        _mode: *const c_char,
        _properties: *const zpico_property_t,
        _num_properties: usize,
    ) -> i32 {
        0
    }

    /// Open zenoh session and start background tasks (if threaded backend).
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_open(_session: *mut zpico_session_t) -> i32 {
        0
    }

    /// Check if session is currently open.
    ///
    /// # Returns
    /// Non-zero if open, 0 if closed.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_is_open(_session: *mut zpico_session_t) -> i32 {
        0
    }

    /// Phase 124.F.2 — wire-level connectivity probe.
    ///
    /// Returns 0 on success (transport accepted a keep-alive frame),
    /// `ZPICO_ERR_SESSION` if no session is open, `ZPICO_ERR_TIMEOUT`
    /// if the send failed (treated as a probe timeout — caller maps
    /// to `NROS_RMW_RET_TIMEOUT`).
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_send_keep_alive(_session: *mut zpico_session_t) -> i32 {
        ZPICO_ERR_SESSION
    }

    /// Phase 124.E.3 — streamed publish driven by `z_bytes_writer`.
    ///
    /// Returns 0 on success, `ZPICO_ERR_*` on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_publish_streamed(
        _session: *mut zpico_session_t,
        _handle: i32,
        _total_len: usize,
        _chunk_cb: Option<
            unsafe extern "C" fn(
                out_buf: *mut u8,
                cap: usize,
                out_written: *mut usize,
                user_ctx: *mut c_void,
            ),
        >,
        _user_ctx: *mut c_void,
        _attachment: *const u8,
        _attachment_len: usize,
    ) -> i32 {
        ZPICO_ERR_INVALID
    }

    /// Close the session and clean up all resources.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_close(_session: *mut zpico_session_t) {}

    /// Configure scheduling attributes for zenoh-pico read and lease background tasks.
    ///
    /// Must be called between `zpico_init()` and `zpico_open()`.  If not called,
    /// `zpico_open()` passes NULL to zenoh-pico (platform defaults).
    ///
    /// Priority and stack values are platform-specific (already mapped by the caller).
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_set_task_config(
        _read_priority: u32,
        _read_stack_bytes: u32,
        _lease_priority: u32,
        _lease_stack_bytes: u32,
    ) {
    }

    /// Declare a publisher for the given key expression.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
    ///
    /// # Returns
    /// Publisher handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_declare_publisher(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
    ) -> i32 {
        0
    }

    /// Declare a publisher with options (stub). `_is_express` mirrors the real
    /// shim's phase-279 express hint.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_declare_publisher_ex(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _is_express: i32,
    ) -> i32 {
        0
    }

    /// Publish data using publisher handle.
    ///
    /// # Parameters
    /// * `handle` - Publisher handle from zpico_declare_publisher()
    /// * `data` - Pointer to data buffer
    /// * `len` - Length of data in bytes
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_publish(
        _session: *mut zpico_session_t,
        _handle: i32,
        _data: *const u8,
        _len: usize,
    ) -> i32 {
        0
    }

    /// Undeclare a publisher.
    ///
    /// # Parameters
    /// * `handle` - Publisher handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_undeclare_publisher(
        _session: *mut zpico_session_t,
        _handle: i32,
    ) -> i32 {
        0
    }

    /// Declare a subscriber for the given key expression.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
    /// * `callback` - Callback function to invoke when samples arrive
    /// * `ctx` - User context pointer passed to callback
    ///
    /// # Returns
    /// Subscriber handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_declare_subscriber(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _callback: ZpicoCallback,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Declare a subscriber with attachment support for RMW compatibility.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
    /// * `callback` - Callback function to invoke when samples arrive (includes attachment)
    /// * `ctx` - User context pointer passed to callback
    ///
    /// # Returns
    /// Subscriber handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_declare_subscriber_with_attachment(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _callback: ZpicoCallbackWithAttachment,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Declare a subscriber with direct-write to a Rust buffer.
    ///
    /// The C shim reads the payload directly into `buf_ptr` using
    /// `z_bytes_reader_read()`, avoiding a malloc. The notify callback
    /// is called after the write completes, providing only the length
    /// and attachment.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string, null-terminated.
    /// * `buf_ptr` - Pointer to the Rust static buffer for payload
    /// * `buf_capacity` - Size of the buffer in bytes
    /// * `locked_ptr` - Pointer to the AtomicBool lock flag
    /// * `callback` - Notify callback (payload length + attachment)
    /// * `ctx` - User context pointer passed to callback
    ///
    /// # Returns
    /// Subscriber handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_declare_subscriber_direct_write(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _buf_ptr: *mut u8,
        _buf_capacity: usize,
        _locked_ptr: *const bool,
        _callback: ZpicoNotifyCallback,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Phase 124.D.3.c — declare a burst-tolerant direct-write
    /// subscriber backed by an SPSC ring. Each message lands in the
    /// next free ring slot rather than a single shared slot, so a
    /// burst arriving between two `take` calls is buffered
    /// instead of dropped. The `notify` callback fires once per
    /// message for async-waker support.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string, null-terminated.
    /// * `desc` - Ring descriptor; must outlive the subscriber.
    /// * `callback` - Notify callback (per-message arrival signal).
    /// * `ctx` - User context pointer passed to callback.
    ///
    /// # Returns
    /// Subscriber handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_declare_subscriber_ring(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _desc: *mut zpico_ring_desc_t,
        _callback: ZpicoNotifyCallback,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Declare a zero-copy subscriber for the given key expression.
    ///
    /// The callback receives a borrowed pointer directly into zenoh-pico's
    /// internal receive buffer. The pointer is only valid during the callback.
    /// Requires `Z_FEATURE_UNSTABLE_API` to be enabled.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string, null-terminated.
    /// * `callback` - Zero-copy callback (borrowed data pointer + attachment)
    /// * `ctx` - User context pointer passed to callback
    ///
    /// # Returns
    /// Subscriber handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_subscribe_zero_copy(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _callback: ZpicoZeroCopyCallback,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Undeclare a subscriber.
    ///
    /// # Parameters
    /// * `handle` - Subscriber handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_undeclare_subscriber(
        _session: *mut zpico_session_t,
        _handle: i32,
    ) -> i32 {
        0
    }

    /// Combined poll and keepalive operation.
    ///
    /// For threaded backends, this is just a brief poll. For polling
    /// backends, this handles both network I/O and zenoh protocol
    /// maintenance (keep-alives).
    ///
    /// # Parameters
    /// * `timeout_ms` - Maximum time to wait (0 = non-blocking)
    ///
    /// # Returns
    /// Number of events processed, or negative on error.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_spin_once(_session: *mut zpico_session_t, _timeout_ms: u32) -> i32 {
        0
    }

    /// Check if the current backend uses polling.
    ///
    /// # Returns
    /// true if polling required (smoltcp), false if threaded (Zephyr, POSIX).
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_uses_polling() -> bool {
        false
    }

    // ========================================================================
    // ZenohId API
    // ========================================================================

    /// Get the session's Zenoh ID.
    ///
    /// # Parameters
    /// * `zid_out` - Pointer to 16-byte buffer to receive the ZID
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_get_zid(_session: *mut zpico_session_t, _zid_out: *mut u8) -> i32 {
        0
    }

    // ========================================================================
    // Liveliness API
    // ========================================================================

    /// Declare a liveliness token for ROS 2 discovery.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string, null-terminated.
    ///
    /// # Returns
    /// Liveliness handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_declare_liveliness(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
    ) -> i32 {
        0
    }

    /// Undeclare a liveliness token.
    ///
    /// # Parameters
    /// * `handle` - Liveliness handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_undeclare_liveliness(
        _session: *mut zpico_session_t,
        _handle: i32,
    ) -> i32 {
        0
    }

    // ========================================================================
    // Publish with Attachment API
    // ========================================================================

    /// Publish data with an attachment (for RMW compatibility).
    ///
    /// # Parameters
    /// * `handle` - Publisher handle
    /// * `data` - Pointer to data buffer
    /// * `len` - Length of data in bytes
    /// * `attachment` - Pointer to attachment buffer (may be NULL)
    /// * `attachment_len` - Length of attachment in bytes
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_publish_with_attachment(
        _session: *mut zpico_session_t,
        _handle: i32,
        _data: *const u8,
        _len: usize,
        _attachment: *const u8,
        _attachment_len: usize,
    ) -> i32 {
        0
    }

    // ========================================================================
    // Queryable API (for ROS 2 Services)
    // ========================================================================

    /// Declare a queryable for receiving service requests.
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string, null-terminated.
    /// * `callback` - Callback function to invoke when queries arrive
    /// * `ctx` - User context pointer passed to callback
    ///
    /// # Returns
    /// Queryable handle (>= 0) on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_declare_queryable(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _callback: ZpicoQueryCallback,
        _ctx: *mut c_void,
    ) -> i32 {
        0
    }

    /// Undeclare a queryable.
    ///
    /// # Parameters
    /// * `handle` - Queryable handle
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_undeclare_queryable(
        _session: *mut zpico_session_t,
        _handle: i32,
    ) -> i32 {
        0
    }

    /// Reply to a query (must be called within query callback).
    ///
    /// # Parameters
    /// * `keyexpr` - Reply key expression string, null-terminated.
    /// * `data` - Pointer to reply data buffer
    /// * `len` - Length of data in bytes
    /// * `attachment` - Pointer to attachment buffer (may be NULL)
    /// * `attachment_len` - Length of attachment in bytes
    ///
    /// # Returns
    /// 0 on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_query_reply(
        _session: *mut zpico_session_t,
        _queryable_handle: i32,
        _reply_seq: i64,
        _keyexpr: *const c_char,
        _data: *const u8,
        _len: usize,
        _attachment: *const u8,
        _attachment_len: usize,
    ) -> i32 {
        0
    }

    /// Phase 237 — reply-slot index from the most recent query callback (the
    /// deferred-reply seq); call from inside the synchronous query callback.
    /// Stub returns -1 (no slot) in the pure-Rust no-op build.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_queryable_take_reply_seq(
        _session: *mut zpico_session_t,
        _queryable_handle: i32,
    ) -> i64 {
        -1
    }

    /// Send a query and wait for reply (blocking, for service client).
    ///
    /// # Parameters
    /// * `keyexpr` - Key expression string, null-terminated.
    /// * `payload` - Request payload (may be NULL)
    /// * `payload_len` - Length of payload in bytes
    /// * `reply_buf` - Buffer to receive reply data
    /// * `reply_buf_size` - Size of reply buffer
    /// * `timeout_ms` - Timeout in milliseconds
    ///
    /// # Returns
    /// Number of bytes in reply on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_get(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _payload: *const u8,
        _payload_len: usize,
        _reply_buf: *mut u8,
        _reply_buf_size: usize,
        _timeout_ms: u32,
    ) -> i32 {
        0
    }

    /// Start a non-blocking query (for async service client).
    ///
    /// Returns a non-negative slot handle on success, negative error code on failure.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_get_start(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _payload: *const u8,
        _payload_len: usize,
        _timeout_ms: u32,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Issue 0153 — attachment-carrying query start (rmw_zenoh service interop).
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_get_start_with_attachment(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _payload: *const u8,
        _payload_len: usize,
        _attachment: *const u8,
        _attachment_len: usize,
        _timeout_ms: u32,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Check for a reply to a pending non-blocking query.
    ///
    /// Returns positive byte count on reply, 0 if still pending, negative on error/timeout.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_get_check(
        _session: *mut zpico_session_t,
        _handle: i32,
        _reply_buf: *mut u8,
        _reply_buf_size: usize,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Start a non-blocking liveliness query (for wait_for_service).
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_liveliness_get_start(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _timeout_ms: u32,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Poll a pending liveliness query.
    ///
    /// Returns 1 on first matching token reply, 0 if still pending, -9 on
    /// timeout (dropper fired without replies), other negative on error.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_liveliness_get_check(
        _session: *mut zpico_session_t,
        _handle: i32,
    ) -> i32 {
        -1 // stub: not available
    }

    /// phase-381 W1 — a liveliness query that KEEPS its replies' keyexprs.
    ///
    /// `zpico_liveliness_get_start` answers "does anything match"; reading the
    /// ROS graph needs "WHAT matched", and a liveliness reply carries all of it
    /// in the keyexpr. Same slot pool, same start/poll shape — poll with
    /// `zpico_liveliness_get_check`, then read with the two below. Costs no
    /// extra storage: the slot's reply buffer is dead weight on a liveliness
    /// query, whose token payload is empty.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_liveliness_collect_start(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
        _timeout_ms: u32,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Has the collecting sweep FINISHED (dropper fired)? Distinct from
    /// `zpico_liveliness_get_check`, which reports the FIRST reply.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_liveliness_collect_done(
        _session: *mut zpico_session_t,
        _handle: i32,
    ) -> i32 {
        -1 // stub: not available
    }

    /// How many keyexprs the slot STORED — distinct from
    /// `zpico_liveliness_get_count`, which reports how many ARRIVED. They differ
    /// exactly when the buffer could not hold an entry, so comparing the two is
    /// how a caller learns the enumeration was truncated.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_liveliness_entry_count(
        _session: *mut zpico_session_t,
        _handle: i32,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Copy stored keyexpr `index` into `out`, NUL-terminated. Returns the byte
    /// count excluding the NUL, `ZPICO_ERR_INVALID` for a bad handle or index,
    /// or `ZPICO_ERR_BUFFER` when `cap` cannot hold the entry plus its NUL — a
    /// short buffer is refused rather than truncated.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_liveliness_entry(
        _session: *mut zpico_session_t,
        _handle: i32,
        _index: u32,
        _out: *mut c_char,
        _cap: usize,
    ) -> i32 {
        -1 // stub: not available
    }

    /// phase-381 / issue 0903 — start the standing graph cache (a liveliness
    /// SUBSCRIBER with history), replacing the per-question sweep. Idempotent.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_graph_cache_start(
        _session: *mut zpico_session_t,
        _keyexpr: *const c_char,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Stop the graph cache and release its subscriber. Idempotent.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_graph_cache_stop(_session: *mut zpico_session_t) -> i32 {
        -1 // stub: not available
    }

    /// How many tokens the graph cache holds; `out_dropped` receives how many
    /// did not fit.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_graph_entry_count(
        _session: *mut zpico_session_t,
        _out_dropped: *mut u32,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Copy cached keyexpr `index` into `out`, NUL-terminated.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_graph_entry_at(
        _session: *mut zpico_session_t,
        _index: u32,
        _out: *mut c_char,
        _cap: usize,
    ) -> i32 {
        -1 // stub: not available
    }

    /// phase-428 W13 — the PURE half of the graph-cache sample handler: apply
    /// one liveliness sample (PUT inserts once, DELETE removes and closes the
    /// gap, a PUT that does not fit is COUNTED in `dropped`) to a
    /// NUL-separated token set in a caller buffer. Split out like
    /// `zpico_entry_at` so the set `service_is_ready` answers from is testable
    /// without a session. Returns 1 if the set changed, 0 if not,
    /// `ZPICO_ERR_INVALID` for a NULL argument.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_graph_set_apply(
        _buf: *mut u8,
        _cap: usize,
        _len: *mut usize,
        _count: *mut u32,
        _dropped: *mut u32,
        _key: *const c_char,
        _klen: usize,
        _remove: bool,
    ) -> i32 {
        -1 // stub: not available
    }

    /// The PURE half of `zpico_liveliness_entry`: index into a NUL-separated
    /// run. Split out so the walk is testable WITHOUT a live session, because
    /// this is where an off-by-one costs a WRONG keyexpr rather than a missing
    /// one.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_entry_at(
        _buf: *const u8,
        _len: usize,
        _count: u32,
        _index: u32,
        _out: *mut c_char,
        _cap: usize,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Phase 108.C.zenoh.4-followup — count of liveliness-token
    /// replies on this slot. Used by the subscriber-side
    /// `LivelinessChanged` bridge to surface `alive_count > 1`.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_liveliness_get_count(
        _session: *mut zpico_session_t,
        _handle: i32,
    ) -> i32 {
        -1 // stub: not available
    }

    /// Register a reply waker callback for async service client support.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_set_reply_waker(
        _session: *mut zpico_session_t,
        _func: Option<unsafe extern "C" fn(i32, i32)>,
    ) {
    }

    /// Capture the current clock into an opaque 16-byte buffer.
    /// Used by FFI reentrancy guard timeout decomposition.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_clock_start(_clock_buf: *mut u8) {}

    /// Return elapsed milliseconds since a clock captured by `zpico_clock_start`.
    #[unsafe(no_mangle)]
    pub extern "C" fn zpico_clock_elapsed_ms_since(_clock_buf: *mut u8) -> core::ffi::c_ulong {
        0
    }
}
