// emit:ok
// nros-c message type - C header for embedded systems
// Package: fingerprint-corpus
// Message: Nested
// Auto-generated by rosidl-codegen - do not edit

#ifndef FINGERPRINT_CORPUS_MSG_NESTED_H
#define FINGERPRINT_CORPUS_MSG_NESTED_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <nros/types.h>

#include <nros/nros_config_generated.h>

/* RFC-0090 — emitted by nano-ros codegen version 1. */
#define NROS_EMITTED_CODEGEN_VERSION 1

#ifndef NROS_CODEGEN_VERSION
#error "nros: the generated config header did not define NROS_CODEGEN_VERSION. This generated artifact cannot tell whether the runtime accepts it; rebuild the nano-ros runtime so its config header is regenerated."
#elif NROS_EMITTED_CODEGEN_VERSION < NROS_CODEGEN_VERSION_MIN \
   || NROS_EMITTED_CODEGEN_VERSION > NROS_CODEGEN_VERSION
#error "nros: this generated tree was emitted at a codegen version the runtime does not accept (see NROS_EMITTED_CODEGEN_VERSION above against NROS_CODEGEN_VERSION_MIN..NROS_CODEGEN_VERSION in nros_config_generated.h). Regenerate it against the runtime you are building: `nros sync` in a consumer workspace."
#endif

#ifdef __cplusplus
extern "C" {
#endif
#include "fingerprint_corpus_msg_shapes.h"

// Constants

/// Nested message structure
typedef struct fingerprint_corpus_msg_nested {
    struct fingerprint_corpus_msg_shapes one;
    struct { uint32_t size; struct fingerprint_corpus_msg_shapes data[64]; } many;
} fingerprint_corpus_msg_nested;

/// RFC-0088 D5 — the serialization format this type is encoded in, as the
/// image-local `nros_serdes::format::SerializationFormatId` discriminant.
///
/// This pack emits a CDR serializer (fingerprint_corpus_msg_nested_serialize writes a CDR
/// encapsulation header), so the answer is a property of the GENERATOR, not a
/// value copied from a backend: what this header contains IS CDR.
#define NROS_MSG_FORMAT_ID_fingerprint_corpus_msg_nested NROS_SERIALIZATION_FORMAT_ID_CDR

/* One image links one backend and one backend speaks one encoding (RFC-0088),
   so a message this image cannot encode is a build error rather than a runtime
   surprise on the wire. NROS_SERIALIZATION_FORMAT_ID comes in via
   <nros/types.h> above; a bridge image, which links two backends and has no
   single answer, must not reach it at all (check-format-macro-scope). */
NROS_ASSERT_MESSAGE_FORMAT(NROS_MSG_FORMAT_ID_fingerprint_corpus_msg_nested, "fingerprint-corpus/Nested");

/// Get the ROS type name for Nested
static inline const char* fingerprint_corpus_msg_nested_get_type_name(void) {
    return "fingerprint-corpus::msg::dds_::Nested_";
}

/// Get the type hash for Nested
static inline const char* fingerprint_corpus_msg_nested_get_type_hash(void) {
    return "h";
}

/// Initialize a Nested message to default values
void fingerprint_corpus_msg_nested_init(fingerprint_corpus_msg_nested* msg);

/// Release heap-backed (`mode = "heap"`, RFC-0033) fields and re-zero them.
/// Safe on a zero-initialized or already-fini'd message; a no-op when the
/// message has no heap fields. Call after deserializing a message with heap
/// sequences to avoid leaking the malloc'd element buffers.
void fingerprint_corpus_msg_nested_fini(fingerprint_corpus_msg_nested* msg);

/// Serialize a Nested message to CDR format (writes a fresh
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error. On success, *serialized_size contains
/// bytes written.
int32_t fingerprint_corpus_msg_nested_serialize(const fingerprint_corpus_msg_nested* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size);

/// Deserialize a Nested message from CDR format (expects a
/// 4-byte CDR encapsulation header followed by the fields).
/// Returns 0 on success, -1 on error
int32_t fingerprint_corpus_msg_nested_deserialize(fingerprint_corpus_msg_nested* msg, const uint8_t* buffer, size_t buffer_size);

/// Serialize a Nested inline into an already-open CDR stream,
/// without emitting its own encapsulation header. Used by parent messages,
/// services, and actions that embed this type as a nested field.
/// - ptr_ref: in/out current write pointer (advanced on success)
/// - end: one-past-last byte of the destination buffer
/// - origin: CDR alignment origin (start of the surrounding encapsulation)
/// Returns 0 on success, -1 on error.
int32_t fingerprint_corpus_msg_nested_serialize_inline(const fingerprint_corpus_msg_nested* msg, uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Deserialize a Nested inline from an already-open CDR stream,
/// without consuming an encapsulation header. Parameters mirror the inline
/// serialize variant.
int32_t fingerprint_corpus_msg_nested_deserialize_inline(fingerprint_corpus_msg_nested* msg, const uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin);

/// Get the nros_message_type_t for this message type
const nros_message_type_t* fingerprint_corpus_msg_nested_get_type_support(void);


/// NO size bound is emitted for this type.
///
/// Reason: nested type `fingerprint-corpus/Shapes` could not be resolved
///
/// "unbounded member" means the bound was computed and does not exist -- bound
/// the field in the `.msg` (`string<=64`), or give it an INLINE `cap` in
/// `nros-codegen.toml` (`[fields]` / `[types]` / `[packages]` / `[defaults]`).
/// A `heap` or `view` cap is a sizing hint nothing enforces (RFC-0033 "What each
/// mode GUARANTEES"), so it deliberately does not bound. EVERY offending member
/// is listed above, so one build names everything there is to fix (phase-403
/// W0). "could not be resolved" means the bound was NOT computed, because a
/// nested type was not reachable; that is a search-path problem, not a property
/// of the message. Issue 0896.

/* issue 0896 layer 5 -- naming the size constant of an unbounded type is a
   deliberate error, and this makes the compiler SAY SO. Without it the
   constant is simply absent and the user gets "undeclared identifier", which
   names neither the type nor the member that costs it the bound. */
#define FINGERPRINT_CORPUS_MSG_NESTED_TX_MAX_SERIALIZED_SIZE \
    NROS_UNRESOLVED__fingerprint_corpus_msg_nested__nested_type_fingerprint_corpus_Shapes
#define FINGERPRINT_CORPUS_MSG_NESTED_RX_MAX_SERIALIZED_SIZE \
    NROS_UNRESOLVED__fingerprint_corpus_msg_nested__nested_type_fingerprint_corpus_Shapes


/// Typed publish helper. Serializes `msg` into a stack buffer sized from the
/// type's own bound where one exists, and from `NROS_PUB_BUFFER_SIZE`
/// otherwise. nros_ret_t / nros_publisher_t / nros_publish_raw all come in via
/// <nros/types.h> (already included at the top of this header).
#ifndef NROS_PUB_BUFFER_SIZE
#define NROS_PUB_BUFFER_SIZE 256
#endif
static inline nros_ret_t fingerprint_corpus_msg_nested_publish(struct nros_publisher_t* publisher,
                                                   const fingerprint_corpus_msg_nested* msg) {

    /* No bound for this type (nested type `fingerprint-corpus/Shapes` could not be resolved), so the global knob is
       still the only available answer. */
    uint8_t buf[NROS_PUB_BUFFER_SIZE];

    size_t n = 0;
    int32_t r = fingerprint_corpus_msg_nested_serialize(msg, buf, sizeof(buf), &n);
    if (r != 0) return r;
    return nros_publish_raw(publisher, buf, n);
}

/// Typed subscribe helper -- the sibling of fingerprint_corpus_msg_nested_publish above.
///
/// A MACRO, not a function, deliberately. It expands at the CALL SITE, where
/// <nros/component.h> is already included, so this header keeps its single
/// include of <nros/types.h> and takes no dependency on the component ABI.
/// nros_cpp_subscription_register, nros_cpp_node_t, nros_c_qos_default and
/// nros_c_subscription_callback_t all come from component.h and none of them is
/// named until the macro is actually used.
///
/// ONE token names the type. The ROS type name, the type hash and the
/// receive-buffer size hint are all derived from it, so they cannot disagree.
/// The hand-written raw register this replaces named the type TWICE -- once for
/// _get_type_name() and once for the buffer hint -- with nothing checking the
/// two agreed (issue 0896).
///
/// The `_subscribe_sized` form is the same call with the hint chosen by the
/// caller: for a type with no receive bound, and for anyone deliberately
/// overriding the type's own number. `rx_bytes` is a HINT (0 = image default),
/// never a promise that larger samples are refused.
///
/// C ONLY. The options struct is passed as a compound literal, and C++ cannot
/// take the address of one ("taking address of rvalue"), so the C++ arm below
/// names a C++ answer instead of leaving that diagnostic to be decoded. C++
/// callers have a typed subscription already -- nros::Subscription<M> over the
/// generated .hpp -- and it carries no hint yet; that is the C++ sibling of
/// this work, not something this macro can supply.
#define fingerprint_corpus_msg_nested_subscribe_sized(node, topic, cb, ctx, out_handle, rx_bytes) \
    nros_cpp_subscription_register_hinted( \
        (node), (topic), fingerprint_corpus_msg_nested_get_type_name(), fingerprint_corpus_msg_nested_get_type_hash(), \
        nros_c_qos_default(), (cb), (ctx), (out_handle), (uint32_t)(rx_bytes))

/* issue 0896 layer 5 -- this type has NO receive bound
   (nested type `fingerprint-corpus/Shapes` could not be resolved), so there is no number a plain `_subscribe` could
   pass, and sizing the buffer is a decision only the caller can make. The macro
   is emitted anyway, POISONED, so the diagnostic names the type and the member
   that costs it the bound instead of reporting an undeclared function.
   Either remove the cause -- see the reason block above, which says whether the
   bound is ABSENT (bound the field) or merely UNCOMPUTED (fix the search path)
   -- or call the `_subscribe_sized` form above with a byte count you chose. */
#define fingerprint_corpus_msg_nested_subscribe(node, topic, cb, ctx, out_handle) \
    NROS_UNRESOLVED__fingerprint_corpus_msg_nested__nested_type_fingerprint_corpus_Shapes


/// phase-417 W5.a — the TYPED delivery glue: the callback receives a
/// deserialised Nested, not CDR bytes.
///
/// `fingerprint_corpus_msg_nested_deserialize` already writes into caller-owned storage and
/// returns 0/-1 — the executor's typed path needs exactly that, with the type
/// erased. This is a real function with the erased signature rather than a cast
/// of `fingerprint_corpus_msg_nested_deserialize`: calling through a function pointer of a
/// different type is undefined even where it happens to work, and a
/// control-flow-integrity build traps on it.
static inline int32_t fingerprint_corpus_msg_nested_deserialize_erased(void* msg, const uint8_t* buffer,
                                                           size_t buffer_size) {
    return fingerprint_corpus_msg_nested_deserialize((fingerprint_corpus_msg_nested*)msg, buffer, buffer_size);
}

/// rclc-shaped typed registration for Nested.
///
///     rclc_executor_add_subscription_with_context(&exec, &sub, &msg, &cb, &ctx, ON_NEW_DATA);
///     fingerprint_corpus_msg_nested_executor_add_subscription(&exec, &sub, &msg, &cb, &ctx,
///                                                 NROS_EXECUTOR_ON_NEW_DATA);
///
/// Six arguments, rclc's order. The deserialiser and the receive-buffer hint are
/// derived from the ONE type token, so they cannot disagree with each other or
/// with the type — the same argument `fingerprint_corpus_msg_nested_subscribe` above makes
/// for the raw path.
///
/// `cb` is an `nros_typed_subscription_callback_t`:
/// `void (*)(const void* msg, void* context)`, rclc's
/// `rclc_subscription_callback_with_context_t`. Cast `msg` to
/// `const fingerprint_corpus_msg_nested*` and read FIELDS; there is no CDR in a ported
/// callback body. `ctx` is passed straight through — it is NOT the context
/// given to `nros_executor_add_subscription_raw`, which belongs to the raw
/// registration.
///
/// If the sample cannot be decoded into `msg` — including a string or sequence
/// longer than the bound this type declares — the callback is NOT invoked, the
/// sample is dropped, and the spin reports a subscription error. It never sees a
/// truncated message.
///
/// A MACRO for the reason `fingerprint_corpus_msg_nested_subscribe` is one: it expands at
/// the CALL SITE, where <nros/executor.h> is already included, so this header
/// keeps its single include of <nros/types.h> and names nothing from the
/// executor ABI until the macro is actually used.
#define fingerprint_corpus_msg_nested_executor_add_subscription_sized(executor, subscription, msg, cb, ctx, \
                                                          invocation, rx_bytes) \
    nros_executor_add_subscription_typed_sized( \
        (executor), (subscription), (msg), fingerprint_corpus_msg_nested_deserialize_erased, (cb), (ctx), \
        (invocation), (uint32_t)(rx_bytes))

/* issue 0896 layer 5 -- this type has NO receive bound
   (nested type `fingerprint-corpus/Shapes` could not be resolved), so there is no number the six-argument form could
   pass, exactly as for `fingerprint_corpus_msg_nested_subscribe` above. POISONED so the
   diagnostic names the type and the member that costs it the bound. Either
   remove the cause -- see the reason block above -- or call
   `fingerprint_corpus_msg_nested_executor_add_subscription_sized` with a byte count you
   chose (0 = the image default). */
#define fingerprint_corpus_msg_nested_executor_add_subscription(executor, subscription, msg, cb, ctx, \
                                                    invocation) \
    NROS_UNRESOLVED__fingerprint_corpus_msg_nested__nested_type_fingerprint_corpus_Shapes

#ifdef __cplusplus
}
#endif

#endif // FINGERPRINT_CORPUS_MSG_NESTED_H