// emit:ok
// nros-c action type - C header for embedded systems
// Package: fingerprint-corpus
// Action: Probe
// Auto-generated by rosidl-codegen - do not edit

#ifndef FINGERPRINT_CORPUS_ACTION_PROBE_H
#define FINGERPRINT_CORPUS_ACTION_PROBE_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#include <nros/types.h>

#include <nros/nros_config_generated.h>

/* RFC-0090 — emitted by nano-ros codegen version 3. */
#define NROS_EMITTED_CODEGEN_VERSION 3

#ifndef NROS_CODEGEN_VERSION
#error "nros: the generated config header did not define NROS_CODEGEN_VERSION. This generated artifact cannot tell whether the runtime accepts it; rebuild the nano-ros runtime so its config header is regenerated."
#elif NROS_EMITTED_CODEGEN_VERSION < NROS_CODEGEN_VERSION_MIN \
   || NROS_EMITTED_CODEGEN_VERSION > NROS_CODEGEN_VERSION
#error "nros: this generated tree was emitted at a codegen version the runtime does not accept (see NROS_EMITTED_CODEGEN_VERSION above against NROS_CODEGEN_VERSION_MIN..NROS_CODEGEN_VERSION in nros_config_generated.h). Regenerate it against the runtime you are building: `nros sync` in a consumer workspace."
#endif

#ifdef __cplusplus
extern "C" {
#endif

// ============================================================================
// Goal
// ============================================================================

// Goal constants

/// Probe goal structure
typedef struct fingerprint_corpus_action_probe_goal {
    struct { uint32_t size; int64_t data[64]; } waypoints;
    char name[256];
} fingerprint_corpus_action_probe_goal;

/// Initialize a Probe goal to default values
void fingerprint_corpus_action_probe_goal_init(fingerprint_corpus_action_probe_goal* msg);
/// Release heap-backed (`mode = "heap"`) fields; no-op without them (issue 0345).
void fingerprint_corpus_action_probe_goal_fini(fingerprint_corpus_action_probe_goal* msg);


/// Serialize a Probe goal to CDR format
/// Returns 0 on success, -1 on error. On success, *serialized_size contains
/// bytes written (issue #228 — unified with the message convention).
int32_t fingerprint_corpus_action_probe_goal_serialize(const fingerprint_corpus_action_probe_goal* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size);

/// Deserialize a Probe goal from CDR format
/// Returns 0 on success, -1 on error
int32_t fingerprint_corpus_action_probe_goal_deserialize(fingerprint_corpus_action_probe_goal* msg, const uint8_t* buffer, size_t buffer_size);

// ============================================================================
// Result
// ============================================================================

// Result constants

/// Probe result structure
typedef struct fingerprint_corpus_action_probe_result {
    int64_t total;
    char report[256];
} fingerprint_corpus_action_probe_result;

/// Initialize a Probe result to default values
void fingerprint_corpus_action_probe_result_init(fingerprint_corpus_action_probe_result* msg);
/// Release heap-backed (`mode = "heap"`) fields; no-op without them (issue 0345).
void fingerprint_corpus_action_probe_result_fini(fingerprint_corpus_action_probe_result* msg);


/// Serialize a Probe result to CDR format
/// Returns 0 on success, -1 on error. On success, *serialized_size contains
/// bytes written (issue #228 — unified with the message convention).
int32_t fingerprint_corpus_action_probe_result_serialize(const fingerprint_corpus_action_probe_result* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size);

/// Deserialize a Probe result from CDR format
/// Returns 0 on success, -1 on error
int32_t fingerprint_corpus_action_probe_result_deserialize(fingerprint_corpus_action_probe_result* msg, const uint8_t* buffer, size_t buffer_size);

// ============================================================================
// Feedback
// ============================================================================

// Feedback constants

/// Probe feedback structure
typedef struct fingerprint_corpus_action_probe_feedback {
    int64_t done;
    char stage[256];
} fingerprint_corpus_action_probe_feedback;

/// Initialize a Probe feedback to default values
void fingerprint_corpus_action_probe_feedback_init(fingerprint_corpus_action_probe_feedback* msg);
/// Release heap-backed (`mode = "heap"`) fields; no-op without them (issue 0345).
void fingerprint_corpus_action_probe_feedback_fini(fingerprint_corpus_action_probe_feedback* msg);


/// Serialize a Probe feedback to CDR format
/// Returns 0 on success, -1 on error. On success, *serialized_size contains
/// bytes written (issue #228 — unified with the message convention).
int32_t fingerprint_corpus_action_probe_feedback_serialize(const fingerprint_corpus_action_probe_feedback* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size);

/// Deserialize a Probe feedback from CDR format
/// Returns 0 on success, -1 on error
int32_t fingerprint_corpus_action_probe_feedback_deserialize(fingerprint_corpus_action_probe_feedback* msg, const uint8_t* buffer, size_t buffer_size);

// ============================================================================
// Action Type Support
// ============================================================================

/// Get the ROS type name for Probe
static inline const char* fingerprint_corpus_action_probe_get_type_name(void) {
    return "fingerprint-corpus::action::dds_::Probe_";
}

/// Get the type hash for Probe
static inline const char* fingerprint_corpus_action_probe_get_type_hash(void) {
    return "h";
}

/// Get the nros_action_type_t for this action type
const struct nros_action_type_t* fingerprint_corpus_action_probe_get_type_support(void);

#ifdef __cplusplus
}
#endif

#endif // FINGERPRINT_CORPUS_ACTION_PROBE_H