//! Unsafe FFI bindings to zenoh-pico C library
//!
//! This crate provides raw FFI bindings generated by bindgen from the zenoh-pico
//! C headers. These bindings are `no_std` compatible and use the `cty` crate for
//! C type definitions.
//!
//! # Usage
//!
//! This crate is intended to be used by higher-level safe wrappers.
//! Direct usage requires `unsafe` blocks.
//!
//! # Linking
//!
//! For native builds (Linux, macOS, Windows), zenoh-pico is automatically
//! compiled and linked as a static library using CMake. No external
//! configuration is required.
//!
//! For embedded targets (Zephyr, FreeRTOS, etc.), zenoh-pico is typically
//! compiled and linked by the platform's build system. Set the appropriate
//! Kconfig options or CMake variables.
//!
//! # Safety
//!
//! All functions in this crate are unsafe FFI calls. Callers must ensure:
//! - Pointers are valid and properly aligned
//! - Lifetimes are respected (owned vs loaned types)
//! - Thread safety requirements are met

#![no_std]
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

#[cfg(feature = "std")]
extern crate std;

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(test)]
mod tests {
    // Tests require std feature since they use the generated layout tests
    #[cfg(feature = "std")]
    use super::*;

    #[test]
    #[cfg(feature = "std")]
    fn test_bindings_exist() {
        // Just verify that some key types exist
        let _: z_result_t = 0;
    }
}
