// Generated by `nros codegen entry --lang rust`
//   bringup = demo_bringup
//   launch  = /tmp/system.launch.xml
//   board   = native
//
// DO NOT EDIT — re-run `cargo build` to regenerate. The Rust
// `nros::main!()` proc-macro is the canonical compile-time
// emitter; this CLI-baked form mirrors its `OwnedSpin` branch.


fn __nros_entry_run() -> ::core::result::Result<
    (),
    ::nros::__macro_support::nros_platform::RuntimeError,
> {
    <::nros_board_linux::LinuxBoard as ::nros::__macro_support::nros_platform::BoardEntry>::run(
        |runtime: &mut ::nros::__macro_support::nros_platform::RuntimeCtx<'_>|
            -> ::core::result::Result<
                (),
                ::nros::__macro_support::nros_platform::RuntimeError,
            >
    {
            runtime.params = &[];
            runtime.remaps = &[];
            runtime.qos_overrides = &[];
            runtime.node_identity = ::core::option::Option::None;
            ::talker_pkg::register(runtime)?;
            ::core::result::Result::Ok(())
        },
    )
}


#[cfg(not(target_os = "none"))]
fn main() {
    if let ::core::result::Result::Err(e) = __nros_entry_run() {
        ::std::eprintln!("{}: {}", ::core::env!("CARGO_PKG_NAME"), e);
        ::std::process::exit(1);
    }
}

#[cfg(target_os = "none")]
#[unsafe(no_mangle)]
pub extern "C" fn main() -> i32 {
    match __nros_entry_run() {
        ::core::result::Result::Ok(()) => 0,
        ::core::result::Result::Err(_) => 1,
    }
}
