/**
 * zenoh-pico-shim Public C API
 *
 * AUTO-GENERATED by cbindgen - DO NOT EDIT MANUALLY
 *
 * This header defines the high-level C API for zenoh-pico that can be
 * called from Rust FFI. It provides session management, publishers, and
 * subscribers with static storage.
 *
 * Platform-specific behavior (threading vs polling) is handled by the
 * backend interface in zenoh_shim_platform.h
 */

#ifndef ZENOH_SHIM_H
#define ZENOH_SHIM_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Maximum number of concurrent publishers
 */
#define ZENOH_SHIM_MAX_PUBLISHERS 8

/**
 * Maximum number of concurrent subscribers
 */
#define ZENOH_SHIM_MAX_SUBSCRIBERS 8

/**
 * Success
 */
#define ZENOH_SHIM_OK 0

/**
 * Generic error
 */
#define ZENOH_SHIM_ERR_GENERIC -1

/**
 * Configuration error
 */
#define ZENOH_SHIM_ERR_CONFIG -2

/**
 * Session error
 */
#define ZENOH_SHIM_ERR_SESSION -3

/**
 * Task creation error
 */
#define ZENOH_SHIM_ERR_TASK -4

/**
 * Invalid key expression
 */
#define ZENOH_SHIM_ERR_KEYEXPR -5

/**
 * Resource limit reached
 */
#define ZENOH_SHIM_ERR_FULL -6

/**
 * Invalid handle
 */
#define ZENOH_SHIM_ERR_INVALID -7

/**
 * Publish error
 */
#define ZENOH_SHIM_ERR_PUBLISH -8

/**
 * Callback function type for receiving samples.
 *
 * # Parameters
 * * `data` - Pointer to received data buffer
 * * `len` - Length of data in bytes
 * * `ctx` - User-provided context pointer
 */
typedef void (*ShimCallback)(const uint8_t *data, uintptr_t len, void *ctx);

/**
 * Initialize zenoh configuration with client mode and connect locator.
 *
 * # Parameters
 * * `locator` - Connection string (e.g., "tcp/192.168.1.1:7447"), null-terminated.
 *   Can be NULL to use default.
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zenoh_shim_init(const char *_locator);

/**
 * Open zenoh session and start background tasks (if threaded backend).
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zenoh_shim_open(void);

/**
 * Check if session is currently open.
 *
 * # Returns
 * Non-zero if open, 0 if closed.
 */
int32_t zenoh_shim_is_open(void);

/**
 * Close the session and clean up all resources.
 */
void zenoh_shim_close(void);

/**
 * Declare a publisher for the given key expression.
 *
 * # Parameters
 * * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
 *
 * # Returns
 * Publisher handle (>= 0) on success, negative error code on failure.
 */
int32_t zenoh_shim_declare_publisher(const char *_keyexpr);

/**
 * Publish data using publisher handle.
 *
 * # Parameters
 * * `handle` - Publisher handle from zenoh_shim_declare_publisher()
 * * `data` - Pointer to data buffer
 * * `len` - Length of data in bytes
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zenoh_shim_publish(int32_t _handle, const uint8_t *_data, uintptr_t _len);

/**
 * Undeclare a publisher.
 *
 * # Parameters
 * * `handle` - Publisher handle
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zenoh_shim_undeclare_publisher(int32_t _handle);

/**
 * Declare a subscriber for the given key expression.
 *
 * # Parameters
 * * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
 * * `callback` - Callback function to invoke when samples arrive
 * * `ctx` - User context pointer passed to callback
 *
 * # Returns
 * Subscriber handle (>= 0) on success, negative error code on failure.
 */
int32_t zenoh_shim_declare_subscriber(const char *_keyexpr, ShimCallback _callback, void *_ctx);

/**
 * Undeclare a subscriber.
 *
 * # Parameters
 * * `handle` - Subscriber handle
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zenoh_shim_undeclare_subscriber(int32_t _handle);

/**
 * Poll for incoming data and process callbacks.
 *
 * For threaded backends (Zephyr, POSIX), this is a no-op as background
 * tasks handle polling automatically.
 *
 * For polling backends (smoltcp), this must be called regularly to
 * process network data and dispatch callbacks.
 *
 * # Parameters
 * * `timeout_ms` - Maximum time to wait for data (0 = non-blocking)
 *
 * # Returns
 * Number of events processed, or negative on error.
 */
int32_t zenoh_shim_poll(uint32_t _timeout_ms);

/**
 * Combined poll and keepalive operation.
 *
 * This is equivalent to calling zenoh_shim_poll() and performing any
 * necessary keepalive operations. For threaded backends, this is just
 * a brief poll. For polling backends, this handles both network I/O
 * and zenoh protocol maintenance.
 *
 * # Parameters
 * * `timeout_ms` - Maximum time to wait (0 = non-blocking)
 *
 * # Returns
 * Number of events processed, or negative on error.
 */
int32_t zenoh_shim_spin_once(uint32_t _timeout_ms);

/**
 * Check if the current backend uses polling.
 *
 * # Returns
 * true if polling required (smoltcp), false if threaded (Zephyr, POSIX).
 */
bool zenoh_shim_uses_polling(void);

#endif  /* ZENOH_SHIM_H */
