//! Parameter server implementation
//!
//! Provides a static storage parameter server for embedded systems.
//! Parameters are stored in a fixed-size array with compile-time capacity.

use crate::types::{
    MAX_PARAM_NAME_LEN, Parameter, ParameterDescriptor, ParameterType, ParameterValue,
    SetParameterResult,
};
use heapless::String;

// MAX_PARAMETERS is generated by build.rs and included via types.rs.
use crate::types::MAX_PARAMETERS;

/// Entry in the parameter storage.
///
/// phase-382 W2' — crate-private ON PURPOSE. The storage is caller-owned now,
/// but the SLOT layout is not part of the deal: consumers name
/// [`ParameterTable`] / [`ParameterStorage`], never this.
#[derive(Debug, Clone)]
pub(crate) struct ParameterEntry {
    /// The parameter (name + value)
    param: Parameter,
    /// Optional descriptor with constraints
    descriptor: Option<ParameterDescriptor>,
}

/// The slot table a [`ParameterServer`] borrows.
///
/// phase-382 W2' — the server's storage is CALLER-OWNED, and this newtype is
/// what makes that expressible without publishing the slot type. A slot is a
/// `ParameterEntry`, which stays PRIVATE (it is the store's internal slot
/// layout, not an API); a consumer that only needs to *name* the storage —
/// `nros-node`, which carves it out of the executor backing in W3' — names a
/// `ParameterTable` instead.
///
/// **The table's LENGTH is the server's capacity.** [`MAX_PARAMETERS`] is the
/// DEFAULT capacity (see [`ParameterStorage`]), not a bound the borrow
/// re-imposes: a caller who hands over a longer or shorter table gets exactly
/// that many slots, and every capacity question the server answers
/// ([`is_full`](ParameterServer::is_full), the declare path) reads it from
/// here.
pub struct ParameterTable<'s> {
    entries: &'s mut [Option<ParameterEntry>],
}

impl<'s> ParameterTable<'s> {
    /// Wrap a caller-owned slice of slots.
    pub(crate) fn new(entries: &'s mut [Option<ParameterEntry>]) -> Self {
        Self { entries }
    }

    /// Number of slots — the capacity of a server built on this table.
    pub fn capacity(&self) -> usize {
        self.entries.len()
    }

    /// Number of slots currently holding a parameter.
    pub fn occupied(&self) -> usize {
        self.entries.iter().filter(|slot| slot.is_some()).count()
    }
}

impl core::fmt::Debug for ParameterTable<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("ParameterTable")
            .field("capacity", &self.capacity())
            .finish_non_exhaustive()
    }
}

/// Backing storage a caller places, then lends to a [`ParameterServer`].
///
/// `N` defaults to [`MAX_PARAMETERS`], the build-time knob
/// (`NROS_MAX_PARAMETERS` / `CONFIG_NROS_MAX_PARAMETERS`). It is a DEFAULT,
/// not a cap — `ParameterStorage::<8>::new()` and `ParameterStorage::<256>`
/// are equally valid, and the server takes its capacity from whatever table it
/// is handed.
///
/// The intended shapes are a `static`, a caller-owned struct field, or (with
/// `alloc`) one allocation made once at start-up:
///
/// ```
/// use nros_params::{ParameterServer, ParameterStorage, ParameterValue};
///
/// let mut storage: ParameterStorage<8> = ParameterStorage::new();
/// let mut server = ParameterServer::new_in(storage.as_table());
/// assert!(server.declare("max_speed", ParameterValue::Double(1.0)));
/// ```
///
/// # Why this type exists at all — issue 0756
///
/// This is where the size lives, and it is enormous: `ParameterValue` is sized
/// by its largest variant
/// (`StringArray(Vec<String<MAX_STRING_VALUE_LEN>, MAX_ARRAY_LEN>)`), so every
/// slot costs ~8.5 KiB whatever it actually holds. Measured: **285,184 bytes**
/// at the default 32 slots, **2,281,472** at 256. (The eight extra bytes in
/// issue 0756's 285,192 were the `count` that stayed behind on
/// [`ParameterServer`], which is 24 bytes total now.)
///
/// Before phase-382 W2' that bulk was INSIDE `ParameterServer`, so
/// `Box::new(ParameterServer::new())` built a multi-hundred-KiB value on the
/// STACK before copying it into the allocation — Rust has no placement-new —
/// which silently overran a thread stack sized for anything smaller. On the
/// Zephyr lane an image built with 256 slots booted to
/// `dds_create_participant` and hung with no fault and no output, while 32 —
/// which fits the 512 KiB main stack the cyclonedds snippet asks for — ran
/// clean. The mitigation then was `ParameterServer::init_in_place`, a
/// placement initialiser that bounded the largest temporary at one
/// `Option<ParameterEntry>`.
///
/// W2' dissolves the *server* half of that: `ParameterServer` is now a table
/// borrow plus a count (tens of bytes), so nothing about constructing a server
/// depends on the knob. The bulk did not vanish, it MOVED here — and so did
/// the hazard, verbatim: `Box::new(ParameterStorage::new())` is the same
/// stack-first copy the issue was about. [`init_in_place`] is therefore kept,
/// on the type that is actually big, and any heap-placed storage must go
/// through it. A caller who places the storage as a `static` or lets W3' carve
/// it out of the executor backing never materialises it by value and does not
/// need it.
///
/// [`init_in_place`]: ParameterStorage::init_in_place
pub struct ParameterStorage<const N: usize = MAX_PARAMETERS> {
    entries: [Option<ParameterEntry>; N],
}

impl<const N: usize> ParameterStorage<N> {
    /// Create empty storage.
    ///
    /// `const`, so a `static NROS_PARAMS: ParameterStorage = ParameterStorage::new();`
    /// lands in `.bss` with no initialiser and no stack temporary.
    // No `Default`: it would spell this same construction as a by-value
    // expression, which is exactly the `Box::new(Default::default())` shape
    // issue 0756 is about (see the type docs). Callers name `new()` — or
    // `init_in_place` when the home is a heap allocation.
    #[allow(clippy::new_without_default)]
    #[allow(clippy::large_stack_arrays)] // Intentional: this IS the storage.
    pub const fn new() -> Self {
        Self {
            entries: [const { None }; N],
        }
    }

    /// Slots in this storage.
    pub const fn capacity(&self) -> usize {
        N
    }

    /// Lend the storage to a [`ParameterServer`].
    pub fn as_table(&mut self) -> ParameterTable<'_> {
        ParameterTable::new(&mut self.entries)
    }

    /// Initialise storage directly into `dst`, without ever materialising one
    /// by value.
    ///
    /// Issue 0756 — see this type's documentation for why that matters. The
    /// short version: this type is 285,184 bytes at the default 32 slots and
    /// 2,281,472 at 256, and Rust has no placement-new, so
    /// `Box::new(ParameterStorage::new())` builds all of it on the caller's
    /// stack first. Initialising through the allocation bounds the largest
    /// stack temporary at one `Option<ParameterEntry>`, so the
    /// `NROS_MAX_PARAMETERS` knob no longer decides whether boot survives.
    ///
    /// # Safety
    ///
    /// `dst` must be non-null, correctly aligned, and valid for writes of
    /// `size_of::<Self>()` bytes. The pointee may be uninitialised on entry;
    /// it is fully initialised on return.
    pub unsafe fn init_in_place(dst: *mut Self) {
        // addr_of_mut! throughout: `(*dst).entries` as a place expression
        // would require the pointee to already be initialised.
        // Safety: delegated to this function's own contract on `dst`.
        unsafe {
            let entries = core::ptr::addr_of_mut!((*dst).entries).cast::<Option<ParameterEntry>>();
            for i in 0..N {
                entries.add(i).write(None);
            }
        }
    }
}

/// Parameter server over caller-owned storage
///
/// Stores parameters in a [`ParameterTable`] the caller lends it; the table's
/// length is the capacity. [`ParameterStorage`] is the usual way to produce
/// one, defaulting to the build-time `MAX_PARAMETERS` slots.
///
/// # Example
///
/// ```
/// use nros_params::{ParameterServer, ParameterStorage, ParameterValue};
///
/// let mut storage = ParameterStorage::<8>::new();
/// let mut server = ParameterServer::new_in(storage.as_table());
///
/// // Declare a parameter with initial value
/// server.declare("max_speed", ParameterValue::Double(1.0));
///
/// // Get parameter value
/// if let Some(value) = server.get("max_speed") {
///     println!("max_speed = {:?}", value.as_double());
/// }
///
/// // Set parameter value
/// server.set("max_speed", ParameterValue::Double(2.0));
/// ```
pub struct ParameterServer<'s> {
    /// Borrowed parameter storage
    table: ParameterTable<'s>,
    /// Number of parameters currently stored
    count: usize,
    /// May a wire-facing set ([`apply`](Self::apply)) DECLARE a name it does
    /// not hold? Off by default, as upstream (`allow_undeclared_parameters`
    /// in rclcpp's `NodeOptions`, `allow_undeclared` in rclrs) — issue 1151.
    allow_undeclared: bool,
}

impl<'s> ParameterServer<'s> {
    /// Create a parameter server over `table`.
    ///
    /// The server ADOPTS whatever the table already holds: `count` is
    /// recovered from the occupied slots rather than assumed zero. That is
    /// what makes a table safe to hand to a second server after the first is
    /// dropped (and what lets storage arrive pre-seeded), where assuming empty
    /// would desynchronise the count from the slots — `is_full` wrong in one
    /// direction, `remove` underflowing in the other. Fresh
    /// [`ParameterStorage`] is all-`None`, so the usual path costs one scan
    /// and starts at zero.
    pub fn new_in(table: ParameterTable<'s>) -> Self {
        let count = table.occupied();
        Self {
            table,
            count,
            allow_undeclared: false,
        }
    }

    /// Let a wire-facing set ([`apply`](Self::apply)) create a parameter that
    /// was never declared. Default `false`: a remote set on a misspelled
    /// name used to report success and create the misspelling (issue 1151);
    /// now it is refused with a reason unless this is switched on, as
    /// upstream.
    pub fn set_allow_undeclared(&mut self, allow: bool) {
        self.allow_undeclared = allow;
    }

    /// Whether [`apply`](Self::apply) may declare an unknown name.
    pub fn allows_undeclared(&self) -> bool {
        self.allow_undeclared
    }

    /// Get the number of parameters stored
    pub fn len(&self) -> usize {
        self.count
    }

    /// Check if the server has no parameters
    pub fn is_empty(&self) -> bool {
        self.count == 0
    }

    /// Capacity of the borrowed table.
    ///
    /// phase-382 W2' — this is the TABLE's length, not `MAX_PARAMETERS`. The
    /// build-time knob only picks the default size of a [`ParameterStorage`].
    pub fn capacity(&self) -> usize {
        self.table.capacity()
    }

    /// Check if the server is at capacity
    pub fn is_full(&self) -> bool {
        self.count >= self.table.capacity()
    }

    /// Find the index of a parameter by name
    fn find_index(&self, name: &str) -> Option<usize> {
        self.table.entries.iter().position(|entry| {
            entry
                .as_ref()
                .map(|e| e.param.name.as_str() == name)
                .unwrap_or(false)
        })
    }

    /// Find an empty slot
    fn find_empty_slot(&self) -> Option<usize> {
        self.table.entries.iter().position(|entry| entry.is_none())
    }

    /// Declare a new parameter with a value
    ///
    /// If the parameter already exists, this does nothing and returns false.
    /// Returns true if the parameter was declared successfully.
    ///
    /// phase-428 W6 remainder: this is the method `Executor::declare_parameter`
    /// delegates to, so marking only the wrapper would leave the class half
    /// fixed one crate down.
    #[must_use]
    pub fn declare(&mut self, name: &str, value: ParameterValue) -> bool {
        self.declare_with_descriptor(name, value, None)
    }

    /// Declare a new parameter with value and descriptor
    ///
    /// The descriptor provides metadata like description, constraints, and read-only flag.
    ///
    /// phase-428 W6 remainder: see [`Self::declare`]. Every `false` arm below
    /// is a REFUSAL (name taken, table full, value rejected), never a question.
    #[must_use]
    pub fn declare_with_descriptor(
        &mut self,
        name: &str,
        value: ParameterValue,
        descriptor: Option<ParameterDescriptor>,
    ) -> bool {
        // Check if already exists
        if self.find_index(name).is_some() {
            return false;
        }

        // Issue 1150 — an ill-formed range, or a default the range rejects,
        // is refused at declaration, as upstream. Same predicate as every set.
        if !Self::declaration_is_consistent(descriptor.as_ref(), &value) {
            return false;
        }

        // Find an empty slot
        let slot = match self.find_empty_slot() {
            Some(idx) => idx,
            None => return false,
        };

        // Create the parameter
        let param = match Parameter::new(name, value) {
            Some(p) => p,
            None => return false,
        };

        self.table.entries[slot] = Some(ParameterEntry { param, descriptor });
        self.count += 1;
        true
    }

    /// The declare-time half of issue 1150: the range must be well-formed
    /// and the initial value must satisfy it (rclrs `InvalidRange` /
    /// `InitialValueOutOfRange`). ONE spelling for both declare paths.
    fn declaration_is_consistent(
        descriptor: Option<&ParameterDescriptor>,
        value: &ParameterValue,
    ) -> bool {
        match descriptor {
            Some(desc) => desc.range.is_valid() && desc.validate_range(value),
            None => true,
        }
    }

    /// Would `set(name, value)` succeed on an EXISTING entry? Read-only,
    /// then type, then range — the one ordering every set path uses.
    fn check_set_existing(entry: &ParameterEntry, value: &ParameterValue) -> SetParameterResult {
        if let Some(ref desc) = entry.descriptor {
            if desc.read_only {
                return SetParameterResult::ReadOnly;
            }
            if !desc.dynamic_typing && desc.param_type != value.param_type() {
                return SetParameterResult::TypeMismatch;
            }
            if !desc.validate_range(value) {
                return SetParameterResult::OutOfRange;
            }
        }
        SetParameterResult::Success
    }

    /// Dry-run of [`apply`](Self::apply): the verdict a wire-facing set would
    /// get, without changing anything. `SetParametersAtomically` runs this
    /// over the whole batch before applying any of it.
    pub fn check_apply(&self, name: &str, value: &ParameterValue) -> SetParameterResult {
        match self
            .find_index(name)
            .and_then(|idx| self.table.entries[idx].as_ref())
        {
            Some(entry) => Self::check_set_existing(entry, value),
            None if !self.allow_undeclared => SetParameterResult::Undeclared,
            None if self.is_full() => SetParameterResult::StorageFull,
            None if name.len() > MAX_PARAM_NAME_LEN => SetParameterResult::StorageFull,
            None => SetParameterResult::Success,
        }
    }

    /// THE wire-facing set — what one element of `SetParameters` /
    /// `SetParametersAtomically` does (issue 1151).
    ///
    /// An existing parameter is set through [`set`](Self::set). An unknown
    /// name is [`Undeclared`](SetParameterResult::Undeclared) unless
    /// [`set_allow_undeclared`](Self::set_allow_undeclared) was switched on,
    /// in which case it is declared (or `StorageFull`). Every service handler
    /// goes through here so the by-value oracle, the streaming path and the
    /// atomic pre-check cannot disagree about what "undeclared" means.
    pub fn apply(&mut self, name: &str, value: ParameterValue) -> SetParameterResult {
        let verdict = self.check_apply(name, &value);
        if !verdict.is_success() {
            return verdict;
        }
        if self.find_index(name).is_some() {
            self.set(name, value)
        } else if self.declare(name, value) {
            SetParameterResult::Success
        } else {
            SetParameterResult::StorageFull
        }
    }

    /// Get a parameter value by name
    pub fn get(&self, name: &str) -> Option<&ParameterValue> {
        self.find_index(name)
            .and_then(|idx| self.table.entries[idx].as_ref())
            .map(|entry| &entry.param.value)
    }

    /// Get a parameter by name
    pub fn get_parameter(&self, name: &str) -> Option<&Parameter> {
        self.find_index(name)
            .and_then(|idx| self.table.entries[idx].as_ref())
            .map(|entry| &entry.param)
    }

    /// Get a parameter descriptor by name
    pub fn get_descriptor(&self, name: &str) -> Option<&ParameterDescriptor> {
        self.find_index(name)
            .and_then(|idx| self.table.entries[idx].as_ref())
            .and_then(|entry| entry.descriptor.as_ref())
    }

    /// Set a parameter value
    ///
    /// Returns the result of the set operation.
    pub fn set(&mut self, name: &str, value: ParameterValue) -> SetParameterResult {
        let idx = match self.find_index(name) {
            Some(idx) => idx,
            None => return SetParameterResult::NotFound,
        };

        let entry = match self.table.entries[idx].as_mut() {
            Some(e) => e,
            None => return SetParameterResult::NotFound,
        };

        // Read-only, type, range (min/max/step) — one predicate, shared with
        // the atomic pre-check.
        let verdict = Self::check_set_existing(entry, &value);
        if !verdict.is_success() {
            return verdict;
        }

        entry.param.value = value;
        SetParameterResult::Success
    }

    /// Unset an optional parameter (set to NotSet)
    ///
    /// This bypasses the type check to allow optional parameters to be unset.
    /// Returns an error if the parameter is read-only.
    pub fn unset(&mut self, name: &str) -> SetParameterResult {
        let idx = match self.find_index(name) {
            Some(idx) => idx,
            None => return SetParameterResult::NotFound,
        };

        let entry = match self.table.entries[idx].as_mut() {
            Some(e) => e,
            None => return SetParameterResult::NotFound,
        };

        // Check if read-only
        if let Some(ref desc) = entry.descriptor
            && desc.read_only
        {
            return SetParameterResult::ReadOnly;
        }

        entry.param.value = ParameterValue::NotSet;
        SetParameterResult::Success
    }

    /// Set or declare a parameter — an EXPLICIT auto-declare for in-image
    /// callers.
    ///
    /// If the parameter exists, sets its value. Otherwise, declares it. This
    /// ignores `allow_undeclared` on purpose: the flag governs what a REMOTE
    /// set may do; a Rust caller naming this method has opted in by naming
    /// it. Nothing on the wire path reaches here (issue 1151).
    pub fn set_or_declare(&mut self, name: &str, value: ParameterValue) -> SetParameterResult {
        if self.find_index(name).is_some() {
            self.set(name, value)
        } else if self.declare(name, value) {
            SetParameterResult::Success
        } else {
            SetParameterResult::StorageFull
        }
    }

    /// Check if a parameter exists
    pub fn has(&self, name: &str) -> bool {
        self.find_index(name).is_some()
    }

    /// Remove a parameter
    ///
    /// Returns true if the parameter was removed.
    pub fn remove(&mut self, name: &str) -> bool {
        if let Some(idx) = self.find_index(name) {
            self.table.entries[idx] = None;
            self.count -= 1;
            true
        } else {
            false
        }
    }

    /// Get the type of a parameter
    pub fn get_type(&self, name: &str) -> Option<ParameterType> {
        self.get(name).map(|v| v.param_type())
    }

    /// Iterate over all parameters
    pub fn iter(&self) -> impl Iterator<Item = &Parameter> {
        self.table
            .entries
            .iter()
            .filter_map(|entry| entry.as_ref().map(|e| &e.param))
    }

    /// List all parameter names
    pub fn list_names(&self) -> impl Iterator<Item = &str> {
        self.iter().map(|p| p.name.as_str())
    }

    /// List parameter names with a given prefix
    pub fn list_with_prefix<'a>(&'a self, prefix: &'a str) -> impl Iterator<Item = &'a str> {
        self.list_names()
            .filter(move |name| name.starts_with(prefix))
    }

    /// Get a bool parameter value
    pub fn get_bool(&self, name: &str) -> Option<bool> {
        self.get(name).and_then(|v| v.as_bool())
    }

    /// Get an integer parameter value
    pub fn get_integer(&self, name: &str) -> Option<i64> {
        self.get(name).and_then(|v| v.as_integer())
    }

    /// Get a double parameter value
    pub fn get_double(&self, name: &str) -> Option<f64> {
        self.get(name).and_then(|v| v.as_double())
    }

    /// Get a string parameter value
    pub fn get_string(&self, name: &str) -> Option<&str> {
        self.get(name).and_then(|v| v.as_string())
    }

    /// Set a bool parameter value
    pub fn set_bool(&mut self, name: &str, value: bool) -> SetParameterResult {
        self.set(name, ParameterValue::Bool(value))
    }

    /// Set an integer parameter value
    pub fn set_integer(&mut self, name: &str, value: i64) -> SetParameterResult {
        self.set(name, ParameterValue::Integer(value))
    }

    /// Set a double parameter value
    pub fn set_double(&mut self, name: &str, value: f64) -> SetParameterResult {
        self.set(name, ParameterValue::Double(value))
    }

    /// Set a string parameter value
    pub fn set_string(&mut self, name: &str, value: &str) -> SetParameterResult {
        match ParameterValue::from_string(value) {
            Some(v) => self.set(name, v),
            None => SetParameterResult::StorageFull, // String too long
        }
    }

    /// Declare a parameter with a descriptor and optional initial value.
    ///
    /// This is a more comprehensive declaration method used by the typed parameter API.
    ///
    /// # Arguments
    /// - `descriptor`: The metadata for the parameter.
    /// - `initial_value`: An optional initial value for the parameter. If `None`,
    ///   the parameter will be initialized to `ParameterValue::NotSet`.
    pub fn declare_parameter(
        &mut self,
        descriptor: ParameterDescriptor,
        initial_value: Option<&ParameterValue>,
    ) -> Result<(), SetParameterResult> {
        let name = descriptor.name.as_str();

        // Check if already exists
        if self.find_index(name).is_some() {
            return Err(SetParameterResult::TypeMismatch); // Indicates already declared
        }

        let param_value = initial_value.cloned().unwrap_or_default();

        // Issue 1150 — same declare-time check as `declare_with_descriptor`.
        if !Self::declaration_is_consistent(Some(&descriptor), &param_value) {
            return Err(SetParameterResult::InvalidRange);
        }

        // Find an empty slot
        let slot = match self.find_empty_slot() {
            Some(idx) => idx,
            None => return Err(SetParameterResult::StorageFull),
        };

        let param = Parameter::new(name, param_value).ok_or(SetParameterResult::StorageFull)?; // name too long

        self.table.entries[slot] = Some(ParameterEntry {
            param,
            descriptor: Some(descriptor),
        });
        self.count += 1;
        Ok(())
    }

    /// Get the current value of a parameter.
    ///
    /// Returns `Some(ParameterValue)` if the parameter exists, `None` otherwise.
    /// The `ParameterValue` is cloned to avoid lifetime issues with `&mut self`.
    pub fn get_parameter_value(&self, name: &str) -> Option<ParameterValue> {
        self.get(name).cloned()
    }

    /// Set the value of a parameter.
    ///
    /// Returns `SetParameterResult::Success` on success, or an error if the parameter
    /// is read-only, type mismatches, or is out of range.
    pub fn set_parameter_value(&mut self, name: &str, value: ParameterValue) -> SetParameterResult {
        self.set(name, value)
    }
}

/// Builder for declaring parameters with a fluent API
pub struct LegacyParameterBuilder<'a, 's> {
    server: &'a mut ParameterServer<'s>,
    name: String<MAX_PARAM_NAME_LEN>,
    value: ParameterValue,
    descriptor: Option<ParameterDescriptor>,
}

impl<'a, 's> LegacyParameterBuilder<'a, 's> {
    /// Create a new parameter builder
    pub fn new(
        server: &'a mut ParameterServer<'s>,
        name: &str,
        value: ParameterValue,
    ) -> Option<Self> {
        let mut n = String::new();
        n.push_str(name).ok()?;
        Some(Self {
            server,
            name: n,
            value,
            descriptor: None,
        })
    }

    /// Set the parameter description
    pub fn description(mut self, desc: &str) -> Self {
        let param_type = self.value.param_type();
        if self.descriptor.is_none() {
            self.descriptor = ParameterDescriptor::new(self.name.as_str(), param_type);
        }
        if let Some(ref mut d) = self.descriptor {
            d.description.clear();
            let _ = d.description.push_str(desc);
        }
        self
    }

    /// Set the parameter as read-only
    pub fn read_only(mut self) -> Self {
        let param_type = self.value.param_type();
        if self.descriptor.is_none() {
            self.descriptor = ParameterDescriptor::new(self.name.as_str(), param_type);
        }
        if let Some(ref mut d) = self.descriptor {
            d.read_only = true;
        }
        self
    }

    /// Set integer range constraints
    pub fn integer_range(mut self, min: i64, max: i64, step: i64) -> Self {
        let param_type = self.value.param_type();
        if self.descriptor.is_none() {
            self.descriptor = ParameterDescriptor::new(self.name.as_str(), param_type);
        }
        if let Some(ref mut d) = self.descriptor {
            d.range = crate::types::ParameterRange::Integer(crate::types::IntegerRange::new(
                min, max, step,
            ));
        }
        self
    }

    /// Set float range constraints
    pub fn float_range(mut self, min: f64, max: f64, step: f64) -> Self {
        let param_type = self.value.param_type();
        if self.descriptor.is_none() {
            self.descriptor = ParameterDescriptor::new(self.name.as_str(), param_type);
        }
        if let Some(ref mut d) = self.descriptor {
            d.range = crate::types::ParameterRange::FloatingPoint(
                crate::types::FloatingPointRange::new(min, max, step),
            );
        }
        self
    }

    /// Declare the parameter
    ///
    /// phase-428 W6 remainder: the terminal of a builder chain, so a dropped
    /// answer is a parameter that was configured in full and then not declared.
    #[must_use]
    pub fn declare(self) -> bool {
        self.server
            .declare_with_descriptor(self.name.as_str(), self.value, self.descriptor)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{ParameterDescriptor, ParameterType};

    // ── issue 1150: step reaches `set`, and declare validates its range ──

    #[test]
    fn set_rejects_a_value_off_the_integer_step() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        let desc = ParameterDescriptor::new("rate", ParameterType::Integer)
            .unwrap()
            .with_integer_range(0, 100, 10);
        assert!(server.declare_with_descriptor("rate", ParameterValue::Integer(20), Some(desc)));

        assert_eq!(
            server.set("rate", ParameterValue::Integer(30)),
            SetParameterResult::Success
        );
        // In range by min/max, off the lattice: the old `contains` said yes.
        assert_eq!(
            server.set("rate", ParameterValue::Integer(35)),
            SetParameterResult::OutOfRange
        );
        assert_eq!(server.get_integer("rate"), Some(30));
    }

    #[test]
    fn set_rejects_a_value_off_the_float_step() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        let desc = ParameterDescriptor::new("gain", ParameterType::Double)
            .unwrap()
            .with_float_range(0.0, 1.0, 0.25);
        assert!(server.declare_with_descriptor("gain", ParameterValue::Double(0.5), Some(desc)));

        assert_eq!(server.set_double("gain", 0.75), SetParameterResult::Success);
        assert_eq!(
            server.set_double("gain", 0.6),
            SetParameterResult::OutOfRange
        );
        assert_eq!(server.get_double("gain"), Some(0.75));
    }

    #[test]
    fn declare_refuses_an_ill_formed_range() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        let desc = ParameterDescriptor::new("bad", ParameterType::Integer)
            .unwrap()
            .with_integer_range(0, 100, -1);
        assert!(!server.declare_with_descriptor(
            "bad",
            ParameterValue::Integer(0),
            Some(desc.clone())
        ));
        assert!(!server.has("bad"));
        assert_eq!(
            server.declare_parameter(desc, Some(&ParameterValue::Integer(0))),
            Err(SetParameterResult::InvalidRange)
        );
        assert!(!server.has("bad"));
    }

    #[test]
    fn declare_refuses_a_default_its_own_range_rejects() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        let desc = ParameterDescriptor::new("odd", ParameterType::Integer)
            .unwrap()
            .with_integer_range(0, 100, 2);
        assert!(!server.declare_with_descriptor(
            "odd",
            ParameterValue::Integer(3),
            Some(desc.clone())
        ));
        assert!(server.declare_with_descriptor("odd", ParameterValue::Integer(4), Some(desc)));
    }

    // ── issue 1151: a wire-facing set on an undeclared name is refused ──

    #[test]
    fn apply_rejects_an_undeclared_name_by_default() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert!(server.declare("max_speed", ParameterValue::Double(1.0)));
        assert!(!server.allows_undeclared());

        // The typo from the issue: reported success and created a parameter
        // nobody reads.
        assert_eq!(
            server.check_apply("max_speeed", &ParameterValue::Double(5.0)),
            SetParameterResult::Undeclared
        );
        assert_eq!(
            server.apply("max_speeed", ParameterValue::Double(5.0)),
            SetParameterResult::Undeclared
        );
        assert!(!server.has("max_speeed"));
        assert_eq!(server.len(), 1);
        assert_eq!(server.get_double("max_speed"), Some(1.0));

        // A declared name still sets.
        assert_eq!(
            server.apply("max_speed", ParameterValue::Double(5.0)),
            SetParameterResult::Success
        );
        assert_eq!(server.get_double("max_speed"), Some(5.0));
    }

    #[test]
    fn apply_declares_an_unknown_name_under_allow_undeclared() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        server.set_allow_undeclared(true);
        assert!(server.allows_undeclared());

        assert_eq!(
            server.check_apply("fresh", &ParameterValue::Integer(7)),
            SetParameterResult::Success
        );
        assert_eq!(
            server.apply("fresh", ParameterValue::Integer(7)),
            SetParameterResult::Success
        );
        assert_eq!(server.get_integer("fresh"), Some(7));
    }

    #[test]
    fn apply_under_allow_undeclared_still_reports_a_full_store() {
        let mut storage: ParameterStorage<1> = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        server.set_allow_undeclared(true);
        assert!(server.declare("only", ParameterValue::Bool(true)));
        assert_eq!(
            server.check_apply("second", &ParameterValue::Bool(true)),
            SetParameterResult::StorageFull
        );
        assert_eq!(
            server.apply("second", ParameterValue::Bool(true)),
            SetParameterResult::StorageFull
        );
    }

    #[test]
    fn apply_enforces_the_existing_entry_rules_through_the_same_predicate() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        let desc = ParameterDescriptor::new("rate", ParameterType::Integer)
            .unwrap()
            .with_integer_range(0, 100, 10);
        assert!(server.declare_with_descriptor("rate", ParameterValue::Integer(20), Some(desc)));
        assert_eq!(
            server.check_apply("rate", &ParameterValue::Integer(35)),
            SetParameterResult::OutOfRange
        );
        assert_eq!(
            server.apply("rate", ParameterValue::Integer(35)),
            SetParameterResult::OutOfRange
        );
        assert_eq!(
            server.apply("rate", ParameterValue::Double(30.0)),
            SetParameterResult::TypeMismatch
        );
        assert_eq!(server.get_integer("rate"), Some(20));
    }

    #[test]
    fn test_new_server() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let server = ParameterServer::new_in(storage.as_table());
        assert_eq!(server.len(), 0);
        assert!(server.is_empty());
    }

    #[test]
    #[allow(clippy::approx_constant)]
    fn test_declare_and_get() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());

        assert!(server.declare("my_bool", ParameterValue::Bool(true)));
        assert!(server.declare("my_int", ParameterValue::Integer(42)));
        assert!(server.declare("my_double", ParameterValue::Double(3.14)));

        assert_eq!(server.len(), 3);
        assert!(!server.is_empty());

        assert_eq!(server.get_bool("my_bool"), Some(true));
        assert_eq!(server.get_integer("my_int"), Some(42));
        assert_eq!(server.get_double("my_double"), Some(3.14));
    }

    #[test]
    fn test_unset_clears_the_value_and_reports_success() {
        // phase-359 W10 / issue 0080 — what survives of
        // `test_dirty_tracks_value_changes_not_declarations`. That test existed
        // for the persistence flush's dirty flag, which is deleted with the
        // seam; but it carried the crate's ONLY coverage of `unset`, so the
        // assertion moves here rather than going out with the flag.
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert!(server.declare("count", ParameterValue::Integer(0)));
        assert_eq!(server.set_integer("count", 10), SetParameterResult::Success);
        assert_eq!(server.get_integer("count"), Some(10));

        assert_eq!(server.unset("count"), SetParameterResult::Success);
        assert_eq!(server.get_integer("count"), None);
    }

    #[test]
    fn test_set_parameter() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert!(server.declare("count", ParameterValue::Integer(0)));

        assert_eq!(server.set_integer("count", 10), SetParameterResult::Success);
        assert_eq!(server.get_integer("count"), Some(10));
    }

    #[test]
    fn test_set_nonexistent() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert_eq!(
            server.set("nonexistent", ParameterValue::Integer(1)),
            SetParameterResult::NotFound
        );
    }

    #[test]
    fn test_read_only_parameter() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());

        let desc = ParameterDescriptor::new("version", ParameterType::String)
            .unwrap()
            .with_read_only(true);

        assert!(server.declare_with_descriptor(
            "version",
            ParameterValue::from_string("1.0.0").unwrap(),
            Some(desc),
        ));

        assert_eq!(
            server.set_string("version", "2.0.0"),
            SetParameterResult::ReadOnly
        );
        assert_eq!(server.get_string("version"), Some("1.0.0"));
    }

    #[test]
    fn test_range_constraints() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());

        let desc = ParameterDescriptor::new("speed", ParameterType::Double)
            .unwrap()
            .with_float_range(0.0, 10.0, 0.0);

        assert!(server.declare_with_descriptor("speed", ParameterValue::Double(5.0), Some(desc)));

        // Valid value
        assert_eq!(server.set_double("speed", 8.0), SetParameterResult::Success);

        // Out of range
        assert_eq!(
            server.set_double("speed", 15.0),
            SetParameterResult::OutOfRange
        );
        assert_eq!(server.get_double("speed"), Some(8.0)); // Unchanged
    }

    #[test]
    fn test_remove_parameter() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert!(server.declare("temp", ParameterValue::Double(25.0)));

        assert!(server.has("temp"));
        assert!(server.remove("temp"));
        assert!(!server.has("temp"));
        assert!(!server.remove("temp")); // Already removed
    }

    #[test]
    fn test_list_parameters() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert!(server.declare("robot.speed", ParameterValue::Double(1.0)));
        assert!(server.declare("robot.name", ParameterValue::from_string("bot1").unwrap()));
        assert!(server.declare("sensor.range", ParameterValue::Double(10.0)));

        let robot_params: heapless::Vec<&str, 8> = server.list_with_prefix("robot.").collect();
        assert_eq!(robot_params.len(), 2);
    }

    #[test]
    fn test_set_or_declare() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());

        // First call declares
        assert_eq!(
            server.set_or_declare("new_param", ParameterValue::Integer(1)),
            SetParameterResult::Success
        );
        assert_eq!(server.get_integer("new_param"), Some(1));

        // Second call sets
        assert_eq!(
            server.set_or_declare("new_param", ParameterValue::Integer(2)),
            SetParameterResult::Success
        );
        assert_eq!(server.get_integer("new_param"), Some(2));
    }

    #[test]
    fn test_duplicate_declare() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert!(server.declare("param", ParameterValue::Integer(1)));
        assert!(!server.declare("param", ParameterValue::Integer(2))); // Already exists
        assert_eq!(server.get_integer("param"), Some(1)); // Unchanged
    }
}

// =============================================================================
// Ghost model validation
// =============================================================================

#[cfg(test)]
mod ghost_checks {
    use super::*;
    use nros_ghost_types::ParamServerGhost;

    /// Structural check: construct ParamServerGhost from ParameterServer private fields.
    /// If a field is renamed or retyped, this fails to compile.
    fn ghost_from_server(s: &ParameterServer<'_>) -> ParamServerGhost {
        ParamServerGhost {
            count: s.count,
            // phase-382 W2' — capacity is the borrowed TABLE's length. It used
            // to read `MAX_PARAMETERS`, which was the same number only because
            // the storage was the knob-sized array inside the server.
            max: s.table.capacity(),
        }
    }

    #[test]
    fn ghost_new_count() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let capacity = storage.capacity();
        let server = ParameterServer::new_in(storage.as_table());
        let ghost = ghost_from_server(&server);
        assert_eq!(ghost.count, 0);
        // phase-382 W2' — the ghost's `max` is the TABLE's length, and the
        // default-parameter `ParameterStorage` is `MAX_PARAMETERS` long. This
        // used to be a literal `32`, which held only while the knob was at its
        // default.
        assert_eq!(ghost.max, capacity);
        assert_eq!(ghost.max, MAX_PARAMETERS);
    }

    /// phase-382 W2' — capacity follows the TABLE, not `MAX_PARAMETERS`: a
    /// server built on a short table is full at that table's length.
    #[test]
    fn ghost_max_follows_a_shorter_table() {
        let mut storage = ParameterStorage::<2>::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert_eq!(ghost_from_server(&server).max, 2);
        assert!(server.declare("a", ParameterValue::Integer(1)));
        assert!(server.declare("b", ParameterValue::Integer(2)));
        assert!(server.is_full());
        assert!(!server.declare("c", ParameterValue::Integer(3)));
        let ghost = ghost_from_server(&server);
        assert!(ghost.count <= ghost.max);
    }

    /// phase-382 W2' — `new_in` ADOPTS the table it is handed, so a second
    /// server over the same storage sees the parameters the first declared
    /// and keeps its count in step with the slots.
    #[test]
    fn ghost_count_recovers_from_a_reused_table() {
        let mut storage = ParameterStorage::<4>::new();
        {
            let mut first = ParameterServer::new_in(storage.as_table());
            assert!(first.declare("kept", ParameterValue::Integer(7)));
        }
        let second = ParameterServer::new_in(storage.as_table());
        assert_eq!(ghost_from_server(&second).count, 1);
        assert_eq!(second.get_integer("kept"), Some(7));
    }

    #[test]
    fn ghost_declare_increments() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        let before = ghost_from_server(&server).count;
        assert!(server.declare("test", ParameterValue::Integer(1)));
        let after = ghost_from_server(&server).count;
        assert_eq!(after, before + 1);
    }

    #[test]
    fn ghost_remove_decrements() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert!(server.declare("test", ParameterValue::Integer(1)));
        let before = ghost_from_server(&server).count;
        assert!(server.remove("test"));
        let after = ghost_from_server(&server).count;
        assert_eq!(after, before - 1);
    }

    #[test]
    fn ghost_count_bounded() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        for i in 0..MAX_PARAMETERS {
            let mut name = heapless::String::<64>::new();
            let _ = core::fmt::write(&mut name, format_args!("p{}", i));
            assert!(server.declare(name.as_str(), ParameterValue::Integer(i as i64)));
        }
        let ghost = ghost_from_server(&server);
        assert!(ghost.count <= ghost.max);
        assert_eq!(ghost.count, MAX_PARAMETERS);
        // Next declare should fail — count stays bounded
        assert!(!server.declare("overflow", ParameterValue::Integer(0)));
        let ghost2 = ghost_from_server(&server);
        assert!(ghost2.count <= ghost2.max);
    }
}

// =============================================================================
// Kani bounded model checking proofs
// =============================================================================

#[cfg(kani)]
mod verification {
    use super::*;

    // phase-382 W2' — each proof used to build the whole store on the proof
    // stack (`ParameterServer::new()`); it now places a `ParameterStorage` and
    // lends it, which is the only shape a caller-owned store has. Kani still
    // sees the same `MAX_PARAMETERS` slots, so the bounds are unchanged.

    #[kani::proof]
    fn server_new_is_empty() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let server = ParameterServer::new_in(storage.as_table());
        assert!(server.is_empty());
        assert_eq!(server.len(), 0);
        assert!(!server.is_full());
    }

    #[kani::proof]
    fn server_declare_get_roundtrip_integer() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        let val: i64 = kani::any();
        assert!(server.declare("test", ParameterValue::Integer(val)));
        assert_eq!(server.get_integer("test"), Some(val));
        assert!(server.has("test"));
        assert_eq!(server.len(), 1);
    }

    #[kani::proof]
    fn server_declare_get_roundtrip_bool() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        let val: bool = kani::any();
        assert!(server.declare("test", ParameterValue::Bool(val)));
        assert_eq!(server.get_bool("test"), Some(val));
    }

    #[kani::proof]
    fn server_set_requires_declare() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        let val: i64 = kani::any();
        // Set without declare should fail
        let result = server.set("test", ParameterValue::Integer(val));
        assert_eq!(result, SetParameterResult::NotFound);
    }

    #[kani::proof]
    fn server_duplicate_declare_fails() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert!(server.declare("test", ParameterValue::Integer(1)));
        assert!(!server.declare("test", ParameterValue::Integer(2)));
        // Original value preserved
        assert_eq!(server.get_integer("test"), Some(1));
    }

    #[kani::proof]
    fn server_remove_clears() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let mut server = ParameterServer::new_in(storage.as_table());
        assert!(server.declare("test", ParameterValue::Integer(42)));
        assert!(server.has("test"));
        assert!(server.remove("test"));
        assert!(!server.has("test"));
        assert_eq!(server.len(), 0);
    }

    #[kani::proof]
    fn server_get_nonexistent_returns_none() {
        let mut storage: ParameterStorage = ParameterStorage::new();
        let server = ParameterServer::new_in(storage.as_table());
        assert!(server.get("nonexistent").is_none());
        assert!(server.get_bool("nonexistent").is_none());
        assert!(server.get_integer("nonexistent").is_none());
        assert!(server.get_double("nonexistent").is_none());
        assert!(server.get_string("nonexistent").is_none());
    }
}
