#pragma once

// Generated by nano_ros_generate_cpp.py - DO NOT EDIT

#include <nano_ros/cdr.hpp>
#include <cstdint>

namespace builtin_interfaces::msg {

struct Duration {

    int32_t sec{0};
    uint32_t nanosec{0};

    /// Serialize to CDR format
    void serialize(nano_ros::CdrWriter& writer) const {
        writer.write_i32(sec);
        writer.write_u32(nanosec);
    }

    /// Deserialize from CDR format
    void deserialize(nano_ros::CdrReader& reader) {
        sec = reader.read_i32();
        nanosec = reader.read_u32();
    }

    /// Get the ROS type name
    static constexpr const char* type_name() {
        return "builtin_interfaces/msg/Duration";
    }
};

}  // namespace builtin_interfaces::msg
