//! Issue 1009 — keep the DDS interop bus on loopback, for BOTH sides of a pair.
//!
//! # Why
//!
//! Our DDS interop tests discover on whatever multicast the host can reach, so
//! any DDS participant on the LAN is a peer: a colleague's laptop, a robot, a CI
//! runner. Issue 0741 spent fifteen sections and four wrong diagnoses on a
//! 28-byte reply that turned out to belong to a CycloneDDS `add_two_ints_server`
//! on a DIFFERENT HOST, squatting 35 ROS domains. The repro needed none of our
//! code:
//!
//! ```text
//! $ ROS_DOMAIN_ID=1 ros2 service call /add_two_ints \
//!     example_interfaces/srv/AddTwoInts "{a: 5, b: 3}"
//! [RTPS_READER_HISTORY Error] Change payload size of '28' bytes is larger than
//! the history payload size of '15' bytes and cannot be resized.
//! ```
//!
//! # `ROS_LOCALHOST_ONLY=1` IS NOT THE FIX, and that is measured
//!
//! | batch | condition | pass / fail |
//! | --- | --- | ---: |
//! | D | per-run daemon kill, UDP-only profile | 12 / 3 |
//! | F | `ROS_LOCALHOST_ONLY=1` alone | **0 / 15** |
//! | G | Fast-DDS `interfaceWhiteList 127.0.0.1`, BOTH processes | **15 / 15** |
//!
//! Batch F is zero passes with EMPTY client output — no history error at all —
//! because **the XRCE Agent is a bare Fast-DDS application, not a ROS process**,
//! so it ignores `ROS_LOCALHOST_ONLY` and the two sides stop discovering each
//! other. A variable that isolates one half of a pair is worse than none: it
//! turns a wrong answer into no answer.
//!
//! What works is a profile FILE, exported so both the peer and the Agent read
//! it. That is what this module writes and hands out.
//!
//! # Do not combine with `ROS_LOCALHOST_ONLY`
//!
//! A custom `userTransports` profile DEFEATS that variable (the issue's batch E
//! is confounded, 9/6, for exactly this reason). Nothing here sets it, and
//! nothing else should alongside it.

use std::{
    io::Write as _,
    path::{Path, PathBuf},
    sync::OnceLock,
};

/// Escape hatch: leave the bus on the LAN.
///
/// For the one case this isolation cannot serve — a peer that must genuinely
/// reach another host. Deliberately an env var and not a parameter: the callers
/// are ~14 helper functions that all want the same answer, and a parameter
/// threaded through every one of them is a parameter someone passes wrong.
pub fn lan_allowed() -> bool {
    std::env::var_os("NROS_DDS_ALLOW_LAN").is_some()
}

/// Per-process directory holding the generated profiles.
///
/// Per PROCESS, not per repo: two nextest binaries running at once must not
/// write the same file while the other is reading it. The pid makes that
/// impossible without any locking.
fn profile_dir() -> &'static Path {
    static DIR: OnceLock<PathBuf> = OnceLock::new();
    DIR.get_or_init(|| {
        let dir = std::env::temp_dir().join(format!("nros-dds-loopback-{}", std::process::id()));
        let _ = std::fs::create_dir_all(&dir);
        dir
    })
}

/// Write `content` to `<profile_dir>/<name>` once, atomically, and return it.
///
/// Atomic because the Agent may be spawned while a sibling helper is still
/// building its env string, and a half-written profile is a parse error that
/// presents as "no discovery" — the exact symptom this module exists to remove.
fn write_once(name: &str, content: &str) -> PathBuf {
    let path = profile_dir().join(name);
    if path.exists() {
        return path;
    }
    let tmp = path.with_extension("tmp");
    if let Ok(mut f) = std::fs::File::create(&tmp) {
        if f.write_all(content.as_bytes()).is_ok() {
            let _ = f.sync_all();
            let _ = std::fs::rename(&tmp, &path);
        }
    }
    path
}

/// Fast-DDS profile pinning every participant to the loopback interface.
///
/// `useBuiltinTransports=false` matters as much as the whitelist: leaving the
/// builtin transports on adds a second, un-whitelisted UDPv4 descriptor beside
/// this one, and discovery escapes through it.
const FASTDDS_LOOPBACK_XML: &str = r#"<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by nros-tests (issue 1009). Do not edit; see dds_isolation.rs. -->
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
  <profiles>
    <transport_descriptors>
      <transport_descriptor>
        <transport_id>nros_loopback_udp</transport_id>
        <type>UDPv4</type>
        <interfaceWhiteList>
          <address>127.0.0.1</address>
        </interfaceWhiteList>
      </transport_descriptor>
    </transport_descriptors>
    <participant profile_name="nros_loopback" is_default_profile="true">
      <rtps>
        <userTransports>
          <transport_id>nros_loopback_udp</transport_id>
        </userTransports>
        <useBuiltinTransports>false</useBuiltinTransports>
      </rtps>
    </participant>
  </profiles>
</dds>
"#;

/// CycloneDDS equivalent.
///
/// **NOT measured the way the Fast-DDS profile was.** The issue records 15/15
/// for the Fast-DDS side against a live foreign peer and says plainly that the
/// `CYCLONEDDS_URI` equivalent "is not yet written". This is that file, written
/// from Cyclone's documented config, and it has been shown to keep a local pair
/// talking — but never against the poisoned domain, because the 35 orphans on
/// `arm-a100` were cleared before it existed. Treat the isolation as asserted
/// for Cyclone and demonstrated for Fast-DDS.
///
/// `AllowMulticast=false` plus an explicit localhost peer is the pair that does
/// the work: the interface alone still leaves SPDP announcing to a multicast
/// group, and a participant elsewhere on the LAN that announces to the same
/// group is still discovered.
const CYCLONE_LOOPBACK_XML: &str = r#"<?xml version="1.0" encoding="UTF-8" ?>
<!-- Generated by nros-tests (issue 1009). Do not edit; see dds_isolation.rs. -->
<CycloneDDS xmlns="https://cdds.io/config">
  <Domain id="any">
    <General>
      <Interfaces>
        <NetworkInterface address="127.0.0.1" priority="default" multicast="false" />
      </Interfaces>
      <AllowMulticast>false</AllowMulticast>
    </General>
    <Discovery>
      <ParticipantIndex>auto</ParticipantIndex>
      <Peers>
        <Peer address="localhost"/>
      </Peers>
    </Discovery>
  </Domain>
</CycloneDDS>
"#;

/// Path to the generated Fast-DDS loopback profile.
pub fn fastdds_profile_path() -> PathBuf {
    write_once("nros-loopback-fastdds.xml", FASTDDS_LOOPBACK_XML)
}

/// `file://` URI for the generated CycloneDDS loopback config.
pub fn cyclone_config_uri() -> String {
    format!(
        "file://{}",
        write_once("nros-loopback-cyclone.xml", CYCLONE_LOOPBACK_XML).display()
    )
}

/// Bash `export` clauses that put `rmw` on loopback, or an empty string.
///
/// Empty when the caller opted out, and empty for an RMW this does not know
/// how to isolate — silently doing nothing is right there, because the
/// alternative is exporting a variable the middleware ignores, which is
/// precisely the `ROS_LOCALHOST_ONLY` failure one layer up.
///
/// An operator's own `FASTRTPS_DEFAULT_PROFILES_FILE` / `CYCLONEDDS_URI` wins:
/// someone debugging a transport has a reason, and a test harness that
/// overwrites it makes the debugging session lie.
pub fn env_exports_for_rmw(rmw: &str) -> String {
    if lan_allowed() {
        return String::new();
    }
    match rmw {
        "rmw_fastrtps_cpp" | "rmw_fastrtps_dynamic_cpp" => {
            if std::env::var_os("FASTRTPS_DEFAULT_PROFILES_FILE").is_some() {
                return String::new();
            }
            format!(
                " && export FASTRTPS_DEFAULT_PROFILES_FILE={}",
                fastdds_profile_path().display()
            )
        }
        "rmw_cyclonedds_cpp" => {
            if std::env::var_os("CYCLONEDDS_URI").is_some() {
                return String::new();
            }
            format!(" && export CYCLONEDDS_URI={}", cyclone_config_uri())
        }
        _ => String::new(),
    }
}

/// Put the Fast-DDS loopback profile on a `Command`'s environment.
///
/// This is the half `ROS_LOCALHOST_ONLY` could never reach. The XRCE Agent is
/// spawned directly rather than through a `source setup.bash` shell, so it gets
/// the profile as an env var on the `Command` itself.
pub fn apply_fastdds_profile(cmd: &mut std::process::Command) {
    if lan_allowed() || std::env::var_os("FASTRTPS_DEFAULT_PROFILES_FILE").is_some() {
        return;
    }
    cmd.env("FASTRTPS_DEFAULT_PROFILES_FILE", fastdds_profile_path());
}

/// Put the CycloneDDS loopback config on a `Command`'s environment.
///
/// The sibling of [`apply_fastdds_profile`], and it did not exist — which is
/// issue 1137. Cyclone's `dds_create_participant` reads `CYCLONEDDS_URI`
/// through Cyclone's own loader (`nros-rmw-cyclonedds/src/session.cpp` leaves
/// the hosted path to it deliberately), so this reaches a nano-ros binary
/// exactly the way the shell export reaches a `ros2` peer.
pub fn apply_cyclone_config(cmd: &mut std::process::Command) {
    if lan_allowed() || std::env::var_os("CYCLONEDDS_URI").is_some() {
        return;
    }
    cmd.env("CYCLONEDDS_URI", cyclone_config_uri());
}

/// Put EVERY known loopback profile on a `Command`'s environment — the
/// bare-`Command` twin of [`env_exports_for_rmw`].
///
/// # Why this exists, and why it is not per-RMW
///
/// Issue 1009 pinned the bus through [`env_exports_for_rmw`], which only ever
/// reaches a process started from a `source setup.bash` shell string — i.e. the
/// **ROS 2 peer**. Our own side of every pair is a bare `Command`, and it got
/// nothing. That is exactly the state the issue's own headline forbids: *pin
/// both sides or neither; half is no discovery.* Two days later
/// `cyclone_enumerates_a_stock_ros2_node` — which had PASSED live on 2026-08-30
/// (issue 0927) — enumerated only itself again with the identical signature,
/// because the stock talker was pinned to `127.0.0.1` with
/// `AllowMulticast=false` and an explicit localhost peer while our probe kept
/// Cyclone's default interface pick. Neither side could see the other's SPDP.
/// Issue 1137.
///
/// It sets BOTH variables rather than asking which middleware the child speaks,
/// for two reasons:
///
/// * the caller usually cannot know. A fixture binary is built per-RMW and the
///   spawn site holds only a `PathBuf`; `graph-probe` is literally one source
///   compiled once per backend.
/// * a variable naming a middleware the child does not link is inert. That is
///   the opposite of the `ROS_LOCALHOST_ONLY` failure this module was written
///   about, where the variable was honoured by one side and ignored by the
///   other — here NEITHER half of a mismatched pair can act on it, so it cannot
///   create an asymmetry.
///
/// # Where to call it, and where NOT to
///
/// At the spawn site of a nano-ros process whose PEER is a host `ros2` process
/// — i.e. one started through [`env_exports_for_rmw`]. Deliberately NOT inside
/// [`crate::process::ManagedProcess::spawn_command`], which would look like the
/// chokepoint and be wrong: the `DockerRosEnv` editions lanes run their peer in
/// a container that cannot read a host profile path, so those pairs are
/// symmetric-UNPINNED and pinning our half of one would CREATE this bug. What
/// keeps a new site from forgetting is `check-dds-isolation-symmetry`, not this
/// function's placement.
pub fn apply_to_command(cmd: &mut std::process::Command) {
    apply_fastdds_profile(cmd);
    apply_cyclone_config(cmd);
}

/// Is the bus pinned for `rmw` at all? True unless the caller opted out.
///
/// The predicate BOTH sides are supposed to agree on, exposed so
/// `both_spawn_paths_pin_the_same_buses` can assert the agreement rather than
/// restate it.
#[must_use]
pub fn pins_loopback_for(rmw: &str) -> bool {
    !env_exports_for_rmw(rmw).is_empty()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_generated_profiles_are_well_formed_and_pin_loopback() {
        // Not a schema check -- a check that the two clauses which actually do
        // the work are present. A profile that parses but leaves the builtin
        // transports on isolates nothing, and would pass a well-formedness test.
        let fast = std::fs::read_to_string(fastdds_profile_path()).unwrap();
        assert!(fast.contains("<address>127.0.0.1</address>"));
        assert!(fast.contains("<useBuiltinTransports>false</useBuiltinTransports>"));
        assert!(fast.trim_start().starts_with("<?xml"));

        let uri = cyclone_config_uri();
        let path = uri.strip_prefix("file://").unwrap();
        let cyc = std::fs::read_to_string(path).unwrap();
        assert!(cyc.contains("<AllowMulticast>false</AllowMulticast>"));
        assert!(cyc.contains(r#"address="127.0.0.1""#));
    }

    #[test]
    fn an_unknown_rmw_gets_no_exports_rather_than_a_variable_it_ignores() {
        // The `ROS_LOCALHOST_ONLY` lesson as an assertion: exporting something
        // the middleware ignores is worse than exporting nothing, because it
        // reads as isolation while providing none.
        assert_eq!(env_exports_for_rmw("rmw_zenoh_cpp"), "");
        assert_eq!(env_exports_for_rmw(""), "");
    }

    #[test]
    fn each_known_dds_rmw_gets_its_own_variable() {
        // Only meaningful when the caller has not opted out or pre-set one.
        if lan_allowed() {
            return;
        }
        if std::env::var_os("FASTRTPS_DEFAULT_PROFILES_FILE").is_none() {
            assert!(
                env_exports_for_rmw("rmw_fastrtps_cpp").contains("FASTRTPS_DEFAULT_PROFILES_FILE")
            );
        }
        if std::env::var_os("CYCLONEDDS_URI").is_none() {
            assert!(env_exports_for_rmw("rmw_cyclonedds_cpp").contains("CYCLONEDDS_URI"));
        }
    }

    /// **Issue 1137 — the two spawn paths must pin the SAME set of buses.**
    ///
    /// The shell path ([`env_exports_for_rmw`]) reaches a `ros2` peer; the
    /// `Command` path ([`apply_to_command`]) reaches our own binary. Issue 1009
    /// built the first and not the second, so every Cyclone pair ran half
    /// pinned, and "half is no discovery" is the issue's own conclusion.
    ///
    /// Asserted as an equivalence rather than as two separate presence checks:
    /// a presence check on each side passes when only one of them exists, which
    /// is the defect.
    #[test]
    fn both_spawn_paths_pin_the_same_buses() {
        if lan_allowed() {
            return;
        }
        for (rmw, var) in [
            ("rmw_fastrtps_cpp", "FASTRTPS_DEFAULT_PROFILES_FILE"),
            ("rmw_cyclonedds_cpp", "CYCLONEDDS_URI"),
        ] {
            if std::env::var_os(var).is_some() {
                // An operator's own profile wins on both paths; nothing to compare.
                continue;
            }
            let mut cmd = std::process::Command::new("true");
            apply_to_command(&mut cmd);
            let on_command = cmd
                .get_envs()
                .any(|(k, v)| k == var && v.is_some_and(|v| !v.is_empty()));
            assert_eq!(
                pins_loopback_for(rmw),
                on_command,
                "the shell path and the Command path disagree about {var}: a peer \
                 started through `source setup.bash` and a nano-ros binary started \
                 as a bare Command would land on different buses, which is issue \
                 1137 (and 1009's own 'pin both sides or neither')"
            );
        }
    }

    /// The variable actually reaches a CHILD, and the file it names is READABLE
    /// from there.
    ///
    /// Asserted on a real child's environment rather than on the `Command`
    /// struct, and on the file's CONTENT rather than on its path: a
    /// `CYCLONEDDS_URI` pointing at a file the child cannot open is how Cyclone
    /// silently keeps its default interface pick, which is indistinguishable
    /// from no pin at all — the same "absent vs empty" confusion the whole
    /// graph family is about.
    #[test]
    fn a_child_inherits_a_cyclone_config_it_can_actually_read() {
        if lan_allowed() || std::env::var_os("CYCLONEDDS_URI").is_some() {
            return;
        }
        let mut cmd = std::process::Command::new("sh");
        cmd.args(["-c", r#"cat "${CYCLONEDDS_URI#file://}""#]);
        apply_to_command(&mut cmd);
        let out = cmd.output().expect("run sh");
        let text = String::from_utf8_lossy(&out.stdout).into_owned();
        assert!(
            text.contains("<AllowMulticast>false</AllowMulticast>"),
            "a child given CYCLONEDDS_URI must be able to READ the profile it \
             names; `cat` of it produced:\n{text}{}",
            String::from_utf8_lossy(&out.stderr)
        );
    }
}
