#!/bin/bash
# Build zenoh-pico for ARM Cortex-M3 (QEMU mps2-an385)
#
# Cross-compiles zenoh-pico as a static library for bare-metal ARM Cortex-M3.
# This produces a standalone .a that serves as a build-readiness check for
# QEMU E2E tests. The actual linking is done by zpico-sys/build.rs via cc::Build.
#
# Usage:
#   ./scripts/qemu/build-zenoh-pico.sh [--clean]
#
# Output:
#   build/qemu-zenoh-pico/libzenohpico.a
#
# Prerequisites:
#   - arm-none-eabi-gcc toolchain

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
# phase-334 W2.b step 2 — RFC-0070 R3: one derivation, not a literal.
# shellcheck source=scripts/build/build-root.sh
source "$REPO_ROOT/scripts/build/build-root.sh"
BUILD_DIR="$(nros_build_dir "$NROS_KIND_QEMU_ZENOH_PICO")"
ZENOH_PICO_DIR="$REPO_ROOT/packages/rmw/zenoh/zpico-sys/zenoh-pico"
# The vendored tree's SOURCE root. Every path BELOW it is read from the shared
# manifest (see the selection block further down), never spelled here — that is
# what `check-zenoh-source-manifest`'s "no lane names a vendored path" asserts
# about this file.
ZENOH_PICO_SRC="$ZENOH_PICO_DIR/src"
ZENOH_SOURCE_MANIFEST="$REPO_ROOT/packages/rmw/zenoh/zpico-sys/zenoh-sources.txt"
C_DIR="$REPO_ROOT/packages/rmw/zenoh/zpico-sys/c"
PLATFORM_DIR="$C_DIR/platform"

# Parse arguments
if [ "$1" = "--clean" ]; then
    echo "Cleaning build directory..."
    rm -rf "$BUILD_DIR"
    echo "Done."
    exit 0
fi

# Check prerequisites
if ! command -v arm-none-eabi-gcc &>/dev/null; then
    echo "Error: arm-none-eabi-gcc not found"
    echo "Install with: sudo apt install gcc-arm-none-eabi"
    exit 1
fi

# Check zenoh-pico submodule
if [ ! -d "$ZENOH_PICO_DIR/include" ]; then
    echo "Error: zenoh-pico submodule not found"
    echo "Run: git submodule update --init"
    exit 1
fi

echo "Building zenoh-pico for ARM Cortex-M3..."

# Create build directory
mkdir -p "$BUILD_DIR"

# Generate version header (matches build.rs generate_embedded_version_header)
VERSION=$(cat "$ZENOH_PICO_DIR/version.txt" 2>/dev/null || echo "0.11.0")
MAJOR=$(echo "$VERSION" | cut -d. -f1)
MINOR=$(echo "$VERSION" | cut -d. -f2)
PATCH=$(echo "$VERSION" | cut -d. -f3)

mkdir -p "$BUILD_DIR/include"
cat > "$BUILD_DIR/include/zenoh-pico.h" << EOF
// Auto-generated version header for zenoh-pico
#ifndef ZENOH_PICO_H
#define ZENOH_PICO_H

#define ZENOH_PICO "$VERSION"
#define ZENOH_PICO_MAJOR $MAJOR
#define ZENOH_PICO_MINOR $MINOR
#define ZENOH_PICO_PATCH $PATCH
#define ZENOH_PICO_TWEAK 0

#include "zenoh-pico/api.h"

#endif // ZENOH_PICO_H
EOF

# Generate config header (matches build.rs generate_config_header)
mkdir -p "$BUILD_DIR/zenoh-config"
cat > "$BUILD_DIR/zenoh-config/zenoh_generic_config.h" << 'EOF'
/**
 * zenoh_generic_config.h - Generated by build-zenoh-pico.sh
 *
 * A MIRROR of what `nros_zpico_build::config_header()` generates for a
 * bare-metal target — issue 1096. It is a mirror and not a derivation because
 * that function resolves its inputs from cargo build-script environment (link
 * features, the RFC-0049 wire ladder, board knobs) that a standalone shell
 * script has no way to supply; reproducing the resolution here would be a
 * fourth statement of it, not one fewer.
 *
 * What it is NOT is an unwatched mirror, which is what it was: measured
 * 2026-09-05 it had drifted in ten places, including Z_TRANSPORT_LEASE (10000
 * against the 60000 issue 0906 moved it to) and Z_FEATURE_MATCHING /
 * Z_FEATURE_LOCAL_SUBSCRIBER / Z_FEATURE_LOCAL_QUERYABLE, which decide which
 * code compiles — so the readiness check was answering for a build nobody
 * performs. `check-zenoh-config-header-mirror` now compares this block against
 * that function's emissions, by macro NAME for every unconditional `#define`
 * and by VALUE wherever the Rust value is a literal.
 *
 * DO NOT EDIT BY HAND to make the gate pass: change `config_header()` and
 * mirror it here, in that order.
 */

#ifndef ZENOH_GENERIC_CONFIG_H
#define ZENOH_GENERIC_CONFIG_H

// Buffer Sizes
#define Z_FRAG_MAX_SIZE 1500
#define Z_BATCH_UNICAST_SIZE 2048
#define Z_BATCH_MULTICAST_SIZE 2048
#define Z_CONFIG_SOCKET_TIMEOUT 100
#define Z_TRANSPORT_LEASE 60000
#define Z_TRANSPORT_LEASE_EXPIRE_FACTOR 3
#define Z_TRANSPORT_LEASE_TASK_SLEEP_CHUNK_MS 1000
#define ZP_PERIODIC_SCHEDULER_MAX_TASKS 8

// Core Features
#ifndef Z_FEATURE_MULTI_THREAD
#define Z_FEATURE_MULTI_THREAD 0
#endif
#define Z_FEATURE_PUBLICATION 1
#define Z_FEATURE_ADVANCED_PUBLICATION 0
#define Z_FEATURE_SUBSCRIPTION 1
#define Z_FEATURE_ADVANCED_SUBSCRIPTION 0
#define Z_FEATURE_QUERY 1
#define Z_FEATURE_QUERYABLE 1
#define Z_FEATURE_LIVELINESS 1
#define Z_FEATURE_INTEREST 1

// Transport Link Features
#define Z_FEATURE_LINK_TCP 1
#define Z_FEATURE_LINK_UDP_UNICAST 0
#define Z_FEATURE_LINK_UDP_MULTICAST 0
#define Z_FEATURE_LINK_SERIAL 0
#define Z_FEATURE_LINK_SERIAL_USB 0
#define Z_FEATURE_LINK_IVC 0
#define Z_FEATURE_LINK_CUSTOM 0
#define Z_FEATURE_LINK_CAN 0
#define Z_FEATURE_LINK_ISOTP 0
#define Z_FEATURE_LINK_TLS 0
#define Z_FEATURE_LINK_WS 0
#define Z_FEATURE_LINK_BLUETOOTH 0
#define Z_FEATURE_RAWETH_TRANSPORT 0

// Transport Modes
#define Z_FEATURE_UNICAST_TRANSPORT 1
#define Z_FEATURE_MULTICAST_TRANSPORT 0
#define Z_FEATURE_SCOUTING 0
#ifndef Z_FEATURE_SCOUTING_UDP
#define Z_FEATURE_SCOUTING_UDP 0
#endif

// Protocol Features
#define Z_FEATURE_FRAGMENTATION 1
#define Z_FEATURE_ENCODING_VALUES 1
#define Z_FEATURE_TCP_NODELAY 1
#define Z_FEATURE_LOCAL_SUBSCRIBER 1
#define Z_FEATURE_LOCAL_QUERYABLE 1
#define Z_FEATURE_SESSION_CHECK 1
#define Z_FEATURE_BATCHING 0
#define Z_FEATURE_TX_SPLIT_LOCK 0
#define Z_FEATURE_BATCH_TX_MUTEX 0
#define Z_FEATURE_BATCH_PEER_MUTEX 0
#define Z_FEATURE_MATCHING 1
#define Z_FEATURE_RX_CACHE 0
#define Z_FEATURE_UNICAST_PEER 0
#define Z_FEATURE_AUTO_RECONNECT 1
#define Z_FEATURE_MULTICAST_DECLARATIONS 0
#define Z_FEATURE_PERIODIC_TASKS 0

#endif // ZENOH_GENERIC_CONFIG_H
EOF

# ---------------------------------------------------------------------------
# The zenoh-pico source selection — READ, never restated. Issue 1096.
#
# This script is the THIRD compiler of the vendored tree, after
# `nros-zpico-build` (cargo) and `zephyr/cmake/nros_rmw_zenoh.cmake` (west).
# It used to hold its own copy of the nine directory globs those two share,
# with no "matches build.rs" comment on it and no gate watching it, so an
# upstream bump that added a directory would have left this readiness check
# quietly compiling yesterday's set and reporting the bare-metal build healthy.
# It now reads the same `zenoh-sources.txt` they do; the grammar is that
# file's own header, and `just check zenoh-source-manifest` holds all three
# readers to it.
#
# NOTE the failure policy: every error below EXITS. There is deliberately no
# fallback to a built-in list — a fallback would put the drift back while
# looking fixed, which is worse than the copy this replaces.

zenoh_manifest_die() {
    echo "Error: $ZENOH_SOURCE_MANIFEST: $1" >&2
    echo "       (the shared zenoh-pico source list — phase-420 W9, issue 1096;" >&2
    echo "        gate: just check zenoh-source-manifest)" >&2
    exit 1
}

if [ ! -f "$ZENOH_SOURCE_MANIFEST" ]; then
    echo "Error: the shared zenoh-pico source manifest is missing:" >&2
    echo "         $ZENOH_SOURCE_MANIFEST" >&2
    echo "       It is tracked in-repo, so a missing one means an incomplete" >&2
    echo "       checkout: restore it from git before building." >&2
    echo "       This script does NOT fall back to a directory list of its own:" >&2
    echo "       that copy is exactly what issue 1096 removed." >&2
    exit 1
fi

# NROS-ZENOH-CONDITIONS-BEGIN — the boolean this lane supplies for each
# condition token the manifest uses. `check-zenoh-source-manifest` asserts that
# this is exactly the token set the manifest declares and that the other two
# lanes answer, so a new group cannot silently drop out of the bare-metal
# readiness build. The manifest, not this function, decides which sources a
# token covers.
zenoh_condition() {
    case "$1" in
        # The core. Every lane, every platform.
        always) return 0 ;;
        # This is a bare-metal Cortex-M3 build: not Zephyr, so neither Zephyr's
        # vendored `system/zephyr/network.c` nor its ISO-TP binding.
        zephyr) return 1 ;;
        zephyr_isotp) return 1 ;;
        *)
            echo "Error: $ZENOH_SOURCE_MANIFEST uses condition token \`$1\`, which this" >&2
            echo "       lane does not answer. Add a case arm here AND an arm in" >&2
            echo "       nros-zpico-build/src/lib.rs AND a set(_zenoh_cond_$1 ...) in" >&2
            echo "       zephyr/cmake/nros_rmw_zenoh.cmake — a token only some lanes" >&2
            echo "       answer is the same defect one conditional over." >&2
            exit 1
            ;;
    esac
}
# NROS-ZENOH-CONDITIONS-END

# `#` comments out, blank lines out — the manifest's grammar, same as the
# cmake lane's `file(STRINGS)` loop and the Rust lane's `parse_zenoh_sources`.
zenoh_manifest_rows() {
    sed 's/#.*//' "$ZENOH_SOURCE_MANIFEST" | awk 'NF'
}

declare -A ZENOH_GROUP_COND=()
while read -r kind a b c extra; do
    case "$kind" in
        group)
            if [ -z "$a" ] || [ -z "$b" ] || [ -n "$c" ]; then
                zenoh_manifest_die "expected \`group <name> <condition>\`, got \`$kind $a $b $c $extra\`"
            fi
            if [ -n "${ZENOH_GROUP_COND[$a]:-}" ]; then
                zenoh_manifest_die "group \`$a\` declared twice"
            fi
            ZENOH_GROUP_COND[$a]="$b"
            ;;
        dir | src)
            if [ -z "$c" ] || [ -n "$extra" ]; then
                zenoh_manifest_die "expected \`$kind <group> <tree> <path>\`, got \`$kind $a $b $c $extra\`"
            fi
            ;;
        *)
            zenoh_manifest_die "unknown record type \`$kind\` (expected group, dir or src)"
            ;;
    esac
done < <(zenoh_manifest_rows)

SOURCES=""
while read -r kind a b c _extra; do
    # `[ ... ] && continue` would be the shorter spelling and a worse one under
    # `set -e`: its failure branch is the common case here.
    if [ "$kind" = "group" ]; then
        continue
    fi
    cond="${ZENOH_GROUP_COND[$a]:-}"
    if [ -z "$cond" ]; then
        zenoh_manifest_die "\`$c\` names group \`$a\`, which no \`group\` line declares"
    fi
    if [ "$b" != "zenoh_pico" ]; then
        zenoh_manifest_die "\`$c\` names tree \`$b\`; this lane only knows \`zenoh_pico\`"
    fi
    zenoh_condition "$cond" || continue
    if [ "$kind" = "dir" ]; then
        if [ ! -d "$ZENOH_PICO_SRC/$c" ]; then
            zenoh_manifest_die "lists directory \`$c\`, which is not a directory in the vendored tree"
        fi
        # RECURSIVELY, which is the rule the manifest states and every lane
        # expands. A listed directory with no `.c` in it is drift, not an
        # empty set.
        found=$(find "$ZENOH_PICO_SRC/$c" -name "*.c")
        if [ -z "$found" ]; then
            zenoh_manifest_die "lists directory \`$c\`, which holds no .c files"
        fi
        SOURCES="$SOURCES $found"
    else
        if [ ! -f "$ZENOH_PICO_SRC/$c" ]; then
            zenoh_manifest_die "lists source \`$c\`, which does not exist"
        fi
        SOURCES="$SOURCES $ZENOH_PICO_SRC/$c"
    fi
done < <(zenoh_manifest_rows)

if [ -z "$SOURCES" ]; then
    zenoh_manifest_die "selected no sources — manifest or condition drift"
fi

# Add zpico (high-level API wrapper). NOT part of the vendored tree, and
# deliberately not in the manifest: the cargo lane reaches it through each
# platform's `extra_sources` and the cmake lane names it directly.
SOURCES="$SOURCES $C_DIR/zpico/zpico.c"

# Note: No system.c/network.c — bare-metal platform symbols are provided by
# Rust FFI (zpico-platform-mps2-an385). This library only contains zenoh-pico
# core + zpico shim.

# Compiler flags
CFLAGS="-mcpu=cortex-m3 -mthumb"
CFLAGS="$CFLAGS -Os -g"
CFLAGS="$CFLAGS -ffunction-sections -fdata-sections"
CFLAGS="$CFLAGS -fno-common -fno-exceptions"
CFLAGS="$CFLAGS -Wall -Wextra -Wno-unused-but-set-variable"

# Include paths (order matters — generated config takes precedence)
INCLUDES="-I$BUILD_DIR/zenoh-config"
INCLUDES="$INCLUDES -I$ZENOH_PICO_DIR/include"
INCLUDES="$INCLUDES -I$BUILD_DIR/include"
INCLUDES="$INCLUDES -I$PLATFORM_DIR"
INCLUDES="$INCLUDES -I$PLATFORM_DIR/bare-metal"
INCLUDES="$INCLUDES -I$C_DIR/include"
# Phase 154 — zpico.c includes <nros/platform_net.h> (the canonical
# platform ABI header). It lives in nros-platform-cffi, which the
# Rust build.rs already has on its include path; the standalone
# embedded build script needs it too.
INCLUDES="$INCLUDES -I$REPO_ROOT/packages/platform/nros-platform-api/include"

# Platform defines.
#
# Issue 1096 — these three, and ONLY these three. This list used to restate ten
# `Z_FEATURE_*` values that the generated config header above already states,
# inside the same file, a few lines apart: `ZENOH_GENERIC` makes
# `zenoh-pico/config.h` include that header and nothing else, so every one of
# them was the same fact written twice with nothing checking the two spellings
# agreed. The header is where a `Z_FEATURE_*` belongs (it is what the cargo
# lane generates and what `check-zenoh-config-header-mirror` compares); a `-D`
# here belongs only to something the header does not say.
DEFINES="-DZENOH_GENERIC"
DEFINES="$DEFINES -DZPICO_SMOLTCP"
DEFINES="$DEFINES -DZENOH_DEBUG=0"

# Shim slot counts — a MIRROR of `ShimConfig`'s defaults, with a detector.
#
# Issue 1096. Same argument as the config header above: `shim_config_from_env()`
# resolves these from cargo build-script environment and the RFC-0049 ladder, so
# a shell script cannot derive them, only restate them. Held to the real values
# by `check-zenoh-lane-ownership` (12), which reads the macro⇄field mapping out
# of `ShimConfig::defines()` and the defaults out of `shim_config_from_env()`.
#
# The last three are here because that gate found them missing. Every one of
# these has a `#ifndef` fallback in `zpico.c`, so leaving a `-D` out is not "no
# opinion" — it is the shim's own default winning on this lane alone, which is
# issue 0460's shape. Their values (1 / 16 / 16) equal today's C fallbacks, so
# adding them changed no preprocessing; what changed is that the readiness build
# now STATES the configuration it is checking, and a moved default is a red gate
# instead of a silent divergence.
DEFINES="$DEFINES -DZPICO_MAX_PUBLISHERS=8"
DEFINES="$DEFINES -DZPICO_MAX_SUBSCRIBERS=8"
DEFINES="$DEFINES -DZPICO_MAX_QUERYABLES=8"
DEFINES="$DEFINES -DZPICO_MAX_LIVELINESS=16"
DEFINES="$DEFINES -DZPICO_MAX_PENDING_GETS=4"
DEFINES="$DEFINES -DZPICO_MAX_SESSIONS=1"
DEFINES="$DEFINES -DZPICO_GET_REPLY_BUF_SIZE=4096"
DEFINES="$DEFINES -DZPICO_GET_POLL_INTERVAL_MS=10"
DEFINES="$DEFINES -DZPICO_READ_TASK_PRIORITY=16"
DEFINES="$DEFINES -DZPICO_LEASE_TASK_PRIORITY=16"

# Compile each source file
OBJECTS=""
count=0
for src in $SOURCES; do
    basename=$(basename "$src" .c)
    # Handle name collisions by using full path hash
    objname=$(echo "$src" | md5sum | cut -c1-8)_${basename}.o
    obj="$BUILD_DIR/$objname"

    arm-none-eabi-gcc $CFLAGS $INCLUDES $DEFINES -c "$src" -o "$obj"
    OBJECTS="$OBJECTS $obj"
    count=$((count + 1))
done

# Create static library
arm-none-eabi-ar rcs "$BUILD_DIR/libzenohpico.a" $OBJECTS

echo "Built $count sources → $BUILD_DIR/libzenohpico.a ($(stat -c%s "$BUILD_DIR/libzenohpico.a" | numfmt --to=iec-i --suffix=B))"
