/**
 * zpico-sys Public C API
 *
 * AUTO-GENERATED by cbindgen - DO NOT EDIT MANUALLY
 *
 * This header defines the high-level C API for zenoh-pico that can be
 * called from Rust FFI. It provides session management, publishers, and
 * subscribers with static storage.
 *
 * Platform-specific behavior (threading vs polling) is handled by the
 * backend interface in bare-metal/platform.h
 */

#ifndef ZPICO_H
#define ZPICO_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Size of Zenoh ID in bytes
 */
#define ZPICO_ZID_SIZE 16

/**
 * Size of RMW GID in bytes (for ROS 2 humble compatibility)
 */
#define ZPICO_RMW_GID_SIZE 16

/**
 * Success
 */
#define ZPICO_OK 0

/**
 * Generic error
 */
#define ZPICO_ERR_GENERIC -1

/**
 * Configuration error
 */
#define ZPICO_ERR_CONFIG -2

/**
 * Session error
 */
#define ZPICO_ERR_SESSION -3

/**
 * Task creation error
 */
#define ZPICO_ERR_TASK -4

/**
 * Invalid key expression
 */
#define ZPICO_ERR_KEYEXPR -5

/**
 * Resource limit reached
 */
#define ZPICO_ERR_FULL -6

/**
 * Invalid handle
 */
#define ZPICO_ERR_INVALID -7

/**
 * Publish error
 */
#define ZPICO_ERR_PUBLISH -8

/**
 * Query timeout
 */
#define ZPICO_ERR_TIMEOUT -9

/**
 * Caller's buffer cannot hold the value, which is REFUSED rather than
 * truncated (phase-381 W1) — a partial keyexpr names a different, plausible
 * entity, so `zpico_liveliness_entry` never returns one.
 */
#define ZPICO_ERR_BUFFER -10

/**
 * Opaque per-session handle (issue 0348 / phase-328). A `zpico_session_t*`
 * points into the C shim's compile-time session pool
 * (`ZPICO_MAX_SESSIONS`, default 1). Every `zpico_*` entry point that
 * operates on a session takes one as its leading argument. Rust never
 * dereferences it — it is a bare pointer forwarded to the C shim.
 *
 * EXCEPTIONS to the handle rule (process-wide, no session arg):
 * `zpico_set_task_config` / `zpico_set_flush_task_config` are process-wide
 * task-spawn DEFAULTS applied at `zpico_open` (they are called from board
 * boot before any session exists), and `zpico_get_diag_counters` /
 * `zpico_uses_polling` / the clock helpers are process-global.
 */
typedef struct zpico_session_t {
  uint8_t _private[0];
} zpico_session_t;

/**
 * A key-value property for transport configuration (C-compatible)
 */
typedef struct zpico_property_t {
  /**
   * Property key (null-terminated C string)
   */
  const char *key;
  /**
   * Property value (null-terminated C string)
   */
  const char *value;
} zpico_property_t;

/**
 * Callback function type for receiving samples (legacy, payload only).
 *
 * # Parameters
 * * `data` - Pointer to received data buffer
 * * `len` - Length of data in bytes
 * * `ctx` - User-provided context pointer
 */
typedef void (*ZpicoCallback)(const uint8_t *data, size_t len, void *ctx);

/**
 * Callback function type for receiving samples with attachment (RMW compatible).
 *
 * # Parameters
 * * `data` - Pointer to received data buffer
 * * `len` - Length of data in bytes
 * * `attachment` - Pointer to attachment buffer (may be NULL)
 * * `attachment_len` - Length of attachment in bytes
 * * `ctx` - User-provided context pointer
 */
typedef void (*ZpicoCallbackWithAttachment)(const uint8_t *data,
                                            size_t len,
                                            const uint8_t *attachment,
                                            size_t attachment_len,
                                            void *ctx);

/**
 * Notify callback for direct-write subscribers.
 *
 * Called after the C shim has written the payload directly into the Rust
 * static buffer. Only provides the payload length and attachment data.
 *
 * # Parameters
 * * `len` - Length of payload already written to the buffer
 * * `attachment` - Pointer to attachment buffer (may be NULL)
 * * `attachment_len` - Length of attachment in bytes
 * * `ctx` - User-provided context pointer
 */
typedef void (*ZpicoNotifyCallback)(size_t len,
                                    const uint8_t *attachment,
                                    size_t attachment_len,
                                    void *ctx);

/**
 * Phase 124.D.3.c — SPSC ring descriptor mirroring
 * `zpico_ring_desc_t` in `c/include/zpico.h`. Field order, names,
 * and types track the C struct byte-for-byte. The Rust shim owns
 * the backing storage (a `SubscriberBuffer`) and fills this
 * descriptor; the C shim reads it from `sample_handler`.
 *
 * `head` / `tail` are monotonic counters accessed with atomics on
 * both sides — the slot index is `counter % slot_count`.
 */
typedef struct zpico_ring_desc_t {
  /**
   * `slot_count * payload_stride` bytes of payload storage.
   */
  uint8_t *payload_base;
  /**
   * Bytes between payload slot starts.
   */
  size_t payload_stride;
  /**
   * `slot_count * att_stride` bytes of attachment storage.
   */
  uint8_t *att_base;
  /**
   * Bytes between attachment slot starts.
   */
  size_t att_stride;
  /**
   * Number of ring slots N.
   */
  size_t slot_count;
  /**
   * `slot_count` entries — per-slot payload length.
   */
  size_t *payload_len;
  /**
   * `slot_count` entries — per-slot attachment length.
   */
  size_t *att_len;
  /**
   * Consumer counter — written only by the Rust shim.
   */
  size_t *head;
  /**
   * Producer counter — written only by the C shim.
   */
  size_t *tail;
} zpico_ring_desc_t;

/**
 * Zero-copy callback: data pointer is borrowed from zenoh-pico's receive buffer.
 * Only valid during the callback invocation. Requires `unstable-zenoh-api` feature.
 *
 * # Parameters
 * * `data` - Pointer to payload in zenoh-pico's internal buffer (borrowed, NOT owned)
 * * `len` - Length of payload in bytes
 * * `attachment` - Pointer to attachment buffer (may be NULL)
 * * `attachment_len` - Length of attachment in bytes
 * * `ctx` - User-provided context pointer
 */
typedef void (*ZpicoZeroCopyCallback)(const uint8_t *data,
                                      size_t len,
                                      const uint8_t *attachment,
                                      size_t attachment_len,
                                      void *ctx);

/**
 * Callback function type for receiving queries (service requests).
 *
 * # Parameters
 * * `keyexpr` - Key expression string (not null-terminated)
 * * `keyexpr_len` - Length of key expression
 * * `payload` - Pointer to request payload (may be NULL)
 * * `payload_len` - Length of payload in bytes
 * * `ctx` - User-provided context pointer
 */
typedef void (*ZpicoQueryCallback)(const char *keyexpr,
                                   size_t keyexpr_len,
                                   const uint8_t *payload,
                                   size_t payload_len,
                                   void *ctx);

/**
 * Acquire a free slot from the C shim's session pool. Returns NULL when
 * the pool (`ZPICO_MAX_SESSIONS`) is exhausted. Pair with
 * `zpico_session_release` after `zpico_close`.
 */
/**
 * Return a slot to the pool. Call after `zpico_close`; the pointer is
 * invalid afterwards.
 */
/**
 * Phase 124.F.2 — wire-level connectivity probe. Returns 0
 * on success, `ZPICO_ERR_*` on failure.
 */
/**
 * Phase 124.E.3 — streamed publish via zenoh-pico's
 * `z_bytes_writer` API. `chunk_cb` is invoked repeatedly with
 * up to 1 KiB buffers until `total_len` bytes have landed.
 * `attachment` carries the ROS-interop metadata (seq + source
 * timestamp + GID); pass NULL / 0 for a bare publish.
 */
/**
 * Phase 99.F: zero-copy publish via z_bytes_from_static_buf.
 * Caller guarantees `data` outlives the call.
 */
/**
 * Phase 237 — reply-slot index from the most recent query callback (the
 * deferred-reply seq); call from inside the synchronous query callback.
 */
/**
 * Phase 108.C.zenoh.4-followup — count of liveliness-token
 * replies on this slot. Used by the subscriber-side
 * `LivelinessChanged` bridge to surface `alive_count > 1`.
 */
/**
 * phase-381 W1 — a liveliness query that KEEPS its replies' keyexprs.
 * Poll with `zpico_liveliness_get_check`, then read with the two below.
 */
/**
 * How many keyexprs were STORED — compare against
 * `zpico_liveliness_get_count` (how many ARRIVED) to detect truncation.
 * Has the collecting sweep FINISHED? `zpico_liveliness_get_check` returns
 * 1 on the FIRST reply, so restarting on that truncates enumeration.
 */
/**
 * Copy stored keyexpr `index` into `out`. Returns bytes written excluding
 * the NUL, or a negative `ZPICO_ERR_*`.
 */
/**
 * phase-428 W13 — the PURE half of the graph-cache sample handler: apply
 * one liveliness sample to a NUL-separated token set in a caller buffer.
 * PUT inserts once (a duplicate is a no-op), DELETE removes and closes the
 * gap, a PUT that does not fit is counted in `dropped` and never truncated.
 * Returns 1 if the set changed, 0 if not, `ZPICO_ERR_INVALID` for NULL.
 * Reachable without a session so the set semantics are testable against
 * the real C code.
 */
/**
 * The PURE half of `zpico_liveliness_entry`: index into a NUL-separated
 * run. Reachable without a live session, which is why the graph cache
 * reuses it to walk its snapshot instead of growing a second walk.
 */
/**
 * phase-381 / issue 0903 — the GRAPH CACHE, which replaces the per-question
 * liveliness sweep.
 *
 * A liveliness get is an INTEREST under the hood, and a token only reaches
 * a get's callback when the router tags its declaration with that interest
 * id. Measured against a live `rmw_zenoh_cpp` talker, two sweeps in flight
 * did not both receive replies, and a single sweep saw 2-4 of the dozen
 * tokens the talker declares — a different subset each run. A SUBSCRIBER
 * with `history` is what `rmw_zenoh_cpp` uses for its own graph cache and
 * removes the class: one standing declaration, current tokens delivered
 * once, later changes pushed.
 *
 * Idempotent, so every graph entry point may call it without coordinating.
 */
/**
 * Stop the cache and release the subscriber. Idempotent.
 */
/**
 * How many tokens the cache holds, and how many did not fit.
 */
/**
 * Copy cached keyexpr `index` into `out`, NUL-terminated. ONE entry per
 * call, under the C side's lock — the cache is sized for a real ROS graph
 * (tens of KB), which cannot live on an embedded caller's stack, and this
 * keeps that capacity a fact about the C side alone.
 */
/**
 * The session's pool index (0..ZPICO_MAX_SESSIONS), or -1 if the handle is
 * not a valid pool slot. Used to scope the Rust shim's process-global
 * service-buffer / reply-waker tables per session (issue 0376).
 */
/**
 * Acquire a free slot from the C shim's session pool. Returns NULL when
 * the pool (`ZPICO_MAX_SESSIONS`) is exhausted. Pair with
 * `zpico_session_release` after `zpico_close`.
 */
struct zpico_session_t *zpico_session_acquire(void);

/**
 * Return a slot to the pool. Call after `zpico_close`; the pointer is
 * invalid afterwards.
 */
void zpico_session_release(struct zpico_session_t *_session);

/**
 * The session's pool index (0..ZPICO_MAX_SESSIONS), or -1 if invalid.
 * Scopes the Rust shim's process-global tables per session (issue 0376).
 */
int32_t zpico_session_index(struct zpico_session_t *_session);

/**
 * Initialize zenoh configuration with client mode and connect locator.
 *
 * # Parameters
 * * `locator` - Connection string (e.g., "tcp/192.168.1.1:7447"), null-terminated.
 *   Can be NULL to use default.
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_init(struct zpico_session_t *_session, const char *_locator);

/**
 * Initialize zenoh configuration with mode, locator, and properties.
 *
 * # Parameters
 * * `locator` - Connection string (e.g., "tcp/192.168.1.1:7447"), null-terminated.
 *   Can be NULL for peer mode.
 * * `mode` - Session mode string ("client" or "peer"), null-terminated.
 * * `properties` - Array of key-value properties, or NULL.
 * * `num_properties` - Number of properties in the array.
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_init_with_config(struct zpico_session_t *_session,
                               const char *_locator,
                               const char *_mode,
                               const struct zpico_property_t *_properties,
                               size_t _num_properties);

/**
 * Open zenoh session and start background tasks (if threaded backend).
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_open(struct zpico_session_t *_session);

/**
 * Check if session is currently open.
 *
 * # Returns
 * Non-zero if open, 0 if closed.
 */
int32_t zpico_is_open(struct zpico_session_t *_session);

/**
 * Phase 124.F.2 — wire-level connectivity probe.
 *
 * Returns 0 on success (transport accepted a keep-alive frame),
 * `ZPICO_ERR_SESSION` if no session is open, `ZPICO_ERR_TIMEOUT`
 * if the send failed (treated as a probe timeout — caller maps
 * to `NROS_RMW_RET_TIMEOUT`).
 */
int32_t zpico_send_keep_alive(struct zpico_session_t *_session);

/**
 * Phase 124.E.3 — streamed publish driven by `z_bytes_writer`.
 *
 * Returns 0 on success, `ZPICO_ERR_*` on failure.
 */
int32_t zpico_publish_streamed(struct zpico_session_t *_session,
                               int32_t _handle,
                               size_t _total_len,
                               void (*_chunk_cb)(uint8_t *out_buf,
                                                 size_t cap,
                                                 size_t *out_written,
                                                 void *user_ctx),
                               void *_user_ctx,
                               const uint8_t *_attachment,
                               size_t _attachment_len);

/**
 * Close the session and clean up all resources.
 */
void zpico_close(struct zpico_session_t *_session);

/**
 * Configure scheduling attributes for zenoh-pico read and lease background tasks.
 *
 * Must be called between `zpico_init()` and `zpico_open()`.  If not called,
 * `zpico_open()` passes NULL to zenoh-pico (platform defaults).
 *
 * Priority and stack values are platform-specific (already mapped by the caller).
 */
void zpico_set_task_config(uint32_t _read_priority,
                           uint32_t _read_stack_bytes,
                           uint32_t _lease_priority,
                           uint32_t _lease_stack_bytes);

/**
 * Declare a publisher for the given key expression.
 *
 * # Parameters
 * * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
 *
 * # Returns
 * Publisher handle (>= 0) on success, negative error code on failure.
 */
int32_t zpico_declare_publisher(struct zpico_session_t *_session, const char *_keyexpr);

/**
 * Declare a publisher with options (stub). `_is_express` mirrors the real
 * shim's phase-279 express hint.
 */
int32_t zpico_declare_publisher_ex(struct zpico_session_t *_session,
                                   const char *_keyexpr,
                                   int32_t _is_express);

/**
 * Publish data using publisher handle.
 *
 * # Parameters
 * * `handle` - Publisher handle from zpico_declare_publisher()
 * * `data` - Pointer to data buffer
 * * `len` - Length of data in bytes
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_publish(struct zpico_session_t *_session,
                      int32_t _handle,
                      const uint8_t *_data,
                      size_t _len);

/**
 * Undeclare a publisher.
 *
 * # Parameters
 * * `handle` - Publisher handle
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_undeclare_publisher(struct zpico_session_t *_session, int32_t _handle);

/**
 * Declare a subscriber for the given key expression.
 *
 * # Parameters
 * * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
 * * `callback` - Callback function to invoke when samples arrive
 * * `ctx` - User context pointer passed to callback
 *
 * # Returns
 * Subscriber handle (>= 0) on success, negative error code on failure.
 */
int32_t zpico_declare_subscriber(struct zpico_session_t *_session,
                                 const char *_keyexpr,
                                 ZpicoCallback _callback,
                                 void *_ctx);

/**
 * Declare a subscriber with attachment support for RMW compatibility.
 *
 * # Parameters
 * * `keyexpr` - Key expression string (e.g., "demo/topic"), null-terminated.
 * * `callback` - Callback function to invoke when samples arrive (includes attachment)
 * * `ctx` - User context pointer passed to callback
 *
 * # Returns
 * Subscriber handle (>= 0) on success, negative error code on failure.
 */
int32_t zpico_declare_subscriber_with_attachment(struct zpico_session_t *_session,
                                                 const char *_keyexpr,
                                                 ZpicoCallbackWithAttachment _callback,
                                                 void *_ctx);

/**
 * Declare a subscriber with direct-write to a Rust buffer.
 *
 * The C shim reads the payload directly into `buf_ptr` using
 * `z_bytes_reader_read()`, avoiding a malloc. The notify callback
 * is called after the write completes, providing only the length
 * and attachment.
 *
 * # Parameters
 * * `keyexpr` - Key expression string, null-terminated.
 * * `buf_ptr` - Pointer to the Rust static buffer for payload
 * * `buf_capacity` - Size of the buffer in bytes
 * * `locked_ptr` - Pointer to the AtomicBool lock flag
 * * `callback` - Notify callback (payload length + attachment)
 * * `ctx` - User context pointer passed to callback
 *
 * # Returns
 * Subscriber handle (>= 0) on success, negative error code on failure.
 */
int32_t zpico_declare_subscriber_direct_write(struct zpico_session_t *_session,
                                              const char *_keyexpr,
                                              uint8_t *_buf_ptr,
                                              size_t _buf_capacity,
                                              const bool *_locked_ptr,
                                              ZpicoNotifyCallback _callback,
                                              void *_ctx);

/**
 * Phase 124.D.3.c — declare a burst-tolerant direct-write
 * subscriber backed by an SPSC ring. Each message lands in the
 * next free ring slot rather than a single shared slot, so a
 * burst arriving between two `take` calls is buffered
 * instead of dropped. The `notify` callback fires once per
 * message for async-waker support.
 *
 * # Parameters
 * * `keyexpr` - Key expression string, null-terminated.
 * * `desc` - Ring descriptor; must outlive the subscriber.
 * * `callback` - Notify callback (per-message arrival signal).
 * * `ctx` - User context pointer passed to callback.
 *
 * # Returns
 * Subscriber handle (>= 0) on success, negative error code on failure.
 */
int32_t zpico_declare_subscriber_ring(struct zpico_session_t *_session,
                                      const char *_keyexpr,
                                      struct zpico_ring_desc_t *_desc,
                                      ZpicoNotifyCallback _callback,
                                      void *_ctx);

/**
 * Declare a zero-copy subscriber for the given key expression.
 *
 * The callback receives a borrowed pointer directly into zenoh-pico's
 * internal receive buffer. The pointer is only valid during the callback.
 * Requires `Z_FEATURE_UNSTABLE_API` to be enabled.
 *
 * # Parameters
 * * `keyexpr` - Key expression string, null-terminated.
 * * `callback` - Zero-copy callback (borrowed data pointer + attachment)
 * * `ctx` - User context pointer passed to callback
 *
 * # Returns
 * Subscriber handle (>= 0) on success, negative error code on failure.
 */
int32_t zpico_subscribe_zero_copy(struct zpico_session_t *_session,
                                  const char *_keyexpr,
                                  ZpicoZeroCopyCallback _callback,
                                  void *_ctx);

/**
 * Undeclare a subscriber.
 *
 * # Parameters
 * * `handle` - Subscriber handle
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_undeclare_subscriber(struct zpico_session_t *_session, int32_t _handle);

/**
 * Combined poll and keepalive operation.
 *
 * For threaded backends, this is just a brief poll. For polling
 * backends, this handles both network I/O and zenoh protocol
 * maintenance (keep-alives).
 *
 * # Parameters
 * * `timeout_ms` - Maximum time to wait (0 = non-blocking)
 *
 * # Returns
 * Number of events processed, or negative on error.
 */
int32_t zpico_spin_once(struct zpico_session_t *_session, uint32_t _timeout_ms);

/**
 * Check if the current backend uses polling.
 *
 * # Returns
 * true if polling required (smoltcp), false if threaded (Zephyr, POSIX).
 */
bool zpico_uses_polling(void);

/**
 * Get the session's Zenoh ID.
 *
 * # Parameters
 * * `zid_out` - Pointer to 16-byte buffer to receive the ZID
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_get_zid(struct zpico_session_t *_session, uint8_t *_zid_out);

/**
 * Declare a liveliness token for ROS 2 discovery.
 *
 * # Parameters
 * * `keyexpr` - Key expression string, null-terminated.
 *
 * # Returns
 * Liveliness handle (>= 0) on success, negative error code on failure.
 */
int32_t zpico_declare_liveliness(struct zpico_session_t *_session, const char *_keyexpr);

/**
 * Undeclare a liveliness token.
 *
 * # Parameters
 * * `handle` - Liveliness handle
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_undeclare_liveliness(struct zpico_session_t *_session, int32_t _handle);

/**
 * Publish data with an attachment (for RMW compatibility).
 *
 * # Parameters
 * * `handle` - Publisher handle
 * * `data` - Pointer to data buffer
 * * `len` - Length of data in bytes
 * * `attachment` - Pointer to attachment buffer (may be NULL)
 * * `attachment_len` - Length of attachment in bytes
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_publish_with_attachment(struct zpico_session_t *_session,
                                      int32_t _handle,
                                      const uint8_t *_data,
                                      size_t _len,
                                      const uint8_t *_attachment,
                                      size_t _attachment_len);

/**
 * Declare a queryable for receiving service requests.
 *
 * # Parameters
 * * `keyexpr` - Key expression string, null-terminated.
 * * `callback` - Callback function to invoke when queries arrive
 * * `ctx` - User context pointer passed to callback
 *
 * # Returns
 * Queryable handle (>= 0) on success, negative error code on failure.
 */
int32_t zpico_declare_queryable(struct zpico_session_t *_session,
                                const char *_keyexpr,
                                ZpicoQueryCallback _callback,
                                void *_ctx);

/**
 * Undeclare a queryable.
 *
 * # Parameters
 * * `handle` - Queryable handle
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_undeclare_queryable(struct zpico_session_t *_session, int32_t _handle);

/**
 * Reply to a query (must be called within query callback).
 *
 * # Parameters
 * * `keyexpr` - Reply key expression string, null-terminated.
 * * `data` - Pointer to reply data buffer
 * * `len` - Length of data in bytes
 * * `attachment` - Pointer to attachment buffer (may be NULL)
 * * `attachment_len` - Length of attachment in bytes
 *
 * # Returns
 * 0 on success, negative error code on failure.
 */
int32_t zpico_query_reply(struct zpico_session_t *_session,
                          int32_t _queryable_handle,
                          int64_t _reply_seq,
                          const char *_keyexpr,
                          const uint8_t *_data,
                          size_t _len,
                          const uint8_t *_attachment,
                          size_t _attachment_len);

/**
 * Phase 237 — reply-slot index from the most recent query callback (the
 * deferred-reply seq); call from inside the synchronous query callback.
 * Stub returns -1 (no slot) in the pure-Rust no-op build.
 */
int64_t zpico_queryable_take_reply_seq(struct zpico_session_t *_session, int32_t _queryable_handle);

/**
 * Send a query and wait for reply (blocking, for service client).
 *
 * # Parameters
 * * `keyexpr` - Key expression string, null-terminated.
 * * `payload` - Request payload (may be NULL)
 * * `payload_len` - Length of payload in bytes
 * * `reply_buf` - Buffer to receive reply data
 * * `reply_buf_size` - Size of reply buffer
 * * `timeout_ms` - Timeout in milliseconds
 *
 * # Returns
 * Number of bytes in reply on success, negative error code on failure.
 */
int32_t zpico_get(struct zpico_session_t *_session,
                  const char *_keyexpr,
                  const uint8_t *_payload,
                  size_t _payload_len,
                  uint8_t *_reply_buf,
                  size_t _reply_buf_size,
                  uint32_t _timeout_ms);

/**
 * Start a non-blocking query (for async service client).
 *
 * Returns a non-negative slot handle on success, negative error code on failure.
 */
int32_t zpico_get_start(struct zpico_session_t *_session,
                        const char *_keyexpr,
                        const uint8_t *_payload,
                        size_t _payload_len,
                        uint32_t _timeout_ms);

/**
 * Issue 0153 — attachment-carrying query start (rmw_zenoh service interop).
 */
int32_t zpico_get_start_with_attachment(struct zpico_session_t *_session,
                                        const char *_keyexpr,
                                        const uint8_t *_payload,
                                        size_t _payload_len,
                                        const uint8_t *_attachment,
                                        size_t _attachment_len,
                                        uint32_t _timeout_ms);

/**
 * Check for a reply to a pending non-blocking query.
 *
 * Returns positive byte count on reply, 0 if still pending, negative on error/timeout.
 */
int32_t zpico_get_check(struct zpico_session_t *_session,
                        int32_t _handle,
                        uint8_t *_reply_buf,
                        size_t _reply_buf_size);

/**
 * Start a non-blocking liveliness query (for wait_for_service).
 */
int32_t zpico_liveliness_get_start(struct zpico_session_t *_session,
                                   const char *_keyexpr,
                                   uint32_t _timeout_ms);

/**
 * Poll a pending liveliness query.
 *
 * Returns 1 on first matching token reply, 0 if still pending, -9 on
 * timeout (dropper fired without replies), other negative on error.
 */
int32_t zpico_liveliness_get_check(struct zpico_session_t *_session, int32_t _handle);

/**
 * phase-381 W1 — a liveliness query that KEEPS its replies' keyexprs.
 *
 * `zpico_liveliness_get_start` answers "does anything match"; reading the
 * ROS graph needs "WHAT matched", and a liveliness reply carries all of it
 * in the keyexpr. Same slot pool, same start/poll shape — poll with
 * `zpico_liveliness_get_check`, then read with the two below. Costs no
 * extra storage: the slot's reply buffer is dead weight on a liveliness
 * query, whose token payload is empty.
 */
int32_t zpico_liveliness_collect_start(struct zpico_session_t *_session,
                                       const char *_keyexpr,
                                       uint32_t _timeout_ms);

/**
 * Has the collecting sweep FINISHED (dropper fired)? Distinct from
 * `zpico_liveliness_get_check`, which reports the FIRST reply.
 */
int32_t zpico_liveliness_collect_done(struct zpico_session_t *_session, int32_t _handle);

/**
 * How many keyexprs the slot STORED — distinct from
 * `zpico_liveliness_get_count`, which reports how many ARRIVED. They differ
 * exactly when the buffer could not hold an entry, so comparing the two is
 * how a caller learns the enumeration was truncated.
 */
int32_t zpico_liveliness_entry_count(struct zpico_session_t *_session, int32_t _handle);

/**
 * Copy stored keyexpr `index` into `out`, NUL-terminated. Returns the byte
 * count excluding the NUL, `ZPICO_ERR_INVALID` for a bad handle or index,
 * or `ZPICO_ERR_BUFFER` when `cap` cannot hold the entry plus its NUL — a
 * short buffer is refused rather than truncated.
 */
int32_t zpico_liveliness_entry(struct zpico_session_t *_session,
                               int32_t _handle,
                               uint32_t _index,
                               char *_out,
                               size_t _cap);

/**
 * phase-381 / issue 0903 — start the standing graph cache (a liveliness
 * SUBSCRIBER with history), replacing the per-question sweep. Idempotent.
 */
int32_t zpico_graph_cache_start(struct zpico_session_t *_session, const char *_keyexpr);

/**
 * Stop the graph cache and release its subscriber. Idempotent.
 */
int32_t zpico_graph_cache_stop(struct zpico_session_t *_session);

/**
 * How many tokens the graph cache holds; `out_dropped` receives how many
 * did not fit.
 */
int32_t zpico_graph_entry_count(struct zpico_session_t *_session, uint32_t *_out_dropped);

/**
 * Copy cached keyexpr `index` into `out`, NUL-terminated.
 */
int32_t zpico_graph_entry_at(struct zpico_session_t *_session,
                             uint32_t _index,
                             char *_out,
                             size_t _cap);

/**
 * phase-428 W13 — the PURE half of the graph-cache sample handler: apply
 * one liveliness sample (PUT inserts once, DELETE removes and closes the
 * gap, a PUT that does not fit is COUNTED in `dropped`) to a
 * NUL-separated token set in a caller buffer. Split out like
 * `zpico_entry_at` so the set `service_is_ready` answers from is testable
 * without a session. Returns 1 if the set changed, 0 if not,
 * `ZPICO_ERR_INVALID` for a NULL argument.
 */
int32_t zpico_graph_set_apply(uint8_t *_buf,
                              size_t _cap,
                              size_t *_len,
                              uint32_t *_count,
                              uint32_t *_dropped,
                              const char *_key,
                              size_t _klen,
                              bool _remove);

/**
 * The PURE half of `zpico_liveliness_entry`: index into a NUL-separated
 * run. Split out so the walk is testable WITHOUT a live session, because
 * this is where an off-by-one costs a WRONG keyexpr rather than a missing
 * one.
 */
int32_t zpico_entry_at(const uint8_t *_buf,
                       size_t _len,
                       uint32_t _count,
                       uint32_t _index,
                       char *_out,
                       size_t _cap);

/**
 * Phase 108.C.zenoh.4-followup — count of liveliness-token
 * replies on this slot. Used by the subscriber-side
 * `LivelinessChanged` bridge to surface `alive_count > 1`.
 */
int32_t zpico_liveliness_get_count(struct zpico_session_t *_session, int32_t _handle);

/**
 * Register a reply waker callback for async service client support.
 */
void zpico_set_reply_waker(struct zpico_session_t *_session, void (*_func)(int32_t, int32_t));

/**
 * Capture the current clock into an opaque 16-byte buffer.
 * Used by FFI reentrancy guard timeout decomposition.
 */
void zpico_clock_start(uint8_t *_clock_buf);

/**
 * Return elapsed milliseconds since a clock captured by `zpico_clock_start`.
 */
unsigned long zpico_clock_elapsed_ms_since(uint8_t *_clock_buf);

#endif  /* ZPICO_H */
