#pragma once

// Generated by nano_ros_generate_cpp.py - DO NOT EDIT

#include <nano_ros/cdr.hpp>
#include <cstdint>

namespace std_msgs::msg {

struct Float64 {

    double data{0.0};

    /// Serialize to CDR format
    void serialize(nano_ros::CdrWriter& writer) const {
        writer.write_f64(data);
    }

    /// Deserialize from CDR format
    void deserialize(nano_ros::CdrReader& reader) {
        data = reader.read_f64();
    }

    /// Get the ROS type name
    static constexpr const char* type_name() {
        return "std_msgs/msg/Float64";
    }
};

}  // namespace std_msgs::msg
