#pragma once

// Generated by nano_ros_generate_cpp.py - DO NOT EDIT

#include <nano_ros/cdr.hpp>
#include <builtin_interfaces/msg/time.hpp>
#include <string>
#include <cstdint>

namespace std_msgs::msg {

struct Header {

    builtin_interfaces::msg::Time stamp{};
    std::string frame_id{};

    /// Serialize to CDR format
    void serialize(nano_ros::CdrWriter& writer) const {
        stamp.serialize(writer);
        writer.write_string(frame_id);
    }

    /// Deserialize from CDR format
    void deserialize(nano_ros::CdrReader& reader) {
        stamp.deserialize(reader);
        frame_id = reader.read_string();
    }

    /// Get the ROS type name
    static constexpr const char* type_name() {
        return "std_msgs/msg/Header";
    }
};

}  // namespace std_msgs::msg
