#pragma once

// Generated by nano_ros_generate_cpp.py - DO NOT EDIT

#include <nano_ros/cdr.hpp>
#include <cstdint>

namespace std_msgs::msg {

struct Int16 {

    int16_t data{0};

    /// Serialize to CDR format
    void serialize(nano_ros::CdrWriter& writer) const {
        writer.write_i16(data);
    }

    /// Deserialize from CDR format
    void deserialize(nano_ros::CdrReader& reader) {
        data = reader.read_i16();
    }

    /// Get the ROS type name
    static constexpr const char* type_name() {
        return "std_msgs/msg/Int16";
    }
};

}  // namespace std_msgs::msg
