#pragma once

// Generated by nano_ros_generate_cpp.py - DO NOT EDIT

#include <nano_ros/cdr.hpp>
#include <string>
#include <cstdint>

namespace std_msgs::msg {

struct String {

    std::string data{};

    /// Serialize to CDR format
    void serialize(nano_ros::CdrWriter& writer) const {
        writer.write_string(data);
    }

    /// Deserialize from CDR format
    void deserialize(nano_ros::CdrReader& reader) {
        data = reader.read_string();
    }

    /// Get the ROS type name
    static constexpr const char* type_name() {
        return "std_msgs/msg/String";
    }
};

}  // namespace std_msgs::msg
