// emit:ok
// nros-cpp message type — C++ header for embedded systems
// Package: fingerprint-corpus
// Message: Bounded
// Auto-generated by rosidl-codegen — do not edit

#ifndef FINGERPRINT_CORPUS_MSG_BOUNDED_HPP
#define FINGERPRINT_CORPUS_MSG_BOUNDED_HPP

#include <cstdint>
#include <cstddef>

#include "nros/fixed_string.hpp"
#include "nros/fixed_sequence.hpp"
#include "nros/heap_sequence.hpp"
#include "nros/heap_string.hpp"
#include "nros/size_bound.hpp"
#include "nros/serialization_format.hpp"

#include <nros/nros_config_generated.h>

/* RFC-0090 — emitted by nano-ros codegen version 2. */
#define NROS_EMITTED_CODEGEN_VERSION 2

#ifndef NROS_CODEGEN_VERSION
#error "nros: the generated config header did not define NROS_CODEGEN_VERSION. This generated artifact cannot tell whether the runtime accepts it; rebuild the nano-ros runtime so its config header is regenerated."
#elif NROS_EMITTED_CODEGEN_VERSION < NROS_CODEGEN_VERSION_MIN \
   || NROS_EMITTED_CODEGEN_VERSION > NROS_CODEGEN_VERSION
#error "nros: this generated tree was emitted at a codegen version the runtime does not accept (see NROS_EMITTED_CODEGEN_VERSION above against NROS_CODEGEN_VERSION_MIN..NROS_CODEGEN_VERSION in nros_config_generated.h). Regenerate it against the runtime you are building: `nros sync` in a consumer workspace."
#endif

// FFI declarations
extern "C" {
int nros_cpp_publish_fingerprint_corpus_msg_bounded(void* handle, const void* msg);
int nros_cpp_serialize_fingerprint_corpus_msg_bounded(const void* msg, uint8_t* buf, size_t buf_len, size_t* out_len);
int nros_cpp_deserialize_fingerprint_corpus_msg_bounded(const uint8_t* data, size_t len, void* out);
} // extern "C"

namespace fingerprint_corpus { namespace msg {

/// Bounded message structure (repr(C) compatible)
struct Bounded {
    bool flag = {};
    int64_t wide = {};
    uint8_t narrow = {};
    double d = {};
    nros::FixedString<8> label = {};
    int32_t fixed[4] = {};
    nros::FixedSequence<nros::FixedString<8>, 4> labels = {};

    // Type metadata
    static constexpr const char* TYPE_NAME = "fingerprint-corpus::msg::dds_::Bounded_";
    static constexpr const char* TYPE_HASH = "h";
    /// ESTIMATE, not a bound — `rosidl_codegen::types::compute_serialized_size_max`
    /// charges a flat 512 bytes per nested message and a flat default capacity
    /// per string, and always returns a value, so it can never say "unbounded"
    /// and can be SMALLER than the real bound (issue 0964). Kept because
    /// `Subscription<M>`, `Client<Svc>` and the action tiers all stack buffers
    /// on it. Anything sizing a RECEIVE buffer wants RX_MAX_SERIALIZED_SIZE
    /// below.
    static constexpr size_t SERIALIZED_SIZE_MAX = 1170;

    /// Marker: this type states DERIVED bounds, so `nros::rx_size_bound<M>`
    /// reads `rx_size_bound` below instead of falling back to the estimate.
    /// Present whether or not a bound exists — its absence means "generated by
    /// a codegen that had no derivation at all", which is a different fact from
    /// "this type has no bound".
    using nros_derived_size_bounds = void;

    /// Largest CDR payload this type can produce / must be able to receive,
    /// encapsulation header included.
    ///
    /// Computed by `nros_serdes::size::max_serialized_size` over this type's own
    /// schema — THE size rule, not a copy of it — so it cannot disagree with the
    /// Rust `MAX_SERIALIZED_SIZE_XCDR*` const, or with the C header's
    /// `_TX/_RX_MAX_SERIALIZED_SIZE`, for the same type (issue 0896).
    ///
    /// Two constants because the encodings differ: XCDR2 adds a 4-byte DHEADER
    /// and aligns 8-byte primitives to 4 instead of 8. This stack WRITES XCDR1,
    /// so a transmit buffer wants TX; a RECEIVE buffer must hold whichever
    /// encoding a peer negotiated, so it wants RX.
    static constexpr size_t TX_MAX_SERIALIZED_SIZE = 133;
    static constexpr size_t RX_MAX_SERIALIZED_SIZE = 136;

    /// The two constants above, reachable UNIFORMLY across bounded and unbounded
    /// types — see the unbounded arm, where these are the poison. A generic
    /// consumer writes `nros::rx_size_bound<M>::value`, never the constant, so
    /// one spelling works for every message type and a type with no bound
    /// reports so at the point the number is actually needed.
    template <class = void> struct tx_size_bound { static constexpr size_t value = 133; };
    template <class = void> struct rx_size_bound { static constexpr size_t value = 136; };

    /// Publish via FFI (called by Publisher<M>::publish)
    static int ffi_publish(void* handle, const void* msg) {
        return nros_cpp_publish_fingerprint_corpus_msg_bounded(handle, msg);
    }

    /// Serialize to CDR buffer (called by Service/Client/Action)
    static int ffi_serialize(const void* msg, uint8_t* buf, size_t buf_len, size_t* out_len) {
        return nros_cpp_serialize_fingerprint_corpus_msg_bounded(msg, buf, buf_len, out_len);
    }

    /// Deserialize from CDR (called by Subscription<M>::take)
    static int ffi_deserialize(const uint8_t* data, size_t len, void* out) {
        return nros_cpp_deserialize_fingerprint_corpus_msg_bounded(data, len, out);
    }
};

// Constants — namespace-level `<Msg>_<NAME>` aliases (legacy shape; prefer
// the struct-member `<Msg>::<NAME>` above, which matches rosidl C++).

}} // namespace fingerprint_corpus::msg

// RFC-0088 D5 — state this type's serialization format.
//
// `nros::format_of<M>` defaults to CDR (the C++ mirror of the defaulted
// `nros_core::RosMessage::SERIALIZATION_FORMAT_ID`), so this specialization
// changes no answer today. It is emitted anyway because a generated type should
// STATE its format rather than inherit one: this pack emits a CDR serializer,
// which is a fact about the GENERATOR, and a future non-CDR pack specializes the
// same slot instead of silently riding the default.
//
// `nros::Node::create_publisher` / `create_subscription` static_assert on this
// against the format the linked backend speaks — one image, one backend, one
// encoding.
namespace nros {
template <> struct format_of<::fingerprint_corpus::msg::Bounded> {
    static constexpr SerializationFormat value = SerializationFormat::Cdr;
};
} // namespace nros

#endif // FINGERPRINT_CORPUS_MSG_BOUNDED_HPP