// emit:ok
// nros-c service type - C implementation
// Package: fingerprint-corpus
// Service: Probe
// Auto-generated by rosidl-codegen - do not edit

#include "fingerprint_corpus_srv_probe.h"
#include <nros/types.h>
#include <nros/cdr.h>
// Issue 0345 — heap payload fields (RFC-0033 `mode = "heap"`) malloc on
// deserialize and are freed by the generated `_fini`, so the platform
// allocator seam is needed here exactly as in message_c.c.
#include <nros/platform.h>
#include <string.h>

// Type support structure
static const struct nros_service_type_t fingerprint_corpus_srv_probe_type_support = {
    .type_name = "fingerprint-corpus::srv::dds_::Probe_",
    .type_hash = "h",
};

const struct nros_service_type_t* fingerprint_corpus_srv_probe_get_type_support(void) {
    return &fingerprint_corpus_srv_probe_type_support;
}

// ============================================================================
// Request Implementation
// ============================================================================

void fingerprint_corpus_srv_probe_request_init(fingerprint_corpus_srv_probe_request* msg) {
    if (msg == NULL) return;
    memset(msg, 0, sizeof(fingerprint_corpus_srv_probe_request));
}

// Release heap-backed (`mode = "heap"`, RFC-0033) fields. Safe on a zero-inited
// or already-fini'd struct (frees NULL, re-zeroes). No-op when the payload has
// no heap fields. Issue 0345 — the caller owns the payload struct (it rides the
// raw `(data, len)` service/action callbacks), so the caller `_fini`s it, the
// same contract messages have used since RFC-0033.
void fingerprint_corpus_srv_probe_request_fini(fingerprint_corpus_srv_probe_request* msg) {
    if (msg == NULL) return;
    nros_platform_free(msg->items.data);
    msg->items.data = NULL;
    msg->items.size = 0;
    msg->items.capacity = 0;
}

int32_t fingerprint_corpus_srv_probe_request_serialize(const fingerprint_corpus_srv_probe_request* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size) {
    if (msg == NULL || buffer == NULL) return -1;

    uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // phase-303 W4 (#0267) — edition-appropriate encapsulation header + DHEADER.
    if (nros_cdr_write_encaps_header(&ptr, end) < 0) return -1;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)
    (void)origin;
    int64_t __dh = nros_cdr_begin_dheader(&ptr, end, origin);
    if (__dh < -1) return -1;
    if (nros_cdr_write_u32(&ptr, end, origin, msg->items.size) < 0) return -1;
    for (size_t i = 0; i < msg->items.size; ++i) {
        if (nros_cdr_write_i64(&ptr, end, origin, msg->items.data[i]) < 0) return -1;
    }
    if (nros_cdr_write_string(&ptr, end, origin, msg->note) < 0) return -1;

    if (nros_cdr_end_dheader(__dh, &ptr, end, origin) < 0) return -1;
    if (serialized_size != NULL) {
        *serialized_size = (size_t)(ptr - buffer);
    }
    return 0;
}

int32_t fingerprint_corpus_srv_probe_request_deserialize(fingerprint_corpus_srv_probe_request* msg, const uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    const uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // phase-303 W4 (#0267) — skip the encapsulation header + read the DHEADER.
    if (ptr + 4 > end) return -1;
    ptr += 4;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)
    (void)origin;
    int64_t __dh = nros_cdr_begin_dheader_read(&ptr, end, origin);
    if (__dh < -1) return -1;

    fingerprint_corpus_srv_probe_request_init(msg);
    {
        uint32_t len;
        if (nros_cdr_read_u32(&ptr, end, origin, &len) < 0) return -1;
        // Heap sequence (RFC-0033): allocate exactly `len` elements; freed by
        // fingerprint_corpus_srv_probe_request_fini. A re-deserialize leaks the prior buffer unless
        // the caller _fini's first.
        if (len > 0) {
            // `len` is wire data: a bare `(size_t)len * sizeof` wraps on a
            // 32-bit target and under-allocates (issue 1149's class).
            size_t bytelen;
            if (nros_cdr_seq_byte_len(len, sizeof(*msg->items.data), SIZE_MAX, &bytelen) < 0) return -1;
            msg->items.data = nros_platform_malloc(bytelen);
            if (msg->items.data == NULL) return -1;
        } else {
            msg->items.data = NULL;
        }
        msg->items.size = len;
        msg->items.capacity = len;
        for (size_t i = 0; i < len; ++i) {
            if (nros_cdr_read_i64(&ptr, end, origin, &msg->items.data[i]) < 0) {
                nros_platform_free(msg->items.data);
                msg->items.data = NULL;
                msg->items.size = 0;
                msg->items.capacity = 0;
                return -1;
            }
        }
    }
    if (nros_cdr_read_string(&ptr, end, origin, msg->note, sizeof(msg->note)) < 0) return -1;

    if (nros_cdr_end_dheader_read(__dh, &ptr, end, origin) < 0) return -1;
    return 0;
}

// ============================================================================
// Response Implementation
// ============================================================================

void fingerprint_corpus_srv_probe_response_init(fingerprint_corpus_srv_probe_response* msg) {
    if (msg == NULL) return;
    memset(msg, 0, sizeof(fingerprint_corpus_srv_probe_response));
}

// Release heap-backed (`mode = "heap"`, RFC-0033) fields. Safe on a zero-inited
// or already-fini'd struct (frees NULL, re-zeroes). No-op when the payload has
// no heap fields. Issue 0345 — the caller owns the payload struct (it rides the
// raw `(data, len)` service/action callbacks), so the caller `_fini`s it, the
// same contract messages have used since RFC-0033.
void fingerprint_corpus_srv_probe_response_fini(fingerprint_corpus_srv_probe_response* msg) {
    if (msg == NULL) return;
}

int32_t fingerprint_corpus_srv_probe_response_serialize(const fingerprint_corpus_srv_probe_response* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size) {
    if (msg == NULL || buffer == NULL) return -1;

    uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // phase-303 W4 (#0267) — edition-appropriate encapsulation header + DHEADER.
    if (nros_cdr_write_encaps_header(&ptr, end) < 0) return -1;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)
    (void)origin;
    int64_t __dh = nros_cdr_begin_dheader(&ptr, end, origin);
    if (__dh < -1) return -1;
    if (nros_cdr_write_i64(&ptr, end, origin, msg->sum) < 0) return -1;
    if (nros_cdr_write_u32(&ptr, end, origin, msg->lines.size) < 0) return -1;
    for (size_t i = 0; i < msg->lines.size; ++i) {
        if (nros_cdr_write_string(&ptr, end, origin, msg->lines.data[i]) < 0) return -1;
    }

    if (nros_cdr_end_dheader(__dh, &ptr, end, origin) < 0) return -1;
    if (serialized_size != NULL) {
        *serialized_size = (size_t)(ptr - buffer);
    }
    return 0;
}

int32_t fingerprint_corpus_srv_probe_response_deserialize(fingerprint_corpus_srv_probe_response* msg, const uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    const uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // phase-303 W4 (#0267) — skip the encapsulation header + read the DHEADER.
    if (ptr + 4 > end) return -1;
    ptr += 4;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)
    (void)origin;
    int64_t __dh = nros_cdr_begin_dheader_read(&ptr, end, origin);
    if (__dh < -1) return -1;

    fingerprint_corpus_srv_probe_response_init(msg);
    if (nros_cdr_read_i64(&ptr, end, origin, &msg->sum) < 0) return -1;
    {
        uint32_t len;
        if (nros_cdr_read_u32(&ptr, end, origin, &len) < 0) return -1;
        msg->lines.size = len;
        if (len > 64) return -1;
        for (size_t i = 0; i < len; ++i) {
            if (nros_cdr_read_string(&ptr, end, origin, msg->lines.data[i], sizeof(msg->lines.data[i])) < 0) return -1;
        }
    }

    if (nros_cdr_end_dheader_read(__dh, &ptr, end, origin) < 0) return -1;
    return 0;
}