// emit:ok
// nros-cpp message type — C++ header for embedded systems
// Package: fingerprint-corpus
// Message: Shapes
// Auto-generated by rosidl-codegen — do not edit

#ifndef FINGERPRINT_CORPUS_MSG_SHAPES_HPP
#define FINGERPRINT_CORPUS_MSG_SHAPES_HPP

#include <cstdint>
#include <cstddef>

#include "nros/fixed_string.hpp"
#include "nros/fixed_sequence.hpp"
#include "nros/heap_sequence.hpp"
#include "nros/heap_string.hpp"
#include "nros/size_bound.hpp"
#include "nros/serialization_format.hpp"
#include "nros/span.hpp"

#include <nros/nros_config_generated.h>

/* RFC-0090 — emitted by nano-ros codegen version 3. */
#define NROS_EMITTED_CODEGEN_VERSION 3

#ifndef NROS_CODEGEN_VERSION
#error "nros: the generated config header did not define NROS_CODEGEN_VERSION. This generated artifact cannot tell whether the runtime accepts it; rebuild the nano-ros runtime so its config header is regenerated."
#elif NROS_EMITTED_CODEGEN_VERSION < NROS_CODEGEN_VERSION_MIN \
   || NROS_EMITTED_CODEGEN_VERSION > NROS_CODEGEN_VERSION
#error "nros: this generated tree was emitted at a codegen version the runtime does not accept (see NROS_EMITTED_CODEGEN_VERSION above against NROS_CODEGEN_VERSION_MIN..NROS_CODEGEN_VERSION in nros_config_generated.h). Regenerate it against the runtime you are building: `nros sync` in a consumer workspace."
#endif

// FFI declarations
extern "C" {
int nros_cpp_publish_fingerprint_corpus_msg_shapes(void* handle, const void* msg);
int nros_cpp_serialize_fingerprint_corpus_msg_shapes(const void* msg, uint8_t* buf, size_t buf_len, size_t* out_len);
int nros_cpp_deserialize_fingerprint_corpus_msg_shapes(const uint8_t* data, size_t len, void* out);
int nros_cpp_deserialize_fingerprint_corpus_msg_shapes_borrowed(const uint8_t* data, size_t len, void* out);
} // extern "C"

namespace fingerprint_corpus { namespace msg {

/// Shapes message structure (repr(C) compatible)
struct Shapes {
    bool flag = {};
    int8_t i8_v = {};
    uint8_t u8_v = {};
    int16_t i16_v = {};
    uint16_t u16_v = {};
    int32_t i32_v = {};
    uint32_t u32_v = {};
    int64_t i64_v = {};
    uint64_t u64_v = {};
    float f32_v = {};
    double f64_v = {};
    nros::FixedString<32> text = {};
    nros::HeapSequence<int64_t> seq_prim = {};
    nros::FixedSequence<nros::FixedString<256>, 64> seq_string = {};
    double arr_fixed[3] = {};
    nros::FixedSequence<int32_t, 4> seq_bounded = {};
    nros::FixedString<8> str_bounded = {};

    // Type metadata
    static constexpr const char* TYPE_NAME = "fingerprint-corpus::msg::dds_::Shapes_";
    static constexpr const char* TYPE_HASH = "h";
    /// ESTIMATE, not a bound — `rosidl_codegen::types::compute_serialized_size_max`
    /// charges a flat 512 bytes per nested message and a flat default capacity
    /// per string, and always returns a value, so it can never say "unbounded"
    /// and can be SMALLER than the real bound (issue 0964). Kept because
    /// `Subscription<M>`, `Client<Svc>` and the action tiers all stack buffers
    /// on it. Anything sizing a RECEIVE buffer wants RX_MAX_SERIALIZED_SIZE
    /// below.
    static constexpr size_t SERIALIZED_SIZE_MAX = 18137;

    /// Marker: this type states DERIVED bounds, so `nros::rx_size_bound<M>`
    /// reads `rx_size_bound` below instead of falling back to the estimate.
    /// Present whether or not a bound exists — its absence means "generated by
    /// a codegen that had no derivation at all", which is a different fact from
    /// "this type has no bound".
    using nros_derived_size_bounds = void;

    /// NO size bound is stated for this type.
    ///
    /// Reason: unbounded members: text (string), seq_prim (sequence<T>), seq_string (sequence<T>)
    ///
    /// "unbounded member" means the bound was computed and does not exist —
    /// bound the field in the `.msg` (`string<=64`), or give it an INLINE `cap`
    /// in `nros-codegen.toml` (`[fields]` / `[types]` / `[packages]` /
    /// `[defaults]`). A `heap` or `view` cap is a sizing hint nothing enforces
    /// (RFC-0033 "What each mode GUARANTEES"), so it deliberately does not
    /// bound. EVERY offending member is listed above, so one build names
    /// everything there is to fix (phase-403 W0). "could not be resolved" means
    /// the bound was NOT computed, because a nested type was not reachable;
    /// that is a search-path problem, not a property of the message.
    ///
    /// `TX_MAX_SERIALIZED_SIZE` / `RX_MAX_SERIALIZED_SIZE` are therefore ABSENT,
    /// and these two templates are the POISON that replaces them (issue 0896
    /// layer 5). A `static constexpr` member cannot be poisoned — its
    /// initializer is evaluated when the class is defined, so a bad one would
    /// break every translation unit that merely INCLUDES this header, including
    /// one that only publishes. A class template is evaluated when it is
    /// INSTANTIATED, so the error arrives exactly where a number was asked for,
    /// and it names this type and the member that costs it the bound instead of
    /// reporting an undeclared identifier.
    template <class NROS_size_bound_required = void>
    struct tx_size_bound {
        static_assert(::nros::detail::size_bound_dependent_false<NROS_size_bound_required>::value,
                      "NROS_UNBOUNDED__fingerprint_corpus_msg_shapes__field_text: fingerprint-corpus/Shapes states no serialized-size bound -- unbounded members: text (string), seq_prim (sequence<T>), seq_string (sequence<T>). A bound must EXIST before a buffer can be sized from it: bound the field in the .msg (`string<=64`, `int32[<=8]`), or give it an INLINE `cap` in nros-codegen.toml. To size this subscription by hand instead, pass an explicit byte count: nros::bind_subscription_sized<M, C, Method>(node, topic, self, qos, rx_bytes). If the reason says a nested type could NOT BE RESOLVED, that is a search-path problem and not a property of the message.");
        static constexpr size_t value = 0;
    };
    template <class NROS_size_bound_required = void>
    struct rx_size_bound {
        static_assert(::nros::detail::size_bound_dependent_false<NROS_size_bound_required>::value,
                      "NROS_UNBOUNDED__fingerprint_corpus_msg_shapes__field_text: fingerprint-corpus/Shapes states no serialized-size bound -- unbounded members: text (string), seq_prim (sequence<T>), seq_string (sequence<T>). A bound must EXIST before a buffer can be sized from it: bound the field in the .msg (`string<=64`, `int32[<=8]`), or give it an INLINE `cap` in nros-codegen.toml. To size this subscription by hand instead, pass an explicit byte count: nros::bind_subscription_sized<M, C, Method>(node, topic, self, qos, rx_bytes). If the reason says a nested type could NOT BE RESOLVED, that is a search-path problem and not a property of the message.");
        static constexpr size_t value = 0;
    };

    /// Publish via FFI (called by Publisher<M>::publish)
    static int ffi_publish(void* handle, const void* msg) {
        return nros_cpp_publish_fingerprint_corpus_msg_shapes(handle, msg);
    }

    /// Serialize to CDR buffer (called by Service/Client/Action)
    static int ffi_serialize(const void* msg, uint8_t* buf, size_t buf_len, size_t* out_len) {
        return nros_cpp_serialize_fingerprint_corpus_msg_shapes(msg, buf, buf_len, out_len);
    }

    /// Deserialize from CDR (called by Subscription<M>::take)
    static int ffi_deserialize(const uint8_t* data, size_t len, void* out) {
        return nros_cpp_deserialize_fingerprint_corpus_msg_shapes(data, len, out);
    }
};

/// Borrowed (zero-copy) view of Shapes — RFC-0033 `borrowed` mode.
/// `mode = "borrowed"` fields are `nros::Span`/`StringView`/`LeSpan` pointing
/// into the CDR receive buffer (set by `deserialize_view`); other fields
/// are copied. Layout-compatible with the Rust `ShapesView` repr.
/// The borrowed views are valid ONLY while the source buffer lives (e.g. the
/// subscription callback) — copy out anything retained.
struct ShapesView {
    bool flag = {};
    int8_t i8_v = {};
    uint8_t u8_v = {};
    int16_t i16_v = {};
    uint16_t u16_v = {};
    int32_t i32_v = {};
    uint32_t u32_v = {};
    int64_t i64_v = {};
    uint64_t u64_v = {};
    float f32_v = {};
    double f64_v = {};
    nros::StringView text;
    nros::HeapSequence<int64_t> seq_prim = {};
    nros::FixedSequence<nros::FixedString<256>, 64> seq_string = {};
    double arr_fixed[3] = {};
    nros::FixedSequence<int32_t, 4> seq_bounded = {};
    nros::FixedString<8> str_bounded = {};

    /// Deserialize CDR `data` into a borrowed view. Returns 0 on success, -1 on
    /// error. The view's borrowed pointers alias `data`.
    static int deserialize_view(const uint8_t* data, size_t len, ShapesView* out) {
        return nros_cpp_deserialize_fingerprint_corpus_msg_shapes_borrowed(data, len, out);
    }
};

// Constants — namespace-level `<Msg>_<NAME>` aliases (legacy shape; prefer
// the struct-member `<Msg>::<NAME>` above, which matches rosidl C++).

}} // namespace fingerprint_corpus::msg

// RFC-0088 D5 — state this type's serialization format.
//
// `nros::format_of<M>` defaults to CDR (the C++ mirror of the defaulted
// `nros_core::RosMessage::SERIALIZATION_FORMAT_ID`), so this specialization
// changes no answer today. It is emitted anyway because a generated type should
// STATE its format rather than inherit one: this pack emits a CDR serializer,
// which is a fact about the GENERATOR, and a future non-CDR pack specializes the
// same slot instead of silently riding the default.
//
// `nros::Node::create_publisher` / `create_subscription` static_assert on this
// against the format the linked backend speaks — one image, one backend, one
// encoding.
namespace nros {
template <> struct format_of<::fingerprint_corpus::msg::Shapes> {
    static constexpr SerializationFormat value = SerializationFormat::Cdr;
};
} // namespace nros

#endif // FINGERPRINT_CORPUS_MSG_SHAPES_HPP