// emit:ok
// nros-c message type - C implementation
// Package: fingerprint-corpus
// Message: Shapes
// Auto-generated by rosidl-codegen - do not edit

#include "fingerprint_corpus_msg_shapes.h"
#include <nros/types.h>
#include <nros/cdr.h>
#include <nros/platform.h>
#include <string.h>

// Type support structure
static const nros_message_type_t fingerprint_corpus_msg_shapes_type_support = {
    .type_name = "fingerprint-corpus::msg::dds_::Shapes_",
    .type_hash = "h",
    .serialized_size_max = 0,  // Dynamic/unknown
};

const nros_message_type_t* fingerprint_corpus_msg_shapes_get_type_support(void) {
    return &fingerprint_corpus_msg_shapes_type_support;
}

void fingerprint_corpus_msg_shapes_init(fingerprint_corpus_msg_shapes* msg) {
    if (msg == NULL) return;
    memset(msg, 0, sizeof(fingerprint_corpus_msg_shapes));
}

// Release heap-backed (`mode = "heap"`, RFC-0033) fields. Safe on a zero-inited
// or already-fini'd message (frees NULL, re-zeroes). No-op when the message has
// no heap fields.
void fingerprint_corpus_msg_shapes_fini(fingerprint_corpus_msg_shapes* msg) {
    if (msg == NULL) return;
    nros_platform_free(msg->seq_prim.data);
    msg->seq_prim.data = NULL;
    msg->seq_prim.size = 0;
    msg->seq_prim.capacity = 0;
}

// =============================================================================
// Inline serialize — writes fields only into an already-open CDR stream.
// Used by parent messages, services, and actions that embed this type as a
// nested field. Does NOT write an encapsulation header. `origin` is the
// CDR alignment origin of the surrounding encapsulation.
// =============================================================================
int32_t fingerprint_corpus_msg_shapes_serialize_inline(const fingerprint_corpus_msg_shapes* msg, uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin) {
    if (msg == NULL || ptr_ref == NULL || *ptr_ref == NULL) return -1;
    uint8_t* ptr = *ptr_ref;
    (void)origin; // may be unused for empty structs
    // phase-303 W4 (#0267) — XCDR2 DHEADER wrap (no-op / returns -1 under XCDR1).
    int64_t __dh = nros_cdr_begin_dheader(&ptr, end, origin);
    if (__dh < -1) return -1;
    if (nros_cdr_write_bool(&ptr, end, origin, msg->flag) < 0) return -1;
    if (nros_cdr_write_i8(&ptr, end, origin, msg->i8_v) < 0) return -1;
    if (nros_cdr_write_u8(&ptr, end, origin, msg->u8_v) < 0) return -1;
    if (nros_cdr_write_i16(&ptr, end, origin, msg->i16_v) < 0) return -1;
    if (nros_cdr_write_u16(&ptr, end, origin, msg->u16_v) < 0) return -1;
    if (nros_cdr_write_i32(&ptr, end, origin, msg->i32_v) < 0) return -1;
    if (nros_cdr_write_u32(&ptr, end, origin, msg->u32_v) < 0) return -1;
    if (nros_cdr_write_i64(&ptr, end, origin, msg->i64_v) < 0) return -1;
    if (nros_cdr_write_u64(&ptr, end, origin, msg->u64_v) < 0) return -1;
    if (nros_cdr_write_f32(&ptr, end, origin, msg->f32_v) < 0) return -1;
    if (nros_cdr_write_f64(&ptr, end, origin, msg->f64_v) < 0) return -1;
    if (nros_cdr_write_string(&ptr, end, origin, msg->text) < 0) return -1;
    if (nros_cdr_write_u32(&ptr, end, origin, msg->seq_prim.size) < 0) return -1;
    for (size_t i = 0; i < msg->seq_prim.size; ++i) {
        if (nros_cdr_write_i64(&ptr, end, origin, msg->seq_prim.data[i]) < 0) return -1;
    }
    if (nros_cdr_write_u32(&ptr, end, origin, msg->seq_string.size) < 0) return -1;
    for (size_t i = 0; i < msg->seq_string.size; ++i) {
        if (nros_cdr_write_string(&ptr, end, origin, msg->seq_string.data[i]) < 0) return -1;
    }
    for (size_t i = 0; i < 3; ++i) {
        if (nros_cdr_write_f64(&ptr, end, origin, msg->arr_fixed[i]) < 0) return -1;
    }
    if (nros_cdr_write_u32(&ptr, end, origin, msg->seq_bounded.size) < 0) return -1;
    for (size_t i = 0; i < msg->seq_bounded.size; ++i) {
        if (nros_cdr_write_i32(&ptr, end, origin, msg->seq_bounded.data[i]) < 0) return -1;
    }
    if (nros_cdr_write_string(&ptr, end, origin, msg->str_bounded) < 0) return -1;
    if (nros_cdr_end_dheader(__dh, &ptr, end, origin) < 0) return -1;
    *ptr_ref = ptr;
    return 0;
}

// =============================================================================
// Public serialize — writes a fresh 4-byte CDR encapsulation header then
// delegates to the inline serializer.
// =============================================================================
int32_t fingerprint_corpus_msg_shapes_serialize(const fingerprint_corpus_msg_shapes* msg, uint8_t* buffer, size_t buffer_size, size_t* serialized_size) {
    if (msg == NULL || buffer == NULL) return -1;

    uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Write the edition-appropriate CDR encapsulation header (XCDR1 `00 01` or
    // XCDR2 DELIMITED `00 09`) — phase-303 W4 (#0267).
    if (nros_cdr_write_encaps_header(&ptr, end) < 0) return -1;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)

    if (fingerprint_corpus_msg_shapes_serialize_inline(msg, &ptr, end, origin) < 0) return -1;

    if (serialized_size != NULL) {
        *serialized_size = (size_t)(ptr - buffer);
    }
    return 0;
}

// =============================================================================
// Inline deserialize — reads fields only from an already-open CDR stream.
// =============================================================================
int32_t fingerprint_corpus_msg_shapes_deserialize_inline(fingerprint_corpus_msg_shapes* msg, const uint8_t** ptr_ref, const uint8_t* end, const uint8_t* origin) {
    if (msg == NULL || ptr_ref == NULL || *ptr_ref == NULL) return -1;
    const uint8_t* ptr = *ptr_ref;
    // phase-303 W4 (#0267) — XCDR2 DHEADER read (no-op / -1 under XCDR1).
    int64_t __dh = nros_cdr_begin_dheader_read(&ptr, end, origin);
    if (__dh < -1) return -1;
    (void)origin;
    if (nros_cdr_read_bool(&ptr, end, origin, &msg->flag) < 0) return -1;
    if (nros_cdr_read_i8(&ptr, end, origin, &msg->i8_v) < 0) return -1;
    if (nros_cdr_read_u8(&ptr, end, origin, &msg->u8_v) < 0) return -1;
    if (nros_cdr_read_i16(&ptr, end, origin, &msg->i16_v) < 0) return -1;
    if (nros_cdr_read_u16(&ptr, end, origin, &msg->u16_v) < 0) return -1;
    if (nros_cdr_read_i32(&ptr, end, origin, &msg->i32_v) < 0) return -1;
    if (nros_cdr_read_u32(&ptr, end, origin, &msg->u32_v) < 0) return -1;
    if (nros_cdr_read_i64(&ptr, end, origin, &msg->i64_v) < 0) return -1;
    if (nros_cdr_read_u64(&ptr, end, origin, &msg->u64_v) < 0) return -1;
    if (nros_cdr_read_f32(&ptr, end, origin, &msg->f32_v) < 0) return -1;
    if (nros_cdr_read_f64(&ptr, end, origin, &msg->f64_v) < 0) return -1;
    if (nros_cdr_read_string(&ptr, end, origin, msg->text, sizeof(msg->text)) < 0) return -1;
    {
        uint32_t len;
        if (nros_cdr_read_u32(&ptr, end, origin, &len) < 0) return -1;
        // Heap sequence (RFC-0033): allocate exactly `len` elements; freed by
        // fingerprint_corpus_msg_shapes_fini. A re-deserialize leaks the prior buffer unless
        // the caller _fini's first.
        if (len > 0) {
            // `len` is wire data: a bare `(size_t)len * sizeof` wraps on a
            // 32-bit target and under-allocates (issue 1149's class).
            size_t bytelen;
            if (nros_cdr_seq_byte_len(len, sizeof(*msg->seq_prim.data), SIZE_MAX, &bytelen) < 0) return -1;
            msg->seq_prim.data = nros_platform_malloc(bytelen);
            if (msg->seq_prim.data == NULL) return -1;
        } else {
            msg->seq_prim.data = NULL;
        }
        msg->seq_prim.size = len;
        msg->seq_prim.capacity = len;
        for (size_t i = 0; i < len; ++i) {
            if (nros_cdr_read_i64(&ptr, end, origin, &msg->seq_prim.data[i]) < 0) {
                nros_platform_free(msg->seq_prim.data);
                msg->seq_prim.data = NULL;
                msg->seq_prim.size = 0;
                msg->seq_prim.capacity = 0;
                return -1;
            }
        }
    }
    {
        uint32_t len;
        if (nros_cdr_read_u32(&ptr, end, origin, &len) < 0) return -1;
        msg->seq_string.size = len;
        if (len > 64) return -1;
        for (size_t i = 0; i < len; ++i) {
            if (nros_cdr_read_string(&ptr, end, origin, msg->seq_string.data[i], sizeof(msg->seq_string.data[i])) < 0) return -1;
        }
    }
    for (size_t i = 0; i < 3; ++i) {
        if (nros_cdr_read_f64(&ptr, end, origin, &msg->arr_fixed[i]) < 0) return -1;
    }
    {
        uint32_t len;
        if (nros_cdr_read_u32(&ptr, end, origin, &len) < 0) return -1;
        msg->seq_bounded.size = len;
        if (len > 4) return -1;
        for (size_t i = 0; i < len; ++i) {
            if (nros_cdr_read_i32(&ptr, end, origin, &msg->seq_bounded.data[i]) < 0) return -1;
        }
    }
    if (nros_cdr_read_string(&ptr, end, origin, msg->str_bounded, sizeof(msg->str_bounded)) < 0) return -1;
    if (nros_cdr_end_dheader_read(__dh, &ptr, end, origin) < 0) return -1;
    *ptr_ref = ptr;
    return 0;
}

// =============================================================================
// Public deserialize — skips the 4-byte CDR encapsulation header then
// delegates to the inline deserializer.
// =============================================================================
int32_t fingerprint_corpus_msg_shapes_deserialize(fingerprint_corpus_msg_shapes* msg, const uint8_t* buffer, size_t buffer_size) {
    if (msg == NULL || buffer == NULL) return -1;

    const uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Skip CDR header
    if (ptr + 4 > end) return -1;
    ptr += 4;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)

    fingerprint_corpus_msg_shapes_init(msg);

    if (fingerprint_corpus_msg_shapes_deserialize_inline(msg, &ptr, end, origin) < 0) return -1;
    return 0;
}

// =============================================================================
// Borrowed deserialize (RFC-0033 `borrowed`, Phase 235) — `mode = "borrowed"`
// fields are pointed into `buffer` (zero-copy); other fields are copied exactly
// as the owned deserializer does. `out` is zeroed first so unset pointers are
// NULL. The borrowed views alias `buffer` and are valid only while it lives.
// =============================================================================
int32_t fingerprint_corpus_msg_shapes_deserialize_view(fingerprint_corpus_msg_shapes_View* out, const uint8_t* buffer, size_t buffer_size) {
    if (out == NULL || buffer == NULL) return -1;

    const uint8_t* ptr = buffer;
    const uint8_t* end = buffer + buffer_size;

    // Skip CDR header
    if (ptr + 4 > end) return -1;
    ptr += 4;
    const uint8_t* origin = ptr; // CDR alignment origin (after header)
    (void)origin;

    memset(out, 0, sizeof(*out));
    if (nros_cdr_read_bool(&ptr, end, origin, &out->flag) < 0) return -1;
    if (nros_cdr_read_i8(&ptr, end, origin, &out->i8_v) < 0) return -1;
    if (nros_cdr_read_u8(&ptr, end, origin, &out->u8_v) < 0) return -1;
    if (nros_cdr_read_i16(&ptr, end, origin, &out->i16_v) < 0) return -1;
    if (nros_cdr_read_u16(&ptr, end, origin, &out->u16_v) < 0) return -1;
    if (nros_cdr_read_i32(&ptr, end, origin, &out->i32_v) < 0) return -1;
    if (nros_cdr_read_u32(&ptr, end, origin, &out->u32_v) < 0) return -1;
    if (nros_cdr_read_i64(&ptr, end, origin, &out->i64_v) < 0) return -1;
    if (nros_cdr_read_u64(&ptr, end, origin, &out->u64_v) < 0) return -1;
    if (nros_cdr_read_f32(&ptr, end, origin, &out->f32_v) < 0) return -1;
    if (nros_cdr_read_f64(&ptr, end, origin, &out->f64_v) < 0) return -1;
    if (nros_cdr_borrow_string(&ptr, end, origin, &out->text) < 0) return -1;
    {
        uint32_t len;
        if (nros_cdr_read_u32(&ptr, end, origin, &len) < 0) return -1;
        // Heap sequence (RFC-0033): allocate exactly `len` elements; freed by
        // fingerprint_corpus_msg_shapes_fini. A re-deserialize leaks the prior buffer unless
        // the caller _fini's first.
        if (len > 0) {
            // `len` is wire data: a bare `(size_t)len * sizeof` wraps on a
            // 32-bit target and under-allocates (issue 1149's class).
            size_t bytelen;
            if (nros_cdr_seq_byte_len(len, sizeof(*out->seq_prim.data), SIZE_MAX, &bytelen) < 0) return -1;
            out->seq_prim.data = nros_platform_malloc(bytelen);
            if (out->seq_prim.data == NULL) return -1;
        } else {
            out->seq_prim.data = NULL;
        }
        out->seq_prim.size = len;
        out->seq_prim.capacity = len;
        for (size_t i = 0; i < len; ++i) {
            if (nros_cdr_read_i64(&ptr, end, origin, &out->seq_prim.data[i]) < 0) {
                nros_platform_free(out->seq_prim.data);
                out->seq_prim.data = NULL;
                out->seq_prim.size = 0;
                out->seq_prim.capacity = 0;
                return -1;
            }
        }
    }
    {
        uint32_t len;
        if (nros_cdr_read_u32(&ptr, end, origin, &len) < 0) return -1;
        out->seq_string.size = len;
        if (len > 64) return -1;
        for (size_t i = 0; i < len; ++i) {
            if (nros_cdr_read_string(&ptr, end, origin, out->seq_string.data[i], sizeof(out->seq_string.data[i])) < 0) return -1;
        }
    }
    for (size_t i = 0; i < 3; ++i) {
        if (nros_cdr_read_f64(&ptr, end, origin, &out->arr_fixed[i]) < 0) return -1;
    }
    {
        uint32_t len;
        if (nros_cdr_read_u32(&ptr, end, origin, &len) < 0) return -1;
        out->seq_bounded.size = len;
        if (len > 4) return -1;
        for (size_t i = 0; i < len; ++i) {
            if (nros_cdr_read_i32(&ptr, end, origin, &out->seq_bounded.data[i]) < 0) return -1;
        }
    }
    if (nros_cdr_read_string(&ptr, end, origin, out->str_bounded, sizeof(out->str_bounded)) < 0) return -1;
    return 0;
}